# Generated by Django 5.1 on 2025-12-04 11:52

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="BurningGuideNotification",
            fields=[
                (
                    "device_id",
                    models.CharField(max_length=255, primary_key=True, serialize=False),
                ),
                ("postal_code", models.CharField(max_length=4)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("send_at", models.DateTimeField(null=True)),
            ],
        ),
    ]
