# Generated by Django 6.0.5 on 2026-07-10 09:12

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("bridge", "0001_initial"),
    ]

    operations = [
        migrations.DeleteModel(
            name="BurningGuideNotification",
        ),
    ]
