MOCK_RESPONSE = {
    "content": [
        {
            "id": "VCPS-MX1VV",
            "protocol": "OCPPJ16",
            "accepted": True,
            "reservable": False,
            "configured": True,
            "blocked": False,
            "locationId": "2c0ccfb795d040e39136b7dd1d25f13e",
            "locationName": "AmsterdamBoatTest1",
            "availability": "OPERATIVE",
            "status": "OFFLINE",
            "aggregateStatus": "OFFLINE",
            "localAuthorizationListVersion": 0,
            "localAuths": [],
            "openingTimes": [],
            "evses": [
                {
                    "id": 2,
                    "ocppEvseId": 1,
                    "evseId": "1",
                    "status": "UNKNOWN",
                    "connectors": [
                        {
                            "connectorId": 1,
                            "maxAmp": 32,
                            "phase": 3,
                            "voltage": 400,
                            "current": "AC",
                            "connectorType": "S_309_3P_32A",
                            "status": "UNKNOWN",
                            "availability": "OPERATIVE",
                        }
                    ],
                    "availability": "OPERATIVE",
                    "evseStatus": "ACTIVE",
                    "capabilities": [],
                    "parkingRestrictions": [],
                }
            ],
            "attributes": {
                "vendorId": "Tritium",
                "model": "TRI153-RTM-01",
                "firmwareVersion": "VCPS-062023",
            },
            "confItems": {},
            "firstSeen": "2025-10-30T14:11:12.162+00:00",
            "lastSeen": "2025-10-30T14:11:12.162+00:00",
            "securitySettings": {
                "securedConnection": False,
                "ipAddress": "84.87.178.95",
                "securityProfile": "PROFILE_0",
            },
            "pools": [],
            "lastStatusUpdate": "2025-10-30T14:11:49.174949Z",
        },
        {
            "id": "VCPS-7BMY3",
            "protocol": "OCPPJ16",
            "accepted": True,
            "reservable": False,
            "configured": True,
            "blocked": False,
            "locationId": "a9d9b42ce3eb4d8cbf50bb6aaeaa6357",
            "locationName": "AmsterdamBoatTest3",
            "availability": "OPERATIVE",
            "status": "OCCUPIED",
            "aggregateStatus": "OCCUPIED",
            "localAuthorizationListVersion": 0,
            "localAuths": [],
            "openingTimes": [],
            "evses": [
                {
                    "id": 25,
                    "ocppEvseId": 1,
                    "evseId": "1",
                    "status": "OCCUPIED",
                    "subStatus": "FINISHING",
                    "connectors": [
                        {
                            "connectorId": 1,
                            "maxAmp": 1,
                            "phase": 1,
                            "voltage": 1,
                            "current": "AC",
                            "connectorType": "CEE_7_7",
                            "status": "OCCUPIED",
                            "subStatus": "FINISHING",
                            "availability": "OPERATIVE",
                            "errorCode": "NoError",
                            "lastStatusUpdate": "2026-04-29T12:01:08.428676Z",
                        }
                    ],
                    "availability": "OPERATIVE",
                    "evseStatus": "ACTIVE",
                    "capabilities": [],
                    "parkingRestrictions": [],
                    "lastStatusUpdate": "2026-04-29T12:01:08.428676Z",
                }
            ],
            "attributes": {
                "vendorId": "Alfen BV",
                "model": "NG910-60123",
                "firmwareVersion": "VCPS-062023",
            },
            "confItems": {
                "AllowOfflineTxForUnknownId": "False",
                "AuthorizationCacheEnabled": "False",
                "AuthorizeRemoteTxRequests": "False",
                "BlinkRepeat": "1",
                "ClockAlignedDataInterval": "0",
                "ConnectionTimeOut": "0",
                "ConnectorPhaseRotation": "0.Unknown",
                "ConnectorPhaseRotationMaxLength": "1",
                "GetConfigurationMaxKeys": "34",
                "HeartbeatInterval": "900",
                "LightIntensity": "100",
                "LocalAuthorizeOffline": "False",
                "LocalPreAuthorize": "False",
                "MaxEnergyOnInvalidId": "0",
                "MeterValueSampleInterval": "0",
                "MeterValuesAlignedData": None,
                "MeterValuesAlignedDataMaxLength": "0",
                "MeterValuesSampledData": "Energy.Active.Import.Register",
                "MeterValuesSampledDataMaxLength": "1",
                "MinimumStatusDuration": "0",
                "NumberOfConnectors": "1",
                "ResetRetries": "0",
                "StopTransactionOnEVSideDisconnect": "True",
                "StopTransactionOnInvalidId": "True",
                "StopTxnAlignedData": "",
                "StopTxnAlignedDataMaxLength": "0",
                "StopTxnSampledData": "",
                "StopTxnSampledDataMaxLength": "0",
                "SupportedFeatureProfiles": "Remote Trigger",
                "SupportedFeatureProfilesMaxLength": "1",
                "TransactionMessageAttempts": "0",
                "TransactionMessageRetryInterval": "0",
                "UnlockConnectorOnEVSideDisconnect": "True",
                "WebSocketPingInterval": "0",
            },
            "firstSeen": "2026-03-27T18:20:52.031+00:00",
            "lastSeen": "2026-04-29T12:20:23.814+00:00",
            "securitySettings": {
                "securedConnection": False,
                "ipAddress": "95.97.70.22",
                "securityProfile": "PROFILE_0",
            },
            "pools": [],
            "lastStatusUpdate": "2026-04-29T12:20:26.388640Z",
        },
        {
            "id": "VCPS-7BMY2",
            "protocol": "OCPPJ16",
            "accepted": True,
            "reservable": False,
            "configured": True,
            "blocked": False,
            "locationId": "2c0ccfb795d040e39136b7dd1d25f13e",
            "locationName": "AmsterdamBoatTest1",
            "availability": "OPERATIVE",
            "status": "OPERATIVE",
            "aggregateStatus": "OPERATIVE",
            "localAuthorizationListVersion": 0,
            "localAuths": [],
            "openingTimes": [],
            "evses": [
                {
                    "id": 17,
                    "ocppEvseId": 1,
                    "evseId": "1",
                    "status": "OPERATIVE",
                    "connectors": [
                        {
                            "connectorId": 1,
                            "maxAmp": 1,
                            "phase": 1,
                            "voltage": 1,
                            "maxElectricPower": 22000,
                            "current": "AC",
                            "connectorType": "CEE_7_7",
                            "status": "OPERATIVE",
                            "availability": "OPERATIVE",
                            "errorCode": "NoError",
                            "lastStatusUpdate": "2026-03-31T00:04:06.527209Z",
                        }
                    ],
                    "availability": "OPERATIVE",
                    "evseStatus": "ACTIVE",
                    "capabilities": [],
                    "parkingRestrictions": [],
                    "lastStatusUpdate": "2026-03-31T00:04:06.527209Z",
                }
            ],
            "attributes": {
                "vendorId": "Alfen BV",
                "model": "NG910-60123",
                "firmwareVersion": "VCPS-062023",
            },
            "confItems": {
                "AllowOfflineTxForUnknownId": "False",
                "AuthorizationCacheEnabled": "False",
                "AuthorizeRemoteTxRequests": "False",
                "BlinkRepeat": "1",
                "ClockAlignedDataInterval": "0",
                "ConnectionTimeOut": "0",
                "ConnectorPhaseRotation": "0.Unknown",
                "ConnectorPhaseRotationMaxLength": "1",
                "GetConfigurationMaxKeys": "34",
                "HeartbeatInterval": "900",
                "LightIntensity": "100",
                "LocalAuthorizeOffline": "False",
                "LocalPreAuthorize": "False",
                "MaxEnergyOnInvalidId": "0",
                "MeterValueSampleInterval": "0",
                "MeterValuesAlignedData": None,
                "MeterValuesAlignedDataMaxLength": "0",
                "MeterValuesSampledData": "Energy.Active.Import.Register",
                "MeterValuesSampledDataMaxLength": "1",
                "MinimumStatusDuration": "0",
                "NumberOfConnectors": "1",
                "ResetRetries": "0",
                "StopTransactionOnEVSideDisconnect": "True",
                "StopTransactionOnInvalidId": "True",
                "StopTxnAlignedData": "",
                "StopTxnAlignedDataMaxLength": "0",
                "StopTxnSampledData": "",
                "StopTxnSampledDataMaxLength": "0",
                "SupportedFeatureProfiles": "Remote Trigger",
                "SupportedFeatureProfilesMaxLength": "1",
                "TransactionMessageAttempts": "0",
                "TransactionMessageRetryInterval": "0",
                "UnlockConnectorOnEVSideDisconnect": "True",
                "WebSocketPingInterval": "0",
            },
            "firstSeen": "2026-01-27T19:09:57.426+00:00",
            "lastSeen": "2026-04-13T14:08:25.021+00:00",
            "securitySettings": {
                "securedConnection": False,
                "ipAddress": "188.120.98.169",
                "securityProfile": "PROFILE_0",
            },
            "pools": [],
            "lastStatusUpdate": "2026-04-13T14:08:29.439788Z",
        },
    ],
    "pageable": {
        "pageNumber": 0,
        "pageSize": 10,
        "sort": {"empty": True, "sorted": False, "unsorted": True},
        "offset": 0,
        "paged": True,
        "unpaged": False,
    },
    "last": True,
    "totalPages": 1,
    "totalElements": 3,
    "first": True,
    "size": 10,
    "number": 0,
    "sort": {"empty": True, "sorted": False, "unsorted": True},
    "numberOfElements": 3,
    "empty": False,
}
