MOCK_RESPONSE = {
    "content": [
        {
            "id": "2c0ccabc15d040e39136b7abc125f13e",
            "name": "AmsterdamBoatTest1",
            "address": "Isolatorweg 178",
            "city": "Amsterdam",
            "postalCode": "1234 AM",
            "coordinates": {"latitude": "52.327549", "longitude": "4.972519"},
            "openingTimes": {
                "twentyfourseven": False,
                "regularHours": [
                    {"weekday": 1, "periodBegin": "17:41", "periodEnd": "19:41"},
                    {"weekday": 6, "periodBegin": "13:41", "periodEnd": "17:41"},
                ],
            },
            "chargingStationsIds": ["VCPS-7BMY2", "VCPS-MX1VV", "VCPS-IFZTY"],
            "availableSockets": 0,
            "totalSockets": 3,
            "sockets": [
                {
                    "chargingStationId": "VCPS-7BMY2",
                    "evseId": "1",
                    "status": "FAULTED",
                    "available": False,
                    "maxElectricPower": 22.0,
                },
                {
                    "chargingStationId": "VCPS-IFZTY",
                    "evseId": "1",
                    "status": "OCCUPIED",
                    "available": False,
                },
                {
                    "chargingStationId": "VCPS-MX1VV",
                    "evseId": "1",
                    "status": "UNKNOWN",
                    "available": False,
                },
            ],
        },
        {
            "id": "a102abc17f62a49f5abc10b5709c4d4c",
            "name": "AmsterdamBoatTest2",
            "address": "Transformatorweg 104",
            "city": "Amsterdam",
            "postalCode": "1234 AM",
            "coordinates": {"latitude": "52.387313", "longitude": "4.822313"},
            "openingTimes": {"twentyfourseven": True},
            "chargingStationsIds": [],
            "tariffId": "NLSGMTYVALVHYCHWGFZALJVSWPJKHSICSIK",
            "availableSockets": 0,
            "totalSockets": 0,
        },
        {
            "id": "a9d9b42abc1b4d8abc10bb6aaeaa6357",
            "name": "AmsterdamBoatTest3",
            "address": "Funenkade 7",
            "city": "Amsterdam",
            "postalCode": "1093 SJ",
            "coordinates": {"latitude": "52.366474", "longitude": "4.926436"},
            "openingTimes": {
                "twentyfourseven": False,
                "regularHours": [
                    {"weekday": 1, "periodBegin": "04:15", "periodEnd": "12:15"},
                    {"weekday": 3, "periodBegin": "09:15", "periodEnd": "16:15"},
                    {"weekday": 4, "periodBegin": "09:15", "periodEnd": "15:15"},
                    {"weekday": 2, "periodBegin": "10:15", "periodEnd": "12:15"},
                ],
            },
            "chargingStationsIds": ["VCPS-7BMY3"],
            "tariffId": "NLSGMTRYXYMXMPAOXJFEYLQXIHAYXJPNTOY",
            "tariff": {
                "id": "NLSGMTRYXYMXMPAOXJFEYLQXIHAYXJPNTOY",
                "energyPricePerKwh": 0.23,
                "chargingTimePricePerHour": 0.45,
                "parkingTimePricePerHour": 0.12,
                "flatFeePrice": 1.0,
            },
            "availableSockets": 0,
            "totalSockets": 1,
            "sockets": [
                {
                    "chargingStationId": "VCPS-7BMY3",
                    "evseId": "1",
                    "status": "OCCUPIED",
                    "available": False,
                }
            ],
        },
    ],
    "empty": False,
    "first": True,
    "last": True,
    "number": 0,
    "numberOfElements": 3,
    "pageable": {
        "pageNumber": 0,
        "pageSize": 20,
        "sort": {"empty": False, "sorted": True, "unsorted": False},
        "offset": 0,
        "paged": True,
        "unpaged": False,
    },
    "sort": {"empty": False, "sorted": True, "unsorted": False},
    "totalElements": 3,
    "totalPages": 1,
}
