MOCK_RESPONSE = {
    "content": [
        {
            "id": "a1025467f62a49f5898260b5709c4d4c",
            "countryCode": "NL",
            "partyId": "SGM",
            "publish": False,
            "ocpiPublish": True,
            "publishOnlyTo": [],
            "name": "AmsterdamBoatTest2",
            "address": "Transformatorweg 104",
            "city": "Amsterdam",
            "postalCode": "1234 AM",
            "country": "NLD",
            "coordinates": {"latitude": "52.387313", "longitude": "4.822313"},
            "parkingType": "ALONG_MOTORWAY",
            "timeZone": "Europe/Amsterdam",
            "openingTimes": {
                "regularHours": [],
                "twentyfourseven": True,
                "exceptionalOpenings": [],
                "exceptionalClosings": [],
            },
            "chargingWhenClosed": False,
            "lastUpdated": "2026-03-19T21:00:40.343213Z",
            "chargingStationCount": 0,
            "tariffId": "NLSGMTRYXYMXMPAOXJFEYLQXIHAYXJPNTOY",
            "facilities": [],
        },
        {
            "id": "2c0ccfb795d040e39136b7dd1d25f13e",
            "countryCode": "NL",
            "partyId": "SGM",
            "publish": False,
            "ocpiPublish": True,
            "publishOnlyTo": [],
            "name": "AmsterdamBoatTest1",
            "address": "Isolatorweg 178",
            "city": "Amsterdam",
            "postalCode": "1234 AM",
            "country": "NLD",
            "coordinates": {"latitude": "52.327549", "longitude": "4.972519"},
            "parkingType": "PARKING_LOT",
            "timeZone": "Europe/Amsterdam",
            "openingTimes": {
                "regularHours": [],
                "twentyfourseven": True,
                "exceptionalOpenings": [],
                "exceptionalClosings": [],
            },
            "chargingWhenClosed": False,
            "lastUpdated": "2026-03-31T00:04:06.560502Z",
            "chargingStationCount": 0,
            "tariffId": "NLSGMTRYXYMXMPAOXJFEYLQXIHAYXJPNTOY",
            "facilities": [],
        },
    ],
    "pageable": {
        "pageNumber": 0,
        "pageSize": 20,
        "sort": {"empty": True, "sorted": False, "unsorted": True},
        "offset": 0,
        "paged": True,
        "unpaged": False,
    },
    "last": True,
    "totalPages": 1,
    "totalElements": 2,
    "first": True,
    "size": 20,
    "number": 0,
    "sort": {"empty": True, "sorted": False, "unsorted": True},
    "numberOfElements": 2,
    "empty": False,
}
