MOCK_RESPONSE = {
    "id": "a1025467f62a49f5898260b5709c4d4c",
    "countryCode": "NL",
    "partyId": "SGM",
    "publish": False,
    "ocpiPublish": True,
    "publishOnlyTo": [],
    "name": "AmsterdamBoatTest2",
    "address": "Transformatorweg 104",
    "city": "Amsterdam",
    "postalCode": "1234 AM",
    "country": "NLD",
    "coordinates": {"latitude": "52.387313", "longitude": "4.822313"},
    "parkingType": "ALONG_MOTORWAY",
    "timeZone": "Europe/Amsterdam",
    "openingTimes": {
        "regularHours": [],
        "twentyfourseven": True,
        "exceptionalOpenings": [],
        "exceptionalClosings": [],
    },
    "chargingWhenClosed": False,
    "lastUpdated": "2026-03-19T21:00:40.343213Z",
    "chargingStationCount": 0,
    "chargingStationsIds": ["cs_id_1", "cs_id_2"],
    "tariffId": "NLSGMTRYXYMXMPAOXJFEYLQXIHAYXJPNTOY",
    "facilities": [],
}
