MOCK_RESPONSE = {
    "content": [
        {
            "id": "2c0ccfb795d040e39136b7dd1d25f13e",
            "name": "AmsterdamBoatTest1",
            "address": "Isolatorweg 178",
            "city": "Amsterdam",
            "postalCode": "1234 AM",
            "coordinates": {"latitude": "52.327549", "longitude": "4.972519"},
            "openingTimes": {"twentyfourseven": True},
            "chargingStationsIds": ["VCPS-7BMY2", "VCPS-MX1VV", "VCPS-IFZTY"],
            "availableSockets": 0,
            "totalSockets": 3,
        },
        {
            "id": "a1025467f62a49f5898260b5709c4d4c",
            "name": "AmsterdamBoatTest2",
            "address": "Transformatorweg 104",
            "city": "Amsterdam",
            "postalCode": "1234 AM",
            "coordinates": {"latitude": "52.387313", "longitude": "4.822313"},
            "openingTimes": {"twentyfourseven": True},
            "chargingStationsIds": [],
            "tariffId": "NLSGMTYVALVHYCHWGFZALJVSWPJKHSICSIK",
            "availableSockets": 0,
            "totalSockets": 0,
        },
        {
            "id": "a9d9b42ce3eb4d8cbf50bb6aaeaa6357",
            "name": "AmsterdamBoatTest3",
            "address": "Funenkade 7",
            "city": "Amsterdam",
            "postalCode": "1093 SJ",
            "coordinates": {"latitude": "52.366474", "longitude": "4.926436"},
            "openingTimes": {"twentyfourseven": False},
            "chargingStationsIds": ["VCPS-7BMY3"],
            "tariffId": "NLSGMTRYXYMXMPAOXJFEYLQXIHAYXJPNTOY",
            "tariff": {
                "id": "NLSGMTRYXYMXMPAOXJFEYLQXIHAYXJPNTOY",
                "energyPricePerKwh": 0.23,
                "chargingTimePricePerHour": 0.45,
                "parkingTimePricePerHour": 0.12,
                "flatFeePrice": 1.0,
            },
            "availableSockets": 0,
            "totalSockets": 1,
        },
    ],
    "empty": False,
    "first": True,
    "last": True,
    "number": 0,
    "numberOfElements": 3,
    "pageable": {
        "pageNumber": 0,
        "pageSize": 20,
        "sort": {"empty": False, "sorted": True, "unsorted": False},
        "offset": 0,
        "paged": True,
        "unpaged": False,
    },
    "sort": {"empty": False, "sorted": True, "unsorted": False},
    "totalElements": 3,
    "totalPages": 1,
}
