MOCK_DATA = {
    "type": "FeatureCollection",
    "features": [
        {
            "type": "Feature",
            "geometry": {"type": "Point", "coordinates": [4.88276008, 52.3573507]},
            "properties": {
                "id": "13073916",
                "title": "Zero Flags Project",
                "description": "Museumplein",
                "street": "Museumplein",
                "city": "Amsterdam",
                "website": "http:\/\/Www.zeroflagsproject.nl",
                "meta": [
                    {
                        "key": "type",
                        "title": "Type",
                        "value": "Tentoonstelling",
                        "presenter": "text",
                    },
                    {
                        "key": "stad",
                        "title": "Stad",
                        "value": "Amsterdam",
                        "presenter": "text",
                    },
                    {
                        "key": "datum-start",
                        "title": "Datum start",
                        "value": "8-jul",
                        "presenter": "text",
                    },
                    {
                        "key": "datum-eind",
                        "title": "Datum eind",
                        "value": "29-jul",
                        "presenter": "text",
                    },
                    {
                        "key": "tijd",
                        "title": "Tijd",
                        "value": "doorlopend",
                        "presenter": "text",
                    },
                    {
                        "key": "url",
                        "title": "URL",
                        "value": '<a href="http:\/\/Www.zeroflagsproject.nl" rel="noopener" target="_blank">Www.zeroflagsproject.nl<\/a>',
                        "presenter": "text",
                    },
                ],
            },
        },
        {
            "type": "Feature",
            "geometry": {"type": "Point", "coordinates": [4.89187769, 52.37367138]},
            "properties": {
                "id": "13073919",
                "title": "Queer Amsterdam",
                "description": "De Nieuwe Kerk,  Dam 12 msterdam",
                "street": "Dam 12",
                "city": "Amsterdam",
                "website": "http:\/\/Queer Amsterdam, de roze stad - De Nieuwe Kerk",
                "meta": [
                    {
                        "key": "type",
                        "title": "Type",
                        "value": "Tentoonstelling",
                        "presenter": "text",
                    },
                    {
                        "key": "stad",
                        "title": "Stad",
                        "value": "Amsterdam",
                        "presenter": "text",
                    },
                    {
                        "key": "datum-start",
                        "title": "Datum start",
                        "value": "8-jul",
                        "presenter": "text",
                    },
                    {
                        "key": "datum-eind",
                        "title": "Datum eind",
                        "value": "31-mrt",
                        "presenter": "text",
                    },
                    {
                        "key": "tijd",
                        "title": "Tijd",
                        "value": "doorlopend",
                        "presenter": "text",
                    },
                    {
                        "key": "url",
                        "title": "URL",
                        "value": "Queer Amsterdam, de roze stad - De Nieuwe Kerk",
                        "presenter": "text",
                    },
                ],
            },
        },
        {
            "type": "Feature",
            "geometry": {"type": "Point", "coordinates": [4.91978668, 52.36648685]},
            "properties": {
                "id": "13073922",
                "title": "Tour d'Amour bij Cordaan",
                "description": "Diverse locaties van Cordaan",
                "city": "Amsterdam",
                "meta": [
                    {
                        "key": "type",
                        "title": "Type",
                        "value": "Evenement",
                        "presenter": "text",
                    },
                    {
                        "key": "stad",
                        "title": "Stad",
                        "value": "Amsterdam",
                        "presenter": "text",
                    },
                    {
                        "key": "datum-start",
                        "title": "Datum start",
                        "value": "8-jul",
                        "presenter": "text",
                    },
                    {
                        "key": "datum-eind",
                        "title": "Datum eind",
                        "value": "29-jul",
                        "presenter": "text",
                    },
                ],
            },
        },
        {
            "type": "Feature",
            "geometry": {"type": "Point", "coordinates": [4.89410619, 52.37291108]},
            "properties": {
                "id": "13073925",
                "title": "Pride Art Route 2026 (de datum op de website is ander)",
                "description": "Dam",
                "street": "Dam",
                "city": "Amsterdam",
                "website": "https:\/\/pride.amsterdam\/en\/event\/pride-art-route-2\/",
                "meta": [
                    {
                        "key": "type",
                        "title": "Type",
                        "value": "Evenement &Tentoonstelling",
                        "presenter": "text",
                    },
                    {
                        "key": "stad",
                        "title": "Stad",
                        "value": "Amsterdam",
                        "presenter": "text",
                    },
                    {
                        "key": "datum-start",
                        "title": "Datum start",
                        "value": "4-jul",
                        "presenter": "text",
                    },
                    {
                        "key": "datum-eind",
                        "title": "Datum eind",
                        "value": "9-aug",
                        "presenter": "text",
                    },
                    {
                        "key": "url",
                        "title": "URL",
                        "value": '<a href="https:\/\/pride.amsterdam\/en\/event\/pride-art-route-2\/" rel="noopener" target="_blank">https:\/\/pride.amsterdam\/en\/event\/pride-art-route-2\/<\/a>',
                        "presenter": "text",
                    },
                ],
            },
        },
        {
            "type": "Feature",
            "geometry": {"type": "Point", "coordinates": [4.89410619, 52.37291108]},
            "properties": {
                "id": "13073928",
                "title": "Trans Pride",
                "description": "Dam",
                "street": "Dam",
                "city": "Amsterdam",
                "meta": [
                    {
                        "key": "type",
                        "title": "Type",
                        "value": "Tentoonstelling",
                        "presenter": "text",
                    },
                    {
                        "key": "stad",
                        "title": "Stad",
                        "value": "Amsterdam",
                        "presenter": "text",
                    },
                    {
                        "key": "datum-start",
                        "title": "Datum start",
                        "value": "8-jul",
                        "presenter": "text",
                    },
                    {
                        "key": "datum-eind",
                        "title": "Datum eind",
                        "value": "29-jul",
                        "presenter": "text",
                    },
                ],
            },
        },
        {
            "type": "Feature",
            "geometry": {"type": "Point", "coordinates": [4.85413421, 52.3800775]},
            "properties": {
                "id": "13073931",
                "title": "Pride 2026 in Podium Moza\u00efek",
                "description": "Podium Moza\u00efek, Bos en Lommerweg 191, 1055 DT Amsterdamv",
                "street": "Bos en Lommerweg 191",
                "city": "Amsterdam",
                "meta": [
                    {
                        "key": "type",
                        "title": "Type",
                        "value": "Theather",
                        "presenter": "text",
                    },
                    {
                        "key": "stad",
                        "title": "Stad",
                        "value": "Amsterdam",
                        "presenter": "text",
                    },
                    {
                        "key": "datum-start",
                        "title": "Datum start",
                        "value": "8-jul",
                        "presenter": "text",
                    },
                    {
                        "key": "datum-eind",
                        "title": "Datum eind",
                        "value": "29-jul",
                        "presenter": "text",
                    },
                ],
            },
        },
        {
            "type": "Feature",
            "geometry": {"type": "Point", "coordinates": [4.89410619, 52.37291108]},
            "properties": {
                "id": "13073934",
                "title": "Roze Vlinders 2026",
                "description": "Dam",
                "street": "Dam",
                "city": "Amsterdam",
                "meta": [
                    {
                        "key": "type",
                        "title": "Type",
                        "value": "Concert",
                        "presenter": "text",
                    },
                    {
                        "key": "stad",
                        "title": "Stad",
                        "value": "Amsterdam",
                        "presenter": "text",
                    },
                    {
                        "key": "datum-start",
                        "title": "Datum start",
                        "value": "8-jul",
                        "presenter": "text",
                    },
                    {
                        "key": "datum-eind",
                        "title": "Datum eind",
                        "value": "29-jul",
                        "presenter": "text",
                    },
                ],
            },
        },
        {
            "type": "Feature",
            "geometry": {"type": "Point", "coordinates": [4.88048941, 52.36405127]},
            "properties": {
                "id": "13073937",
                "title": "Poeziefestival: Queer Joy",
                "description": "Theater Bellevue leidsekade 90 1017 PN amsterdam",
                "street": "Theater Bellevue leidsekade 90",
                "city": "Amsterdam",
                "meta": [
                    {
                        "key": "type",
                        "title": "Type",
                        "value": "Spoken Word- Po\u00ebzie",
                        "presenter": "text",
                    },
                    {
                        "key": "stad",
                        "title": "Stad",
                        "value": "Amsterdam",
                        "presenter": "text",
                    },
                    {
                        "key": "datum-start",
                        "title": "Datum start",
                        "value": "8-jul",
                        "presenter": "text",
                    },
                    {
                        "key": "datum-eind",
                        "title": "Datum eind",
                        "value": "29-jul",
                        "presenter": "text",
                    },
                ],
            },
        },
        {
            "type": "Feature",
            "geometry": {"type": "Point", "coordinates": [4.95560836, 52.31601511]},
            "properties": {
                "id": "13073961",
                "title": "Colourful Pride Stage Zuidoost",
                "description": "Anton de Komplein ( tijdens Kwaku)",
                "street": "Anton de Komplein ",
                "city": "Amsterdam",
                "meta": [
                    {
                        "key": "type",
                        "title": "Type",
                        "value": "Evenement",
                        "presenter": "text",
                    },
                    {
                        "key": "stad",
                        "title": "Stad",
                        "value": "Amsterdam",
                        "presenter": "text",
                    },
                    {
                        "key": "datum-start",
                        "title": "Datum start",
                        "value": "11-jul",
                        "presenter": "text",
                    },
                ],
            },
        },
        {
            "type": "Feature",
            "geometry": {"type": "Point", "coordinates": [4.91268106, 52.34733574]},
            "properties": {
                "id": "13073988",
                "title": "Love Swim 2026",
                "description": "Amstel t.h.v. Berlagebrug",
                "street": "Amstel t.h.v. Berlagebrug",
                "city": "Amsterdam",
                "meta": [
                    {
                        "key": "type",
                        "title": "Type",
                        "value": "Sport",
                        "presenter": "text",
                    },
                    {
                        "key": "stad",
                        "title": "Stad",
                        "value": "Amsterdam",
                        "presenter": "text",
                    },
                    {
                        "key": "datum-start",
                        "title": "Datum start",
                        "value": "24-jul",
                        "presenter": "text",
                    },
                ],
            },
        },
        {
            "type": "Feature",
            "geometry": {"type": "Point", "coordinates": [4.89410619, 52.37291108]},
            "properties": {
                "id": "13073991",
                "title": "Pride Walk",
                "description": "De route loopt vanaf de Dam - Rokin - Munt - Vijzelstraat - Weteringschans - Frederiksplein - Utrechtstestraat -Rembrandtplein - Munt - Rokin - Dam.",
                "street": "Dam",
                "city": "Amsterdam",
                "website": "https:\/\/www.homomonument.nl\/nl\/page\/pridewalk",
                "meta": [
                    {
                        "key": "type",
                        "title": "Type",
                        "value": "Demonstratie",
                        "presenter": "text",
                    },
                    {
                        "key": "stad",
                        "title": "Stad",
                        "value": "Amsterdam",
                        "presenter": "text",
                    },
                    {
                        "key": "datum-start",
                        "title": "Datum start",
                        "value": "25-jul",
                        "presenter": "text",
                    },
                    {
                        "key": "datum-eind",
                        "title": "Datum eind",
                        "value": "25-jul",
                        "presenter": "text",
                    },
                    {
                        "key": "tijd",
                        "title": "Tijd",
                        "value": "11:00-14:00",
                        "presenter": "text",
                    },
                    {
                        "key": "url",
                        "title": "URL",
                        "value": '<a href="https:\/\/www.homomonument.nl\/nl\/page\/pridewalk" rel="noopener" target="_blank">https:\/\/www.homomonument.nl\/nl\/page\/pridewalk<\/a>',
                        "presenter": "text",
                    },
                ],
            },
        },
        {
            "type": "Feature",
            "geometry": {"type": "Point", "coordinates": [4.89008527, 52.37112934]},
            "properties": {
                "id": "13073997",
                "title": "Lola's Huis",
                "description": "Theater De Richel, Nieuwezijds Voorburgwal 282 1012 RT Amsterdam",
                "street": "Nieuwezijds Voorburgwal 282",
                "city": "Amsterdam",
                "website": "https:\/\/theaterderichel.nl\/evenementen\/lars-brinkman-lolas-huis\/",
                "meta": [
                    {
                        "key": "type",
                        "title": "Type",
                        "value": "Theather",
                        "presenter": "text",
                    },
                    {
                        "key": "stad",
                        "title": "Stad",
                        "value": "Amsterdam",
                        "presenter": "text",
                    },
                    {
                        "key": "datum-start",
                        "title": "Datum start",
                        "value": "17-jul",
                        "presenter": "text",
                    },
                    {
                        "key": "datum-eind",
                        "title": "Datum eind",
                        "value": "18-jul",
                        "presenter": "text",
                    },
                    {
                        "key": "tijd",
                        "title": "Tijd",
                        "value": "16-07-2026 - 20:30\n17-07-2026 - 20:30\n17-07-2026 - 22:30\n18-07-2026 - 20:30",
                        "presenter": "text",
                    },
                    {
                        "key": "url",
                        "title": "URL",
                        "value": '<a href="https:\/\/theaterderichel.nl\/evenementen\/lars-brinkman-lolas-huis\/" rel="noopener" target="_blank">https:\/\/theaterderichel.nl\/evenementen\/lars-brinkman-lolas-huis\/<\/a>',
                        "presenter": "text",
                    },
                ],
            },
        },
        {
            "type": "Feature",
            "geometry": {"type": "Point", "coordinates": [4.79562632, 52.36949896]},
            "properties": {
                "id": "13074006",
                "title": "Pride Toernooi TV Osdorp",
                "description": "TV Osdorp,  Han Hollanderlaan 1, 1067 BB Amsterdam",
                "street": "Han Hollanderlaan 1",
                "city": "Amsterdam",
                "website": "https:\/\/www.tvosdorp.nl\/worldpride ",
                "meta": [
                    {
                        "key": "type",
                        "title": "Type",
                        "value": "Sport",
                        "presenter": "text",
                    },
                    {
                        "key": "stad",
                        "title": "Stad",
                        "value": "Amsterdam",
                        "presenter": "text",
                    },
                    {
                        "key": "datum-start",
                        "title": "Datum start",
                        "value": "28-jul",
                        "presenter": "text",
                    },
                    {
                        "key": "datum-eind",
                        "title": "Datum eind",
                        "value": "29-jul",
                        "presenter": "text",
                    },
                    {
                        "key": "url",
                        "title": "URL",
                        "value": '<a href="https:\/\/www.tvosdorp.nl\/worldpride" rel="noopener" target="_blank">https:\/\/www.tvosdorp.nl\/worldpride<\/a> ',
                        "presenter": "text",
                    },
                ],
            },
        },
        {
            "type": "Feature",
            "geometry": {"type": "Point", "coordinates": [4.85095012, 52.3704041]},
            "properties": {
                "id": "13074009",
                "title": "Open Air Film Festival",
                "description": "Mercatorplein",
                "street": "Mercatorplein",
                "city": "Amsterdam",
                "website": "http:\/\/Pride Amsterdam",
                "meta": [
                    {
                        "key": "type",
                        "title": "Type",
                        "value": "Openlucht bioscoop",
                        "presenter": "text",
                    },
                    {
                        "key": "stad",
                        "title": "Stad",
                        "value": "Amsterdam",
                        "presenter": "text",
                    },
                    {
                        "key": "datum-start",
                        "title": "Datum start",
                        "value": "30-jul",
                        "presenter": "text",
                    },
                    {
                        "key": "datum-eind",
                        "title": "Datum eind",
                        "value": "30-jul",
                        "presenter": "text",
                    },
                    {
                        "key": "tijd",
                        "title": "Tijd",
                        "value": "20.00-24.00",
                        "presenter": "text",
                    },
                    {
                        "key": "url",
                        "title": "URL",
                        "value": "Pride Amsterdam",
                        "presenter": "text",
                    },
                ],
            },
        },
        {
            "type": "Feature",
            "geometry": {"type": "Point", "coordinates": [4.91978668, 52.36648685]},
            "properties": {
                "id": "13074018",
                "title": "Sport Pride Waterpolo Tournament",
                "city": "Amsterdam",
                "website": "http:\/\/Pride Amsterdam",
                "meta": [
                    {
                        "key": "type",
                        "title": "Type",
                        "value": "Sport",
                        "presenter": "text",
                    },
                    {
                        "key": "stad",
                        "title": "Stad",
                        "value": "Amsterdam",
                        "presenter": "text",
                    },
                    {
                        "key": "datum-start",
                        "title": "Datum start",
                        "value": "31-jul",
                        "presenter": "text",
                    },
                    {
                        "key": "datum-eind",
                        "title": "Datum eind",
                        "value": "31-jul",
                        "presenter": "text",
                    },
                    {
                        "key": "tijd",
                        "title": "Tijd",
                        "value": "10:00-23:00",
                        "presenter": "text",
                    },
                    {
                        "key": "url",
                        "title": "URL",
                        "value": "Pride Amsterdam",
                        "presenter": "text",
                    },
                ],
            },
        },
        {
            "type": "Feature",
            "geometry": {"type": "Point", "coordinates": [4.91978668, 52.36648685]},
            "properties": {
                "id": "13074051",
                "title": "Canal Parade",
                "description": "Oosterdok\/Amstel\/Prinsengracht\/Westerdok",
                "city": "Amsterdam",
                "website": "http:\/\/Pride Amsterdam",
                "meta": [
                    {
                        "key": "type",
                        "title": "Type",
                        "value": "BOTENPARADE",
                        "presenter": "text",
                    },
                    {
                        "key": "stad",
                        "title": "Stad",
                        "value": "Amsterdam",
                        "presenter": "text",
                    },
                    {
                        "key": "datum-start",
                        "title": "Datum start",
                        "value": "1-aug",
                        "presenter": "text",
                    },
                    {
                        "key": "datum-eind",
                        "title": "Datum eind",
                        "value": "1-aug",
                        "presenter": "text",
                    },
                    {
                        "key": "tijd",
                        "title": "Tijd",
                        "value": "12.00-18.00",
                        "presenter": "text",
                    },
                    {
                        "key": "url",
                        "title": "URL",
                        "value": "Pride Amsterdam",
                        "presenter": "text",
                    },
                ],
            },
        },
        {
            "type": "Feature",
            "geometry": {"type": "Point", "coordinates": [4.91978668, 52.36648685]},
            "properties": {
                "id": "13074054",
                "title": "Bars en Food Canal Parade",
                "description": "Langs de rout (Oosterdok\/Amstel\/Prinsengracht\/Westerdok)",
                "city": "Amsterdam",
                "website": "http:\/\/Pride Amsterdam",
                "meta": [
                    {
                        "key": "type",
                        "title": "Type",
                        "value": "Canal Parade",
                        "presenter": "text",
                    },
                    {
                        "key": "stad",
                        "title": "Stad",
                        "value": "Amsterdam",
                        "presenter": "text",
                    },
                    {
                        "key": "datum-start",
                        "title": "Datum start",
                        "value": "1-aug",
                        "presenter": "text",
                    },
                    {
                        "key": "datum-eind",
                        "title": "Datum eind",
                        "value": "1-aug",
                        "presenter": "text",
                    },
                    {
                        "key": "tijd",
                        "title": "Tijd",
                        "value": "11.00-18.00",
                        "presenter": "text",
                    },
                    {
                        "key": "url",
                        "title": "URL",
                        "value": "Pride Amsterdam",
                        "presenter": "text",
                    },
                ],
            },
        },
        {
            "type": "Feature",
            "geometry": {"type": "Point", "coordinates": [4.90648875, 52.33846375]},
            "properties": {
                "id": "13074114",
                "title": "WorldPride March",
                "description": "MLKingpark-Pr. Kennedylaan, Rijnstraat, Van Woustraat, Ceintuurbaan, Roelof Hartstraat, van Baerlestraat, Museumplein",
                "street": "Amsteldijk 223",
                "city": "Amsterdam",
                "website": "http:\/\/Pride Amsterdam",
                "meta": [
                    {
                        "key": "type",
                        "title": "Type",
                        "value": "Evenement",
                        "presenter": "text",
                    },
                    {
                        "key": "stad",
                        "title": "Stad",
                        "value": "Amsterdam",
                        "presenter": "text",
                    },
                    {
                        "key": "datum-start",
                        "title": "Datum start",
                        "value": "8-aug",
                        "presenter": "text",
                    },
                    {
                        "key": "datum-eind",
                        "title": "Datum eind",
                        "value": "8-aug",
                        "presenter": "text",
                    },
                    {
                        "key": "tijd",
                        "title": "Tijd",
                        "value": "15.00-20.00",
                        "presenter": "text",
                    },
                    {
                        "key": "url",
                        "title": "URL",
                        "value": "Pride Amsterdam",
                        "presenter": "text",
                    },
                ],
            },
        },
        {
            "type": "Feature",
            "geometry": {"type": "Point", "coordinates": [4.86258347, 52.37474957]},
            "properties": {
                "id": "13074117",
                "title": "Meneer Howard & Co Pride 2026",
                "description": "Stichting Meneer Howard & Co de Buurtkamer Willem de Zwijgerlaan 153, 1056 JL Amsterdam",
                "street": "Willem de Zwijgerlaan 153",
                "city": "Amsterdam",
                "meta": [
                    {
                        "key": "type",
                        "title": "Type",
                        "value": "Evenement",
                        "presenter": "text",
                    },
                    {
                        "key": "stad",
                        "title": "Stad",
                        "value": "Amsterdam",
                        "presenter": "text",
                    },
                ],
            },
        },
    ],
}
