MOCK_DATA = {
    "type": "FeatureCollection",
    "features": [
        {
            "type": "Feature",
            "geometry": {"type": "Point", "coordinates": [4.88276008, 52.3573507]},
            "properties": {
                "id": "13073916",
                "title": "Zero Flags Project",
                "description": "Museumplein",
                "street": "Museumplein",
                "city": "Amsterdam",
                "website": "https:\/\/www.zeroflagsproject.nl\/",
                "meta": [
                    {
                        "key": "type",
                        "title": "Type",
                        "value": "Tentoonstelling",
                        "presenter": "text",
                    },
                    {
                        "key": "stad",
                        "title": "Stad",
                        "value": "Amsterdam",
                        "presenter": "text",
                    },
                    {
                        "key": "datum-start",
                        "title": "Datum start",
                        "value": "2026-07-08",
                        "presenter": "text",
                    },
                    {
                        "key": "datum-eind",
                        "title": "Datum eind",
                        "value": "2026-07-29",
                        "presenter": "text",
                    },
                    {
                        "key": "tijd",
                        "title": "Tijd",
                        "value": "doorlopend",
                        "presenter": "text",
                    },
                    {
                        "key": "url",
                        "title": "URL",
                        "value": '<a href="https:\/\/www.zeroflagsproject.nl\/" rel="noopener" target="_blank">https:\/\/www.zeroflagsproject.nl\/<\/a>',
                        "presenter": "text",
                    },
                ],
            },
        },
        {
            "type": "Feature",
            "geometry": {"type": "Point", "coordinates": [4.89187769, 52.37367138]},
            "properties": {
                "id": "13073919",
                "title": "Queer Amsterdam",
                "description": "De Nieuwe Kerk,  Dam 12 msterdam",
                "street": "Dam 12",
                "city": "Amsterdam",
                "website": "https:\/\/www.nieuwekerk.nl\/pers\/persberichten\/queer-amsterdam-in-de-nieuwe-kerk\/",
                "meta": [
                    {
                        "key": "type",
                        "title": "Type",
                        "value": "Tentoonstelling",
                        "presenter": "text",
                    },
                    {
                        "key": "stad",
                        "title": "Stad",
                        "value": "Amsterdam",
                        "presenter": "text",
                    },
                    {
                        "key": "datum-start",
                        "title": "Datum start",
                        "value": "2026-07-09",
                        "presenter": "text",
                    },
                    {
                        "key": "datum-eind",
                        "title": "Datum eind",
                        "value": "2027-04-04",
                        "presenter": "text",
                    },
                    {
                        "key": "tijd",
                        "title": "Tijd",
                        "value": "doorlopend",
                        "presenter": "text",
                    },
                    {
                        "key": "url",
                        "title": "URL",
                        "value": '<a href="https:\/\/www.nieuwekerk.nl\/pers\/persberichten\/queer-amsterdam-in-de-nieuwe-kerk\/" rel="noopener" target="_blank">https:\/\/www.nieuwekerk.nl\/pers\/persberichten\/queer-amsterdam-in-de-nieuwe-kerk\/<\/a>',
                        "presenter": "text",
                    },
                ],
            },
        },
        {
            "type": "Feature",
            "geometry": {"type": "Point", "coordinates": [4.91978668, 52.36648685]},
            "properties": {
                "id": "13073922",
                "title": "Tour d'Amour bij Cordaan",
                "description": "Diverse locaties van Cordaan",
                "city": "Amsterdam",
                "meta": [
                    {
                        "key": "type",
                        "title": "Type",
                        "value": "Evenement",
                        "presenter": "text",
                    },
                    {
                        "key": "stad",
                        "title": "Stad",
                        "value": "Amsterdam",
                        "presenter": "text",
                    },
                    {
                        "key": "datum-start",
                        "title": "Datum start",
                        "value": "2026-07-08",
                        "presenter": "text",
                    },
                    {
                        "key": "datum-eind",
                        "title": "Datum eind",
                        "value": "2026-07-29",
                        "presenter": "text",
                    },
                ],
            },
        },
        {
            "type": "Feature",
            "geometry": {"type": "Point", "coordinates": [4.89410619, 52.37291108]},
            "properties": {
                "id": "13073925",
                "title": "Pride Art Route 2026 (de datum op de website is ander)",
                "description": "Dam",
                "street": "Dam",
                "city": "Amsterdam",
                "website": "https:\/\/pride.amsterdam\/en\/event\/pride-art-route-2\/",
                "meta": [
                    {
                        "key": "type",
                        "title": "Type",
                        "value": "Evenement &Tentoonstelling",
                        "presenter": "text",
                    },
                    {
                        "key": "stad",
                        "title": "Stad",
                        "value": "Amsterdam",
                        "presenter": "text",
                    },
                    {
                        "key": "datum-start",
                        "title": "Datum start",
                        "value": "2026-07-04",
                        "presenter": "text",
                    },
                    {
                        "key": "datum-eind",
                        "title": "Datum eind",
                        "value": "2026-08-09",
                        "presenter": "text",
                    },
                    {
                        "key": "url",
                        "title": "URL",
                        "value": '<a href="https:\/\/pride.amsterdam\/en\/event\/pride-art-route-2\/" rel="noopener" target="_blank">https:\/\/pride.amsterdam\/en\/event\/pride-art-route-2\/<\/a>',
                        "presenter": "text",
                    },
                ],
            },
        },
        {
            "type": "Feature",
            "geometry": {"type": "Point", "coordinates": [4.89410619, 52.37291108]},
            "properties": {
                "id": "13073928",
                "title": "Trans Pride",
                "description": "Dam",
                "street": "Dam",
                "city": "Amsterdam",
                "meta": [
                    {
                        "key": "type",
                        "title": "Type",
                        "value": "Tentoonstelling",
                        "presenter": "text",
                    },
                    {
                        "key": "stad",
                        "title": "Stad",
                        "value": "Amsterdam",
                        "presenter": "text",
                    },
                    {
                        "key": "datum-start",
                        "title": "Datum start",
                        "value": "2026-07-08",
                        "presenter": "text",
                    },
                    {
                        "key": "datum-eind",
                        "title": "Datum eind",
                        "value": "2026-07-29",
                        "presenter": "text",
                    },
                ],
            },
        },
        {
            "type": "Feature",
            "geometry": {"type": "Point", "coordinates": [4.85413421, 52.3800775]},
            "properties": {
                "id": "13073931",
                "title": "Pride 2026 in Podium Moza\u00efek",
                "description": "Podium Moza\u00efek, Bos en Lommerweg 191, 1055 DT Amsterdamv",
                "street": "Bos en Lommerweg 191",
                "city": "Amsterdam",
                "meta": [
                    {
                        "key": "type",
                        "title": "Type",
                        "value": "Theather",
                        "presenter": "text",
                    },
                    {
                        "key": "stad",
                        "title": "Stad",
                        "value": "Amsterdam",
                        "presenter": "text",
                    },
                    {
                        "key": "datum-start",
                        "title": "Datum start",
                        "value": "2026-07-08",
                        "presenter": "text",
                    },
                    {
                        "key": "datum-eind",
                        "title": "Datum eind",
                        "value": "2026-07-29",
                        "presenter": "text",
                    },
                ],
            },
        },
        {
            "type": "Feature",
            "geometry": {"type": "Point", "coordinates": [4.89410619, 52.37291108]},
            "properties": {
                "id": "13073934",
                "title": "Roze Vlinders 2026",
                "description": "Dam",
                "street": "Dam",
                "city": "Amsterdam",
                "meta": [
                    {
                        "key": "type",
                        "title": "Type",
                        "value": "Concert",
                        "presenter": "text",
                    },
                    {
                        "key": "stad",
                        "title": "Stad",
                        "value": "Amsterdam",
                        "presenter": "text",
                    },
                    {
                        "key": "datum-start",
                        "title": "Datum start",
                        "value": "2026-07-08",
                        "presenter": "text",
                    },
                    {
                        "key": "datum-eind",
                        "title": "Datum eind",
                        "value": "2026-07-29",
                        "presenter": "text",
                    },
                ],
            },
        },
        {
            "type": "Feature",
            "geometry": {"type": "Point", "coordinates": [4.88048941, 52.36405127]},
            "properties": {
                "id": "13073937",
                "title": "Poeziefestival: Queer Joy",
                "description": "Theater Bellevue leidsekade 90 1017 PN amsterdam",
                "street": "Theater Bellevue leidsekade 90",
                "city": "Amsterdam",
                "meta": [
                    {
                        "key": "type",
                        "title": "Type",
                        "value": "Spoken Word- Po\u00ebzie",
                        "presenter": "text",
                    },
                    {
                        "key": "stad",
                        "title": "Stad",
                        "value": "Amsterdam",
                        "presenter": "text",
                    },
                    {
                        "key": "datum-start",
                        "title": "Datum start",
                        "value": "2026-07-08",
                        "presenter": "text",
                    },
                    {
                        "key": "datum-eind",
                        "title": "Datum eind",
                        "value": "2026-07-29",
                        "presenter": "text",
                    },
                ],
            },
        },
        {
            "type": "Feature",
            "geometry": {"type": "Point", "coordinates": [4.91978668, 52.36648685]},
            "properties": {
                "id": "13073940",
                "title": "Smakelijke Verhalen",
                "description": "Diverse Hotels & Restaurant in Noord",
                "city": "Amsterdam",
                "meta": [
                    {
                        "key": "type",
                        "title": "Type",
                        "value": "Evenement",
                        "presenter": "text",
                    },
                    {
                        "key": "stad",
                        "title": "Stad",
                        "value": "Amsterdam",
                        "presenter": "text",
                    },
                    {
                        "key": "datum-start",
                        "title": "Datum start",
                        "value": "2026-07-08",
                        "presenter": "text",
                    },
                    {
                        "key": "datum-eind",
                        "title": "Datum eind",
                        "value": "2026-07-29",
                        "presenter": "text",
                    },
                ],
            },
        },
        {
            "type": "Feature",
            "geometry": {"type": "Point", "coordinates": [4.91978668, 52.36648685]},
            "properties": {
                "id": "13073943",
                "title": "NightGuides Community Gatherings",
                "description": "Diverse locaties",
                "city": "Amsterdam",
                "meta": [
                    {
                        "key": "type",
                        "title": "Type",
                        "value": "Evenement",
                        "presenter": "text",
                    },
                    {
                        "key": "stad",
                        "title": "Stad",
                        "value": "Amsterdam",
                        "presenter": "text",
                    },
                    {
                        "key": "datum-start",
                        "title": "Datum start",
                        "value": "2026-07-08",
                        "presenter": "text",
                    },
                    {
                        "key": "datum-eind",
                        "title": "Datum eind",
                        "value": "2026-07-29",
                        "presenter": "text",
                    },
                ],
            },
        },
        {
            "type": "Feature",
            "geometry": {"type": "Point", "coordinates": [4.95109673, 52.31433666]},
            "properties": {
                "id": "13073946",
                "title": "House of Visibility- The Art of Legacy",
                "description": "OSCAM, Bijlmerplein 97, 1102 DA Amsterdam",
                "street": "Bijlmerplein 97",
                "city": "Amsterdam",
                "meta": [
                    {
                        "key": "type",
                        "title": "Type",
                        "value": "Evenement &Tentoonstelling",
                        "presenter": "text",
                    },
                    {
                        "key": "stad",
                        "title": "Stad",
                        "value": "Amsterdam",
                        "presenter": "text",
                    },
                    {
                        "key": "datum-start",
                        "title": "Datum start",
                        "value": "2026-07-09",
                        "presenter": "text",
                    },
                    {
                        "key": "datum-eind",
                        "title": "Datum eind",
                        "value": "2026-07-27",
                        "presenter": "text",
                    },
                ],
            },
        },
        {
            "type": "Feature",
            "geometry": {"type": "Point", "coordinates": [4.96030373, 52.31465483]},
            "properties": {
                "id": "13073949",
                "title": "House of Visibility- The Art of Legacy",
                "description": "Bijlmer Parktheater Anton de Komplein 240, 1102 DR Amsterdam",
                "street": "Anton de Komplein 240",
                "city": "Amsterdam",
                "meta": [
                    {
                        "key": "type",
                        "title": "Type",
                        "value": "Evenement &Tentoonstelling",
                        "presenter": "text",
                    },
                    {
                        "key": "stad",
                        "title": "Stad",
                        "value": "Amsterdam",
                        "presenter": "text",
                    },
                    {
                        "key": "datum-start",
                        "title": "Datum start",
                        "value": "2026-07-09",
                        "presenter": "text",
                    },
                    {
                        "key": "datum-eind",
                        "title": "Datum eind",
                        "value": "2026-07-27",
                        "presenter": "text",
                    },
                ],
            },
        },
        {
            "type": "Feature",
            "geometry": {"type": "Point", "coordinates": [4.81607649, 52.35984657]},
            "properties": {
                "id": "13073952",
                "title": "Sport Pride Amsterdam 2026- Move with Pride Unity in Motion",
                "street": "Christoffel Plantijngracht 4",
                "city": "Amsterdam",
                "meta": [
                    {
                        "key": "type",
                        "title": "Type",
                        "value": "Sport",
                        "presenter": "text",
                    },
                    {
                        "key": "stad",
                        "title": "Stad",
                        "value": "Amsterdam",
                        "presenter": "text",
                    },
                    {
                        "key": "datum-start",
                        "title": "Datum start",
                        "value": "2026-07-09",
                        "presenter": "text",
                    },
                    {
                        "key": "datum-eind",
                        "title": "Datum eind",
                        "value": "2026-07-29",
                        "presenter": "text",
                    },
                ],
            },
        },
        {
            "type": "Feature",
            "geometry": {"type": "Point", "coordinates": [4.91978668, 52.36648685]},
            "properties": {
                "id": "13073955",
                "title": "Van Stadsdeel tot Wereldtoneel Women @ WorldPride",
                "city": "Amsterdam",
                "meta": [
                    {
                        "key": "type",
                        "title": "Type",
                        "value": "Evenement",
                        "presenter": "text",
                    },
                    {
                        "key": "stad",
                        "title": "Stad",
                        "value": "Amsterdam",
                        "presenter": "text",
                    },
                    {
                        "key": "datum-start",
                        "title": "Datum start",
                        "value": "2026-07-10",
                        "presenter": "text",
                    },
                    {
                        "key": "datum-eind",
                        "title": "Datum eind",
                        "value": "2026-07-29",
                        "presenter": "text",
                    },
                ],
            },
        },
        {
            "type": "Feature",
            "geometry": {"type": "Point", "coordinates": [4.89386371, 52.37114857]},
            "properties": {
                "id": "13073958",
                "title": "Queer Trans Seks Workers Pride",
                "description": "Nes 45, Amsterdam",
                "street": "Nes 45",
                "city": "Amsterdam",
                "meta": [
                    {
                        "key": "type",
                        "title": "Type",
                        "value": "Evenement",
                        "presenter": "text",
                    },
                    {
                        "key": "stad",
                        "title": "Stad",
                        "value": "Amsterdam",
                        "presenter": "text",
                    },
                    {
                        "key": "datum-start",
                        "title": "Datum start",
                        "value": "2026-07-11",
                        "presenter": "text",
                    },
                    {
                        "key": "datum-eind",
                        "title": "Datum eind",
                        "value": "2026-07-11",
                        "presenter": "text",
                    },
                ],
            },
        },
        {
            "type": "Feature",
            "geometry": {"type": "Point", "coordinates": [4.95560836, 52.31601511]},
            "properties": {
                "id": "13073961",
                "title": "Colourful Pride Stage Zuidoost",
                "description": "Anton de Komplein ( tijdens Kwaku)",
                "street": "Anton de Komplein ",
                "city": "Amsterdam",
                "meta": [
                    {
                        "key": "type",
                        "title": "Type",
                        "value": "Evenement",
                        "presenter": "text",
                    },
                    {
                        "key": "stad",
                        "title": "Stad",
                        "value": "Amsterdam",
                        "presenter": "text",
                    },
                    {
                        "key": "datum-start",
                        "title": "Datum start",
                        "value": "2026-07-11",
                        "presenter": "text",
                    },
                    {
                        "key": "datum-eind",
                        "title": "Datum eind",
                        "value": "2026-07-11",
                        "presenter": "text",
                    },
                ],
            },
        },
        {
            "type": "Feature",
            "geometry": {"type": "Point", "coordinates": [4.91978668, 52.36648685]},
            "properties": {
                "id": "13073964",
                "title": "Queer Market Amsterdam",
                "description": "Def. Locatie volgt",
                "city": "Amsterdam",
                "website": "https:\/\/www.queermarket.nl",
                "meta": [
                    {
                        "key": "type",
                        "title": "Type",
                        "value": "Evenement",
                        "presenter": "text",
                    },
                    {
                        "key": "stad",
                        "title": "Stad",
                        "value": "Amsterdam",
                        "presenter": "text",
                    },
                    {
                        "key": "datum-start",
                        "title": "Datum start",
                        "value": "2026-07-12",
                        "presenter": "text",
                    },
                    {
                        "key": "datum-eind",
                        "title": "Datum eind",
                        "value": "2026-07-12",
                        "presenter": "text",
                    },
                    {
                        "key": "tijd",
                        "title": "Tijd",
                        "value": "12.00-19.00",
                        "presenter": "text",
                    },
                    {
                        "key": "url",
                        "title": "URL",
                        "value": '<a href="https:\/\/www.queermarket.nl" rel="noopener" target="_blank">https:\/\/www.queermarket.nl<\/a>',
                        "presenter": "text",
                    },
                ],
            },
        },
        {
            "type": "Feature",
            "geometry": {"type": "Point", "coordinates": [4.88111723, 52.38623563]},
            "properties": {
                "id": "13073967",
                "title": "Pride and Sports- Queer Sport Social",
                "description": "Westerpark",
                "street": "Westerpark",
                "city": "Amsterdam",
                "meta": [
                    {
                        "key": "type",
                        "title": "Type",
                        "value": "Sport",
                        "presenter": "text",
                    },
                    {
                        "key": "stad",
                        "title": "Stad",
                        "value": "Amsterdam",
                        "presenter": "text",
                    },
                    {
                        "key": "datum-start",
                        "title": "Datum start",
                        "value": "2026-07-12",
                        "presenter": "text",
                    },
                    {
                        "key": "datum-eind",
                        "title": "Datum eind",
                        "value": "2026-07-12",
                        "presenter": "text",
                    },
                ],
            },
        },
        {
            "type": "Feature",
            "geometry": {"type": "Point", "coordinates": [4.88437426, 52.37385561]},
            "properties": {
                "id": "13073970",
                "title": "Drag Olympics",
                "description": "Homomonument, Westermarkt, Keizersgracht",
                "street": "Homomonument, Westermarkt, Keizersgracht",
                "city": "Amsterdam",
                "website": "https:\/\/www.homomonument.nl\/nl\/event ",
                "meta": [
                    {
                        "key": "type",
                        "title": "Type",
                        "value": "Sport",
                        "presenter": "text",
                    },
                    {
                        "key": "stad",
                        "title": "Stad",
                        "value": "Amsterdam",
                        "presenter": "text",
                    },
                    {
                        "key": "datum-start",
                        "title": "Datum start",
                        "value": "2026-07-31",
                        "presenter": "text",
                    },
                    {
                        "key": "datum-eind",
                        "title": "Datum eind",
                        "value": "2026-07-31",
                        "presenter": "text",
                    },
                    {
                        "key": "tijd",
                        "title": "Tijd",
                        "value": "from 19:00",
                        "presenter": "text",
                    },
                    {
                        "key": "url",
                        "title": "URL",
                        "value": '<a href="https:\/\/www.homomonument.nl\/nl\/event" rel="noopener" target="_blank">https:\/\/www.homomonument.nl\/nl\/event<\/a> ',
                        "presenter": "text",
                    },
                ],
            },
        },
        {
            "type": "Feature",
            "geometry": {"type": "Point", "coordinates": [4.88437426, 52.37385561]},
            "properties": {
                "id": "13073973",
                "title": "Danspaleis Homomonument",
                "description": "Homomonument, Westermarkt, Keizersgracht",
                "street": "Homomonument, Westermarkt, Keizersgracht",
                "city": "Amsterdam",
                "website": "https:\/\/www.homomonument.nl\/nl\/event ",
                "meta": [
                    {
                        "key": "type",
                        "title": "Type",
                        "value": "Evenement",
                        "presenter": "text",
                    },
                    {
                        "key": "stad",
                        "title": "Stad",
                        "value": "Amsterdam",
                        "presenter": "text",
                    },
                    {
                        "key": "datum-start",
                        "title": "Datum start",
                        "value": "2026-07-19",
                        "presenter": "text",
                    },
                    {
                        "key": "datum-eind",
                        "title": "Datum eind",
                        "value": "2026-07-19",
                        "presenter": "text",
                    },
                    {
                        "key": "tijd",
                        "title": "Tijd",
                        "value": "16.00-18.00",
                        "presenter": "text",
                    },
                    {
                        "key": "url",
                        "title": "URL",
                        "value": '<a href="https:\/\/www.homomonument.nl\/nl\/event" rel="noopener" target="_blank">https:\/\/www.homomonument.nl\/nl\/event<\/a> ',
                        "presenter": "text",
                    },
                ],
            },
        },
        {
            "type": "Feature",
            "geometry": {"type": "Point", "coordinates": [4.88437426, 52.37385561]},
            "properties": {
                "id": "13073976",
                "title": "Sexyland",
                "description": "Homomonument, Westermarkt, Keizersgracht",
                "street": "Homomonument, Westermarkt, Keizersgracht",
                "city": "Amsterdam",
                "website": "https:\/\/www.homomonument.nl\/nl\/event ",
                "meta": [
                    {
                        "key": "type",
                        "title": "Type",
                        "value": "Evenement",
                        "presenter": "text",
                    },
                    {
                        "key": "stad",
                        "title": "Stad",
                        "value": "Amsterdam",
                        "presenter": "text",
                    },
                    {
                        "key": "datum-start",
                        "title": "Datum start",
                        "value": "2026-08-01",
                        "presenter": "text",
                    },
                    {
                        "key": "datum-eind",
                        "title": "Datum eind",
                        "value": "2026-08-01",
                        "presenter": "text",
                    },
                    {
                        "key": "tijd",
                        "title": "Tijd",
                        "value": "18.00 - 00.00",
                        "presenter": "text",
                    },
                    {
                        "key": "url",
                        "title": "URL",
                        "value": '<a href="https:\/\/www.homomonument.nl\/nl\/event" rel="noopener" target="_blank">https:\/\/www.homomonument.nl\/nl\/event<\/a> ',
                        "presenter": "text",
                    },
                ],
            },
        },
        {
            "type": "Feature",
            "geometry": {"type": "Point", "coordinates": [4.95263878, 52.35463137]},
            "properties": {
                "id": "13073979",
                "title": "Pride Run 2026 (hardlopers en wandelaars)",
                "description": "Amsterdam Oost: start en finish van de Pride Run bij Caf\u00e9 Restaurant Polder, route door Flevopark; baannummers van de atletiekwedstrijd bij AV` 23 aan de Radioweg. ",
                "street": "Science Park 201",
                "city": "Amsterdam",
                "website": "https:\/\/www.rainbowathletics.amsterdam\/",
                "meta": [
                    {
                        "key": "type",
                        "title": "Type",
                        "value": "Sport",
                        "presenter": "text",
                    },
                    {
                        "key": "stad",
                        "title": "Stad",
                        "value": "Amsterdam",
                        "presenter": "text",
                    },
                    {
                        "key": "datum-start",
                        "title": "Datum start",
                        "value": "2026-07-19",
                        "presenter": "text",
                    },
                    {
                        "key": "datum-eind",
                        "title": "Datum eind",
                        "value": "2026-07-20",
                        "presenter": "text",
                    },
                    {
                        "key": "tijd",
                        "title": "Tijd",
                        "value": "Variabel per afstand",
                        "presenter": "text",
                    },
                    {
                        "key": "url",
                        "title": "URL",
                        "value": '<a href="https:\/\/www.rainbowathletics.amsterdam\/" rel="noopener" target="_blank">https:\/\/www.rainbowathletics.amsterdam\/<\/a>',
                        "presenter": "text",
                    },
                ],
            },
        },
        {
            "type": "Feature",
            "geometry": {"type": "Point", "coordinates": [4.88437426, 52.37385561]},
            "properties": {
                "id": "13073982",
                "title": "Queer Families",
                "description": "Homomonument, Westermarkt, Keizersgracht",
                "street": "Homomonument, Westermarkt, Keizersgracht",
                "city": "Amsterdam",
                "website": "https:\/\/www.homomonument.nl\/nl\/event ",
                "meta": [
                    {
                        "key": "type",
                        "title": "Type",
                        "value": "Evenement",
                        "presenter": "text",
                    },
                    {
                        "key": "stad",
                        "title": "Stad",
                        "value": "Amsterdam",
                        "presenter": "text",
                    },
                    {
                        "key": "datum-start",
                        "title": "Datum start",
                        "value": "2026-08-02",
                        "presenter": "text",
                    },
                    {
                        "key": "datum-eind",
                        "title": "Datum eind",
                        "value": "2026-08-02",
                        "presenter": "text",
                    },
                    {
                        "key": "tijd",
                        "title": "Tijd",
                        "value": "14.00-17.00",
                        "presenter": "text",
                    },
                    {
                        "key": "url",
                        "title": "URL",
                        "value": '<a href="https:\/\/www.homomonument.nl\/nl\/event" rel="noopener" target="_blank">https:\/\/www.homomonument.nl\/nl\/event<\/a> ',
                        "presenter": "text",
                    },
                ],
            },
        },
        {
            "type": "Feature",
            "geometry": {"type": "Point", "coordinates": [4.91978668, 52.36648685]},
            "properties": {
                "id": "13073985",
                "title": "Pride Spectacle at the Eye",
                "description": "Locatie volgt",
                "street": "Locatie volgt",
                "city": "Amsterdam",
                "meta": [
                    {
                        "key": "type",
                        "title": "Type",
                        "value": "Evenement",
                        "presenter": "text",
                    },
                    {
                        "key": "stad",
                        "title": "Stad",
                        "value": "Amsterdam",
                        "presenter": "text",
                    },
                    {
                        "key": "datum-start",
                        "title": "Datum start",
                        "value": "2026-07-20",
                        "presenter": "text",
                    },
                    {
                        "key": "datum-eind",
                        "title": "Datum eind",
                        "value": "2026-07-21",
                        "presenter": "text",
                    },
                ],
            },
        },
        {
            "type": "Feature",
            "geometry": {"type": "Point", "coordinates": [4.91299387, 52.34833311]},
            "properties": {
                "id": "13073988",
                "title": "Love Swim 2026",
                "description": "Amstel t.h.v. Berlagebrug",
                "street": "Weesperzijde 1094",
                "city": "Amsterdam",
                "meta": [
                    {
                        "key": "type",
                        "title": "Type",
                        "value": "Sport",
                        "presenter": "text",
                    },
                    {
                        "key": "stad",
                        "title": "Stad",
                        "value": "Amsterdam",
                        "presenter": "text",
                    },
                    {
                        "key": "datum-start",
                        "title": "Datum start",
                        "value": "2026-07-24",
                        "presenter": "text",
                    },
                    {
                        "key": "datum-eind",
                        "title": "Datum eind",
                        "value": "2026-07-24",
                        "presenter": "text",
                    },
                ],
            },
        },
        {
            "type": "Feature",
            "geometry": {"type": "Point", "coordinates": [4.89410619, 52.37291108]},
            "properties": {
                "id": "13073991",
                "title": "Pride Walk",
                "description": "De route loopt vanaf de Dam - Rokin - Munt - Vijzelstraat - Weteringschans - Frederiksplein - Utrechtstestraat -Rembrandtplein - Munt - Rokin - Dam.",
                "street": "Dam",
                "city": "Amsterdam",
                "website": "https:\/\/www.homomonument.nl\/nl\/page\/pridewalk",
                "meta": [
                    {
                        "key": "type",
                        "title": "Type",
                        "value": "Demonstratie",
                        "presenter": "text",
                    },
                    {
                        "key": "stad",
                        "title": "Stad",
                        "value": "Amsterdam",
                        "presenter": "text",
                    },
                    {
                        "key": "datum-start",
                        "title": "Datum start",
                        "value": "2026-07-25",
                        "presenter": "text",
                    },
                    {
                        "key": "datum-eind",
                        "title": "Datum eind",
                        "value": "2026-07-25",
                        "presenter": "text",
                    },
                    {
                        "key": "tijd",
                        "title": "Tijd",
                        "value": "11:00-14:00",
                        "presenter": "text",
                    },
                    {
                        "key": "url",
                        "title": "URL",
                        "value": '<a href="https:\/\/www.homomonument.nl\/nl\/page\/pridewalk" rel="noopener" target="_blank">https:\/\/www.homomonument.nl\/nl\/page\/pridewalk<\/a>',
                        "presenter": "text",
                    },
                ],
            },
        },
        {
            "type": "Feature",
            "geometry": {"type": "Point", "coordinates": [4.87063792, 52.35835998]},
            "properties": {
                "id": "13073994",
                "title": "Pride Park",
                "description": "Vondelpark Openlucht Theater",
                "street": "Vondelpark 5a, 1071 AA Amsterdam",
                "city": "Amsterdam",
                "website": "https:\/\/pride.amsterdam\/",
                "meta": [
                    {
                        "key": "type",
                        "title": "Type",
                        "value": "Evenement",
                        "presenter": "text",
                    },
                    {
                        "key": "stad",
                        "title": "Stad",
                        "value": "Amsterdam",
                        "presenter": "text",
                    },
                    {
                        "key": "datum-start",
                        "title": "Datum start",
                        "value": "2026-07-25",
                        "presenter": "text",
                    },
                    {
                        "key": "datum-eind",
                        "title": "Datum eind",
                        "value": "2026-07-25",
                        "presenter": "text",
                    },
                    {
                        "key": "tijd",
                        "title": "Tijd",
                        "value": "12.00-22.00",
                        "presenter": "text",
                    },
                    {
                        "key": "url",
                        "title": "URL",
                        "value": '<a href="https:\/\/pride.amsterdam\/" rel="noopener" target="_blank">https:\/\/pride.amsterdam\/<\/a>',
                        "presenter": "text",
                    },
                ],
            },
        },
        {
            "type": "Feature",
            "geometry": {"type": "Point", "coordinates": [4.89008527, 52.37112934]},
            "properties": {
                "id": "13073997",
                "title": "Lola's Huis",
                "description": "Theater De Richel, Nieuwezijds Voorburgwal 282 1012 RT Amsterdam",
                "street": "Nieuwezijds Voorburgwal 282",
                "city": "Amsterdam",
                "website": "https:\/\/theaterderichel.nl\/evenementen\/lars-brinkman-lolas-huis\/",
                "meta": [
                    {
                        "key": "type",
                        "title": "Type",
                        "value": "Theather",
                        "presenter": "text",
                    },
                    {
                        "key": "stad",
                        "title": "Stad",
                        "value": "Amsterdam",
                        "presenter": "text",
                    },
                    {
                        "key": "datum-start",
                        "title": "Datum start",
                        "value": "2026-07-17",
                        "presenter": "text",
                    },
                    {
                        "key": "datum-eind",
                        "title": "Datum eind",
                        "value": "2026-07-18",
                        "presenter": "text",
                    },
                    {
                        "key": "tijd",
                        "title": "Tijd",
                        "value": "16-07-2026 - 20:30\n17-07-2026 - 20:30\n17-07-2026 - 22:30\n18-07-2026 - 20:30",
                        "presenter": "text",
                    },
                    {
                        "key": "url",
                        "title": "URL",
                        "value": '<a href="https:\/\/theaterderichel.nl\/evenementen\/lars-brinkman-lolas-huis\/" rel="noopener" target="_blank">https:\/\/theaterderichel.nl\/evenementen\/lars-brinkman-lolas-huis\/<\/a>',
                        "presenter": "text",
                    },
                ],
            },
        },
    ],
}
