MOCK_MAMS_RESPONSE = {
    "AFIS": {
        "content": {
            "isKnown": True,
            "businessPartnerIdEncrypted": "oEDLgvm3qbMiRRykkw5fxcILSfrv6QmKfJxKsJFHgzKuye257YVS0ZXsPBZLZp6UymNcoqJ0tA2dJeLdssP82tPwRndgm2DEaavbIW8FP-OqIg7Yk-gCHmYp9Gl25JQ-YqioStIUvc9UjoDZn-HDzg",
            "facturen": {
                "open": {
                    "count": 69,
                    "state": "open",
                    "facturen": [
                        {
                            "id": "2600123120-2600123120-2026-05-07t000000",
                            "afzender": "SDN Begraafplaats DN",
                            "datePublished": "2026-05-07T00:00:00",
                            "datePublishedFormatted": "07 mei 2026",
                            "paymentDueDate": "2026-05-07T00:00:00",
                            "paymentDueDateFormatted": "07 mei 2026",
                            "debtClearingDate": None,
                            "debtClearingDateFormatted": None,
                            "amountPayed": "0.01",
                            "amountPayedFormatted": "€ 0,01",
                            "amountOriginal": "0.01",
                            "amountOriginalFormatted": "€ 0,01",
                            "factuurNummer": "2600123120",
                            "factuurDocumentId": "2600123120",
                            "status": "openstaand",
                            "statusDescription": "€ 0,01 betaal nu",
                            "paylink": "https://betalingen.amsterdam.nl/pay/1863664052/bca84743e6c11e9943390265f6e00f634a23ce2f",
                            "eMandateId": "",
                            "documentDownloadLink": "https://test.mijn.amsterdam.nl/api/v1/services/afis/facturen/document?id=fBlxgVnnl91YWAyrXJZy7CIEyjT8MAtCOVK7Oh8pVGpMaQFG1rKof_8UAzKgtAO8RQZ-3AXRC9OsUrFeTfWd8A",
                            "link": {
                                "to": "/facturen-en-betalen/factuur/open/2600123120",
                                "title": "Factuur 2600123120",
                            },
                        },
                        {
                            "id": "2600123139-2600123139-2026-05-07t000000",
                            "afzender": "WP Sociaal Werk",
                            "datePublished": "2026-05-07T00:00:00",
                            "datePublishedFormatted": "07 mei 2026",
                            "paymentDueDate": "2026-05-07T00:00:00",
                            "paymentDueDateFormatted": "07 mei 2026",
                            "debtClearingDate": None,
                            "debtClearingDateFormatted": None,
                            "amountPayed": "0.01",
                            "amountPayedFormatted": "€ 0,01",
                            "amountOriginal": "0.01",
                            "amountOriginalFormatted": "€ 0,01",
                            "factuurNummer": "2600123139",
                            "factuurDocumentId": "2600123139",
                            "status": "factuur-in-termijnen",
                            "statusDescription": "€ 0,01 wordt automatisch van uw rekening afgeschreven. <br><strong>Let op! deze incassomachtiging is gestopt.</strong>",
                            "paylink": None,
                            "eMandateId": "100000000996",
                            "documentDownloadLink": "https://test.mijn.amsterdam.nl/api/v1/services/afis/facturen/document?id=R_pW9jnz-tFBbEX8BGN1FvLjqtEnXdypzmZw06SPIpvk3Ir34lQZDJy1XNCDu37EjHNGee3a309Pm2b1tdR5pg",
                            "link": {
                                "to": "/facturen-en-betalen/factuur/open/2600123139",
                                "title": "Factuur 2600123139",
                            },
                        },
                    ],
                },
                "afgehandeld": {
                    "count": 1,
                    "state": "afgehandeld",
                    "facturen": [
                        {
                            "id": "2600013164-2600013164-2026-01-01t000000",
                            "afzender": "GO Erfpacht en Uitgi",
                            "datePublished": "2025-11-26T00:00:00",
                            "datePublishedFormatted": "26 november 2025",
                            "paymentDueDate": "2026-01-01T00:00:00",
                            "paymentDueDateFormatted": "01 januari 2026",
                            "debtClearingDate": "2026-01-01T00:00:00",
                            "debtClearingDateFormatted": "01 januari 2026",
                            "amountPayed": "316.57",
                            "amountPayedFormatted": "€ 316,57",
                            "amountOriginal": "316.57",
                            "amountOriginalFormatted": "€ 316,57",
                            "factuurNummer": "2600013164",
                            "factuurDocumentId": "2600013164",
                            "status": "betaald",
                            "statusDescription": "€ 316,57 betaald op 01 januari 2026",
                            "paylink": "https://betalingen.amsterdam.nl/pay/1758727321/a43e053f0d4c8b87e1b0d60788e3a7de0fa79dc7",
                            "eMandateId": "",
                            "documentDownloadLink": "https://test.mijn.amsterdam.nl/api/v1/services/afis/facturen/document?id=XUiqToAynlKaoBWh-Wz4NqgsLfgBjjq1bMkCyEyZLI2VPWWfGMHLNTQQNfEiaFJj5y9_YrNOT7EeGH1FdSYh9g",
                            "link": {
                                "to": "/facturen-en-betalen/factuur/afgehandeld/2600013164",
                                "title": "Factuur 2600013164",
                            },
                        }
                    ],
                },
                "overgedragen": {"count": 0, "state": "overgedragen", "facturen": []},
            },
        },
        "status": "OK",
    },
    "AFVAL": {
        "content": [
            {
                "titel": "Glas",
                "instructie": "In de container voor glas",
                "instructieCTA": None,
                "ophaaldagen": "",
                "buitenzetten": None,
                "waar": {
                    "to": '/buurt?datasetIds=["afvalcontainers"]&zoom=14&filters={"afvalcontainers"%3A{"fractie_omschrijving"%3A{"values"%3A{"Glas"%3A1}}}}',
                    "title": "Kaart met containers in de buurt",
                },
                "opmerking": None,
                "kalendermelding": None,
                "fractieCode": "Glas",
                "gebruiksdoelWoonfunctie": False,
            },
            {
                "titel": "Groente-, fruit-, etensresten en tuinafval (gfe/t)",
                "instructie": "Bij het restafval",
                "instructieCTA": None,
                "ophaaldagen": "",
                "buitenzetten": None,
                "waar": None,
                "opmerking": 'Tuinafval kunt u ook laten <a href="https://www.amsterdam.nl/tuinafval">ophalen.</a>',
                "kalendermelding": None,
                "fractieCode": "GFT",
                "gebruiksdoelWoonfunctie": False,
            },
            {
                "titel": "Grof afval",
                "instructie": "Laat uw grof afval ophalen door een erkend afvalbedrijf",
                "instructieCTA": None,
                "ophaaldagen": "",
                "buitenzetten": None,
                "waar": None,
                "opmerking": None,
                "kalendermelding": None,
                "fractieCode": "GA",
                "gebruiksdoelWoonfunctie": False,
            },
            {
                "titel": "Papier en karton",
                "instructie": "In de container voor papier",
                "instructieCTA": None,
                "ophaaldagen": "",
                "buitenzetten": None,
                "waar": {
                    "to": '/buurt?datasetIds=["afvalcontainers"]&zoom=14&filters={"afvalcontainers"%3A{"fractie_omschrijving"%3A{"values"%3A{"Papier"%3A1}}}}',
                    "title": "Kaart met containers in de buurt",
                },
                "opmerking": None,
                "kalendermelding": None,
                "fractieCode": "Papier",
                "gebruiksdoelWoonfunctie": False,
            },
            {
                "titel": "Restafval",
                "instructie": "In rolcontainer",
                "instructieCTA": None,
                "ophaaldagen": "Woensdag",
                "buitenzetten": "Dinsdag vanaf 21.00 tot woensdag 07.00 uur",
                "waar": "Aan de rand van de stoep of op de vaste plek",
                "opmerking": None,
                "kalendermelding": None,
                "fractieCode": "Rest",
                "gebruiksdoelWoonfunctie": False,
            },
            {
                "titel": "Textiel",
                "instructie": "In de container voor textiel",
                "instructieCTA": None,
                "ophaaldagen": "",
                "buitenzetten": None,
                "waar": {
                    "to": '/buurt?datasetIds=["afvalcontainers"]&zoom=14&filters={"afvalcontainers"%3A{"fractie_omschrijving"%3A{"values"%3A{"Textiel"%3A1}}}}',
                    "title": "Kaart met containers in de buurt",
                },
                "opmerking": None,
                "kalendermelding": None,
                "fractieCode": "Textiel",
                "gebruiksdoelWoonfunctie": False,
            },
        ],
        "status": "OK",
    },
    "AFVALPUNTEN": {
        "content": {
            "centers": [
                {
                    "title": "Recylepunt Toetsenbordweg (Noord, geen bedrijfsafval)",
                    "latlng": {"lat": 52.4130770200563, "lng": 4.86961095080549},
                    "website": "https://www.amsterdam.nl/afval/spullen-wegbrengen-naar-een-recyclepunt/",
                    "distance": 3,
                },
                {
                    "title": "Recylepunt Seineweg (Nieuw-West)",
                    "latlng": {"lat": 52.386058385908, "lng": 4.82017500674289},
                    "website": "https://www.amsterdam.nl/afval/spullen-wegbrengen-naar-een-recyclepunt/",
                    "distance": 3,
                },
                {
                    "title": "Recylepunt Henk Sneevlietweg (Nieuw-West)",
                    "latlng": {"lat": 52.3433575455427, "lng": 4.83347291303415},
                    "website": "https://www.amsterdam.nl/afval/spullen-wegbrengen-naar-een-recyclepunt/",
                    "distance": 6,
                },
                {
                    "title": "Recylepunt Rozenburglaan (Oost)",
                    "latlng": {"lat": 52.3388475386366, "lng": 4.93782666381194},
                    "website": "https://www.amsterdam.nl/afval/spullen-wegbrengen-naar-een-recyclepunt/",
                    "distance": 11,
                },
                {
                    "title": "Recylepunt Marie Baronlaan (Oost, geen bedrijfsafval)",
                    "latlng": {"lat": 52.3710209755361, "lng": 4.97156727996261},
                    "website": "https://www.amsterdam.nl/afval/spullen-wegbrengen-naar-een-recyclepunt/",
                    "distance": 14,
                },
                {
                    "title": "Recylepunt Meerkerkdreef (Zuidoost)",
                    "latlng": {"lat": 52.302520488967, "lng": 4.97786715111811},
                    "website": "https://www.amsterdam.nl/afval/spullen-wegbrengen-naar-een-recyclepunt/",
                    "distance": 17,
                },
            ]
        },
        "status": "OK",
    },
    "AVG": {"content": {"aantal": 0, "verzoeken": []}, "status": "OK"},
    "BELASTINGEN": {
        "content": {
            "isKnown": False,
            "url": "https://belastingbalie.amsterdam.nl/digid.saml.php?start",
        },
        "status": "OK",
    },
    "BEZWAREN": {
        "content": [
            {
                "identificatie": "JB.26.000022.001",
                "id": "f8c86403-b710-4062-9179-66a838d3b952",
                "uuid": "f8c86403-b710-4062-9179-66a838d3b952",
                "fetchUrl": "https://test.mijn.amsterdam.nl/api/v1/services/bezwaren/bezwaar?id=olKhWVCwpu0Lf9wL7Yqg61VUkQ3XCTsJLAhO0o0mGTEEeUR8UFvSA7dJIuI_YB7h3E70BCuCYmwA1nBjrH2VNv4KS8WxjGx4kdBOaMkcE7Q",
                "ontvangstdatum": "2026-01-21",
                "ontvangstdatumFormatted": "21 januari 2026",
                "startdatum": "2026-01-21",
                "einddatum": None,
                "title": "Bezwaar JB.26.000022.001",
                "omschrijving": "Algemene Verordening Gegevensbescherming - Inzage / correctie persoonsgegevens",
                "toelichting": "Daarom!",
                "displayStatus": "In behandeling",
                "statusdatum": "2026-02-03",
                "steps": [],
                "primairbesluit": "F2026.10401",
                "primairbesluitdatum": "2026-01-14",
                "primairbesluitdatumFormatted": "14 januari 2026",
                "datumResultaat": None,
                "datumResultaatFormatted": None,
                "resultaat": None,
                "documenten": [],
                "link": {
                    "title": "Bekijk details",
                    "to": "/bezwaren/f8c86403-b710-4062-9179-66a838d3b952",
                },
            },
            {
                "identificatie": "JB.22.000182.002",
                "id": "509492ab-2a60-40ba-8f08-f959835a2bfe",
                "uuid": "509492ab-2a60-40ba-8f08-f959835a2bfe",
                "fetchUrl": "https://test.mijn.amsterdam.nl/api/v1/services/bezwaren/bezwaar?id=JaHhTzIK-cc-g7UTnlg2jLzl47uY5Nfsm0cW5ryu8YU8-7CeegkeR-e0bqdJkfahRKPHCARWY4isUdLYqaWY_Dj6Qdu-QR7xMXbBuOuPKcY",
                "ontvangstdatum": "2023-10-13",
                "ontvangstdatumFormatted": "13 oktober 2023",
                "startdatum": "2024-11-03",
                "einddatum": None,
                "title": "Bezwaar JB.22.000182.002",
                "omschrijving": "BESTUURLIJKE BOETE OPENBARE RUIMTE - BBOOR",
                "toelichting": "test",
                "displayStatus": "Beoordeling bezwaarschrift",
                "statusdatum": "2024-12-09",
                "steps": [],
                "primairbesluit": "113334444",
                "primairbesluitdatum": "2022-03-01",
                "primairbesluitdatumFormatted": "01 maart 2022",
                "datumResultaat": None,
                "datumResultaatFormatted": None,
                "resultaat": None,
                "documenten": [],
                "link": {
                    "title": "Bekijk details",
                    "to": "/bezwaren/509492ab-2a60-40ba-8f08-f959835a2bfe",
                },
            },
        ],
        "status": "OK",
    },
    "BODEM": {
        "content": [
            {
                "id": "OL-001359",
                "title": "Lood in de bodem-check",
                "adres": "Buiksloterweg 9C",
                "datumAanvraag": "2021-08-13T09:41:21Z",
                "datumAanvraagFormatted": "13 augustus 2021",
                "datumInbehandeling": "2025-10-03T08:56:14Z",
                "datumAfgehandeldFormatted": "",
                "decision": None,
                "displayStatus": "Ontvangen",
                "processed": False,
                "identifier": "OL-001359",
                "aanvraagNummer": "AV-001371",
                "rapportBeschikbaar": False,
                "rapportId": "56f55acc-36a0-f011-bbd3-7c1e52fb502b",
                "redenAfwijzing": "",
                "link": {
                    "to": "/bodem/lood-meting/OL-001359",
                    "title": "Bekijk loodmeting",
                },
                "document": None,
                "steps": [
                    {
                        "id": "first-item",
                        "status": "Ontvangen",
                        "datePublished": "2021-08-13T09:41:21Z",
                        "description": "",
                        "documents": [],
                        "isActive": True,
                        "isChecked": True,
                    },
                    {
                        "id": "second-item",
                        "status": "In behandeling",
                        "datePublished": "2025-10-03T08:56:14Z",
                        "description": "",
                        "documents": [],
                        "isActive": False,
                        "isChecked": False,
                    },
                    {
                        "id": "third-item",
                        "status": "Afgehandeld",
                        "datePublished": "",
                        "description": "",
                        "documents": [],
                        "isActive": False,
                        "isChecked": False,
                    },
                ],
            },
            {
                "id": "OL-001377",
                "title": "Lood in de bodem-check",
                "adres": "Jeltje de Bosch Kemperpad 131",
                "datumAanvraag": "2021-11-09T09:08:46Z",
                "datumAanvraagFormatted": "09 november 2021",
                "datumAfgehandeldFormatted": "",
                "decision": None,
                "displayStatus": "Ontvangen",
                "processed": False,
                "identifier": "OL-001377",
                "aanvraagNummer": "AV-001383",
                "rapportBeschikbaar": False,
                "redenAfwijzing": "",
                "link": {
                    "to": "/bodem/lood-meting/OL-001377",
                    "title": "Bekijk loodmeting",
                },
                "document": None,
                "steps": [
                    {
                        "id": "first-item",
                        "status": "Ontvangen",
                        "datePublished": "2021-11-09T09:08:46Z",
                        "description": "",
                        "documents": [],
                        "isActive": True,
                        "isChecked": True,
                    },
                    {
                        "id": "second-item",
                        "status": "In behandeling",
                        "datePublished": "",
                        "description": "",
                        "documents": [],
                        "isActive": False,
                        "isChecked": False,
                    },
                    {
                        "id": "third-item",
                        "status": "Afgehandeld",
                        "datePublished": "",
                        "description": "",
                        "documents": [],
                        "isActive": False,
                        "isChecked": False,
                    },
                ],
            },
        ],
        "status": "OK",
    },
    "BRP": {
        "content": {
            "persoon": {
                "voornamen": "Gerrit",
                "voorvoegselGeslachtsnaam": "den",
                "geslachtsnaam": "Braber",
                "naamgebruik": "eigen geslachtsnaam",
                "omschrijvingAdellijkeTitel": None,
                "opgemaakteNaam": "Gerrit den Braber",
                "geboortedatum": "1968-03-18",
                "geboortedatumFormatted": "18 maart 1968",
                "geboortelandnaam": "Nederland",
                "geboorteplaatsnaam": "'s-Gravenhage",
                "overlijdensdatum": None,
                "overlijdensdatumFormatted": None,
                "aanschrijfwijze": "G. den Braber",
                "bsn": "123412341",
                "gemeentenaamInschrijving": "Amsterdam",
                "omschrijvingBurgerlijkeStaat": None,
                "omschrijvingGeslachtsaanduiding": "man",
                "nationaliteiten": [{"omschrijving": "Nederlandse"}],
                "mokum": True,
                "vertrokkenOnbekendWaarheen": False,
                "datumVertrekUitNederlandFormatted": None,
                "datumVertrekUitNederland": None,
                "indicatieGeheim": False,
                "adresInOnderzoek": None,
            },
            "verbintenis": {
                "soortVerbintenis": "huwelijk",
                "datumSluiting": "1997-09-03",
                "datumSluitingFormatted": "3 september 1997",
                "plaats": "'s-Gravenhage",
                "land": "Nederland",
                "datumOntbinding": None,
                "datumOntbindingFormatted": None,
                "persoon": {
                    "voornamen": "Wilma",
                    "voorvoegselGeslachtsnaam": "van",
                    "geslachtsnaam": "Zon",
                    "naamgebruik": None,
                    "omschrijvingAdellijkeTitel": None,
                    "opgemaakteNaam": None,
                    "geboortedatum": "1970-04-07",
                    "geboortedatumFormatted": "7 april 1970",
                    "geboortelandnaam": "Nederland",
                    "geboorteplaatsnaam": "Rotterdam",
                },
            },
            "ouders": [
                {
                    "voornamen": "Maria Evelien",
                    "voorvoegselGeslachtsnaam": None,
                    "geslachtsnaam": "Dijkmans",
                    "naamgebruik": None,
                    "omschrijvingAdellijkeTitel": None,
                    "opgemaakteNaam": None,
                    "geboortedatum": "1944-01-24",
                    "geboortedatumFormatted": "24 januari 1944",
                    "geboortelandnaam": "Nederland",
                    "geboorteplaatsnaam": "Utrecht",
                },
                {
                    "voornamen": "Johannes",
                    "voorvoegselGeslachtsnaam": "den",
                    "geslachtsnaam": "Braber",
                    "naamgebruik": None,
                    "omschrijvingAdellijkeTitel": None,
                    "opgemaakteNaam": None,
                    "geboortedatum": "1938-08-19",
                    "geboortedatumFormatted": "19 augustus 1938",
                    "geboortelandnaam": "Nederland",
                    "geboorteplaatsnaam": "'s-Gravenhage",
                },
            ],
            "kinderen": [
                {
                    "voornamen": "Zoey",
                    "voorvoegselGeslachtsnaam": "den",
                    "geslachtsnaam": "Braber",
                    "naamgebruik": None,
                    "omschrijvingAdellijkeTitel": None,
                    "opgemaakteNaam": None,
                    "geboortedatum": "2018-11-14",
                    "geboortedatumFormatted": "14 november 2018",
                    "geboortelandnaam": "Nederland",
                    "geboorteplaatsnaam": "Amsterdam",
                },
                {
                    "voornamen": "Alexander",
                    "voorvoegselGeslachtsnaam": "den",
                    "geslachtsnaam": "Braber",
                    "naamgebruik": None,
                    "omschrijvingAdellijkeTitel": None,
                    "opgemaakteNaam": None,
                    "geboortedatum": "2009-05-29",
                    "geboortedatumFormatted": "29 mei 2009",
                    "geboortelandnaam": "Nederland",
                    "geboorteplaatsnaam": "Amsterdam",
                },
            ],
            "adres": {
                "locatiebeschrijving": None,
                "straatnaam": "Schakelstraat",
                "postcode": "1014AW",
                "woonplaatsNaam": "Amsterdam",
                "landnaam": None,
                "huisnummer": "14",
                "huisnummertoevoeging": "H",
                "huisletter": None,
                "begindatumVerblijf": "1997-03-02",
                "begindatumVerblijfFormatted": "2 maart 1997",
                "isBewoner": True,
                "isBriefadres": False,
            },
            "fetchUrlAantalIngeschrevenPersonen": "https://test.mijn.amsterdam.nl/api/v1/services/brp/aantal-ingeschreven-personen?id=mR_fvj1e_P51Q3o2B30Ke_yPzgvjPem2-iUDelpIAaAHM7KaZyCYkOcuXSe1lt3g2OyLppqPjpkwukY3i0y-qA",
            "adresHistorisch": [
                {
                    "locatiebeschrijving": None,
                    "straatnaam": "Jacob Catsstraat",
                    "postcode": "2515GK",
                    "woonplaatsNaam": None,
                    "landnaam": None,
                    "huisnummer": "325",
                    "huisnummertoevoeging": None,
                    "huisletter": None,
                    "begindatumVerblijf": "1992-02-01",
                    "begindatumVerblijfFormatted": "1 februari 1992",
                    "isBewoner": True,
                    "isBriefadres": False,
                }
            ],
            "aantalIngeschrevenPersonen": -1,
        },
        "status": "OK",
    },
    "CMS_CONTENT": {
        "content": {
            "title": "Dit ziet u in Mijn Amsterdam",
            "content": '<p>Welkom op Mijn Amsterdam: dit is uw persoonlijke online portaal bij de gemeente Amsterdam.</p><p>Hier ziet u op 1 centrale plek welke gegevens de gemeente van u heeft vastgelegd. U ziet hier ook wat u bij de gemeente heeft aangevraagd, hoe het met uw aanvraag staat en hoe u kunt doorgeven als er iets niet klopt.</p><p><strong>Let op!</strong> Een thema of een product verschijnt alléén als u deze ook heeft afgenomen!</p><p>Op dit moment kunnen de volgende gegevens getoond worden:</p><h4>Mijn gegevens</h4><ul><li>Uw inschrijving bij de gemeente</li><li>Uw contactmomenten met de gemeente</li></ul><h4>Paspoort en ID-kaart</h4><ul><li>Gegevens van uw paspoort of ID-kaart</li></ul><h4>Mijn buurt</h4><ul><li>Overzicht van gemeentelijke informatie rond uw woning</li></ul><h4>Afval</h4><ul><li>Informatie over afval laten ophalen en wegbrengen in uw buurt</li></ul><h4>Belastingen</h4><ul><li>Belastingaanslagen betalen</li><li>Automatische incasso regelen</li><li>Bezwaar indienen</li><li>Kwijtschelding aanvragen</li><li>Betalingsregeling aanvragen</li><li>Aangifte doen</li></ul><h4>Persoonsgegevens AVG</h4><ul><li>Uw inzage of wijziging persoonsgegevens AVG</li></ul><h4>Bezwaren</h4><ul><li>Bezwaren tegen een besluit van de gemeente Amsterdam</li></ul><h4>Klachten</h4><ul><li>Uw ingediende klachten</li></ul><h4>Erfpacht</h4><ul><li>Overzicht van uw erfpachtgegevens</li></ul><h4>Facturen en betalen</h4><ul><li>Overzicht van facturen</li><li>Betalen van facturen</li></ul><h4>Inkomen</h4><ul><li>Uw aanvraag voor een bijstandsuitkering of bijstand voor zelfstandigen (Bbz)</li><li>De uitkeringsspecificaties en jaaropgaven van uw bijstandsuitkering of bijstand voor zelfstandigen (Bbz)</li><li>Uw aanvraag voor de Tijdelijke overbruggingsregeling zelfstandig ondernemers (Tozo 1, 2, 3 en 4)</li><li>Uw aanvraag voor de Tijdelijke Ondersteuning Noodzakelijke Kosten (TONK)</li><li>Uw aanvraag voor de Inkomensvoorziening oudere en gedeeltelijk arbeidsongeschikte gewezen zelfstandigen (IOAZ)</li></ul><h4>Regelingen bij laag inkomen</h4><ul><li>Collectieve zorgverzekering</li><li>Declaratie Kindtegoed</li><li>Kindtegoed Voorschool</li><li>Gratis laptop of tablet middelbare school</li><li>Gratis laptop of tablet basisschool</li><li>Individuele inkomenstoeslag</li><li>Gratis openbaar vervoer voor AOW\'ers</li><li>Tegemoetkoming aanvullend openbaar vervoer voor ouderen</li><li>Tegemoetkoming openbaar vervoer voor mantelzorgers</li></ul><h4>Stadspas</h4><ul><li>Status aanvraag Stadspas van u of uw gezin</li><li>Het saldo Kindtegoed en/of andere tegoeden en de bestedingen</li><li>Stadspasnummer</li><li>Stadspas blokkeren</li></ul><h4>Zorg en ondersteuning</h4><ul><li>Uw Wmo-regelingen (Wmo: wet maatschappelijke ondersteuning)</li></ul><h4>Subsidies</h4><ul><li>Uw aanvraag voor een subsidie</li></ul><h4>Kredietbank &amp; FIBU</h4><ul><li>Informatie over ondersteuning door Kredietbank en Budgetbeheer (FIBU)</li></ul><h4>Toeristische verhuur</h4><ul><li>Uw aanvraag voor een vergunning vakantieverhuur of bed &amp; breakfast</li><li>Uw landelijk registratienummer toeristische verhuur</li><li>Link naar het landelijk portaal om vakantieverhuur door te geven en het aantal nachten verhuur in te zien</li></ul><h4>Parkeren</h4><ul><li>Het inzien, aanvragen of wijzigen van een bewonersvergunning</li></ul><h4>Milieuzone</h4><ul><li>Inzien van uw ontheffingen in de milieuzone</li></ul><h4>Overtredingen voertuigen</h4><ul><li>Inzien van uw overtredingen in de milieuzone</li></ul><h4>Vergunningen en ontheffingen</h4><ul><li><p>Uw aanvraag voor een ontheffing of vergunning voor de volgende activiteiten:</p><ul><li>Ergens rijden of stilstaan waar dat normaal niet mag (RVV en e-RVV)</li><li>Straat tijdelijk afsluiten of afzetten (TVM)</li><li>Object neerzetten op parkeervak, straat of stoep (Objectvergunning)</li><li>Parkeervakken reserveren (TVM)</li><li>Tijdelijk toegang krijgen tot gebied dat is afgesloten met paaltjes (RVV)</li><li>Werkzaamheden uitvoeren op tijden dat het normaal niet mag (Nachtwerkontheffing)</li><li>Filmen (Filmmelding)</li><li>Fietsen en/of fietsenrekken verwijderen</li></ul></li><li>Uw aanvraag of kentekenwijziging voor een RVV-ontheffing Sloterweg</li><li>Uw aanvraag voor een gehandicaptenparkeerkaart (GPK) of een vaste gehandicaptenparkeerplaats (GPP)</li><li>Uw aanvraag voor een ontheffing touringcar</li><li>Uw aanvraag voor een ontheffing zwaar verkeer</li><li>Uw aanvraag voor een ontheffing blauwe zone</li><li>Uw evenementvergunning of evenementmelding</li><li>Uw aanvraag voor een splitsingsvergunning</li><li>Uw aanvraag voor kamerverhuur (omzettingsvergunning)</li><li>Uw aanvraag vergunning straatartiest, draaiorgel of het aanbieden van diensten op straat</li><li>Uw aanvraag ontheffing verspreiden reclamemateriaal (sampling)</li><li>Uw aanvraag voor een vergunning voor onttrekken, samenvoegen en vormen van woonruimte</li><li>Uw aanvraag voor een ligplaatsvergunning</li><li>Uw aanvraag voor een eigen parkeerplaats voor huisartsen, verloskundigen en consuls</li><li>Uw aanvraag voor een vergunning exploitatie horecabedrijf</li></ul><h4>Bodem</h4><ul><li>Uw aanvraag voor \'lood in de bodem-check\'</li></ul><h4>Vragen over Mijn Amsterdam</h4><p>Kijk bij de <a href="https://www.amsterdam.nl/veelgevraagd/?productid=%7B68422ECA-8C56-43EC-A9AA-B3DF190B5077%7D" target="_self">veelgestelde vragen over Mijn Amsterdam</a>.</p>',
        },
        "status": "OK",
    },
    "CMS_MAINTENANCE_NOTIFICATIONS": {
        "content": [
            {
                "title": "Aanpassing jaarbedrag erfpacht",
                "path": "/erfpacht",
                "themaID": "NOTIFICATIONS",
                "themaTitle": "Alle berichten",
                "isAlert": True,
                "severity": "info",
                "datePublished": "2026-07-14T11:01:11.869Z",
                "otapEnvs": ["tst", "acc", "prd"],
                "description": "Elk jaar passen we het jaarbedrag (canon) van uw erfpacht aan. U vindt het nieuwe bedrag terug op Mijn Amsterdam. Dit geldt niet als u de erfpacht heeft afgekocht, of als er andere afspraken over indexatie gelden. Meer informatie vindt u op:",
                "dateStart": "2026-04-29",
                "dateEnd": "2026-12-31",
                "timeStart": "08:45",
                "timeEnd": "23:59",
                "link": {
                    "title": "www.amsterdam.nl/erfpacht",
                    "to": "https://www.amsterdam.nl/erfpacht",
                },
            }
        ],
        "status": "OK",
    },
    "ERFPACHT": {
        "content": None,
        "message": "AxiosError in requestData: Request failed with status code 401",
        "status": "ERROR",
        "code": 401,
    },
    "HLI": {
        "content": {
            "regelingen": [],
            "stadspas": {"stadspassen": [], "dateExpiryFormatted": "31 juli 2026"},
            "specificaties": [],
        },
        "status": "OK",
    },
    "HORECA": {
        "content": [
            {
                "id": "Z-25-2241642",
                "itemType": "folders",
                "key": "2699E01FDF574C56AF2942A4D4DCBC0C",
                "title": "Horeca vergunning exploitatie Horecabedrijf",
                "caseType": "Horeca vergunning exploitatie Horecabedrijf",
                "decision": None,
                "identifier": "Z/25/2241642",
                "processed": False,
                "dateDecision": None,
                "dateRequest": "2025-04-15T00:00:00",
                "dateEnd": None,
                "dateStart": None,
                "location": "9B",
                "isVerleend": False,
                "dateDecisionFormatted": None,
                "dateRequestFormatted": "15 april 2025",
                "steps": [
                    {
                        "id": "step-1",
                        "status": "Ontvangen",
                        "datePublished": "2025-04-15T00:00:00",
                        "description": "",
                        "documents": [],
                        "isActive": False,
                        "isChecked": True,
                    },
                    {
                        "id": "step-2",
                        "status": "In behandeling",
                        "datePublished": "2025-05-20T16:47:14",
                        "description": "",
                        "documents": [],
                        "isActive": True,
                        "isChecked": True,
                    },
                    {
                        "id": "step-3",
                        "status": "Afgehandeld",
                        "datePublished": "",
                        "description": "",
                        "documents": [],
                        "isActive": False,
                        "isChecked": False,
                    },
                ],
                "displayStatus": "In behandeling",
                "link": {
                    "to": "/horeca/horeca-vergunning-exploitatie-horecabedrijf/Z-25-2241642",
                    "title": "Bekijk hoe het met uw aanvraag staat",
                },
                "fetchSourceRaw": "https://test.mijn.amsterdam.nl/api/v1/services/decos/zaak-raw?key=2699E01FDF574C56AF2942A4D4DCBC0C",
                "fetchDocumentsUrl": "https://test.mijn.amsterdam.nl/api/v1/services/decos/documents?id=Eb1rXGy6_th2Df_3UNxszjsk1j_zpOA0PA9qYWOh58TnTkfbnhY40sMc80g9ieMyUDEKSU2OmCgQHtEz1MSJ5Oo6yahevCA7p6P3Ys3fNuY",
            },
            {
                "id": "Z-24-2233281",
                "itemType": "folders",
                "key": "B7410EB717004349B814683E3D27123B",
                "title": "Horeca vergunning exploitatie Horecabedrijf",
                "caseType": "Horeca vergunning exploitatie Horecabedrijf",
                "decision": None,
                "identifier": "Z/24/2233281",
                "processed": False,
                "dateDecision": None,
                "dateRequest": "2024-05-14T00:00:00",
                "dateEnd": None,
                "dateStart": None,
                "location": "Eerste Constantijn Huygensstraat 26 e 1054BR",
                "isVerleend": False,
                "dateDecisionFormatted": None,
                "dateRequestFormatted": "14 mei 2024",
                "steps": [
                    {
                        "id": "step-1",
                        "status": "Ontvangen",
                        "datePublished": "2024-05-14T00:00:00",
                        "description": "",
                        "documents": [],
                        "isActive": True,
                        "isChecked": True,
                    },
                    {
                        "id": "step-2",
                        "status": "In behandeling",
                        "datePublished": "",
                        "description": "",
                        "documents": [],
                        "isActive": False,
                        "isChecked": False,
                    },
                    {
                        "id": "step-3",
                        "status": "Afgehandeld",
                        "datePublished": "",
                        "description": "",
                        "documents": [],
                        "isActive": False,
                        "isChecked": False,
                    },
                ],
                "displayStatus": "Ontvangen",
                "link": {
                    "to": "/horeca/horeca-vergunning-exploitatie-horecabedrijf/Z-24-2233281",
                    "title": "Bekijk hoe het met uw aanvraag staat",
                },
                "fetchSourceRaw": "https://test.mijn.amsterdam.nl/api/v1/services/decos/zaak-raw?key=B7410EB717004349B814683E3D27123B",
                "fetchDocumentsUrl": "https://test.mijn.amsterdam.nl/api/v1/services/decos/documents?id=ZvjsaBU0XF3uw8lYd722z_GoM7oxPkxE466RSE4QVz5kb-cwoBVvw54xHHT2SEbEw8cqA_iQ0o800tppawhoAqQBPpZPfAZXZOQIKhQ4WFQ",
            },
        ],
        "status": "OK",
    },
    "KLACHTEN": {"content": [], "status": "OK"},
    "KREFIA": {
        "content": {
            "deepLinks": [
                {
                    "displayStatus": "Lopend",
                    "link": {
                        "to": "https://krefia-acceptatie.amsterdam.nl/inloggen-fibu",
                        "title": "Ga naar budgetbeheer",
                    },
                    "type": "budgetbeheer",
                }
            ]
        },
        "status": "OK",
    },
    "KVK": {"content": None, "status": "OK"},
    "MILIEUZONE": {
        "content": {
            "isKnown": False,
            "url": "https://ontheffingen-acc.amsterdam.nl/publiek/aanvragen",
        },
        "status": "OK",
    },
    "MY_LOCATION": {
        "content": [
            {
                "latlng": {"lat": 52.390401, "lng": 4.8494121},
                "address": {
                    "locatiebeschrijving": None,
                    "straatnaam": "Schakelstraat",
                    "postcode": "1014AW",
                    "woonplaatsNaam": "Amsterdam",
                    "landnaam": None,
                    "huisnummer": "14",
                    "huisnummertoevoeging": "H",
                    "huisletter": None,
                    "begindatumVerblijf": "1997-03-02",
                    "begindatumVerblijfFormatted": "2 maart 1997",
                    "isBewoner": True,
                    "isBriefadres": False,
                },
                "bagAddress": {
                    "_links": {
                        "schema": "https://schemas.data.amsterdam.nl/datasets/benkagg/adresseerbareobjecten/v1",
                        "self": {
                            "href": "https://api.data.amsterdam.nl/v1/benkagg/adresseerbareobjecten/0363200000264601?volgnummer=1",
                            "title": "0363200000264601",
                            "identificatie": "0363200000264601",
                            "volgnummer": 1,
                        },
                    },
                    "identificatie": "0363200000264601",
                    "volgnummer": 1,
                    "huisnummer": 14,
                    "huisletter": None,
                    "huisnummertoevoeging": "H",
                    "postcode": "1014AW",
                    "documentdatum": "1961-01-01",
                    "documentnummer": "GV00000402",
                    "beginGeldigheid": "1961-01-01T01:00:00",
                    "eindGeldigheid": None,
                    "statusOmschrijving": "Naamgeving uitgegeven",
                    "typeAdresseerbaarObjectOmschrijving": "Verblijfsobject",
                    "typeAdres": "Hoofdadres",
                    "bagProces": None,
                    "adresseertVerblijfsobjectIdentificatie": "0363010000805805",
                    "openbareruimteIdentificatie": "0363300000004469",
                    "openbareruimteVolgnummer": 2,
                    "openbareruimteTypeOmschrijving": "Weg",
                    "openbareruimteNaam": "Schakelstraat",
                    "openbareruimteNaamNen": "Schakelstraat",
                    "openbareruimteBagproces": None,
                    "woonplaatsIdentificatie": "3594",
                    "woonplaatsNaam": "Amsterdam",
                    "woonplaatsVolgnummer": 1,
                    "adres": "Schakelstraat 14-H",
                    "woonplaatsBagproces": "Benoemen woonplaats",
                    "verblijfsobjectId": "0363010000805805.1",
                    "verblijfsobjectIdentificatie": "0363010000805805",
                    "verblijfsobjectVolgnummer": 1,
                    "verblijfsobjectGeconstateerd": False,
                    "verblijfsobjectGeometrie": {
                        "type": "Point",
                        "coordinates": [118391, 489308],
                    },
                    "verblijfsobjectOppervlakte": 456,
                    "verblijfsobjectStatusOmschrijving": "Verblijfsobject in gebruik",
                    "verblijfsobjectGebruiksdoelWoonfunctieOmschrijving": None,
                    "verblijfsobjectGebruiksdoelGezondheidszorgfunctieOmschrijving": None,
                    "verblijfsobjectAantalEenhedenComplex": None,
                    "verblijfsobjectVerdiepingToegang": None,
                    "verblijfsobjectAantalBouwlagen": None,
                    "verblijfsobjectHoogsteBouwlaag": None,
                    "verblijfsobjectLaagsteBouwlaag": None,
                    "verblijfsobjectAantalKamers": None,
                    "verblijfsobjectEigendomsverhoudingOmschrijving": None,
                    "verblijfsobjectFeitelijkGebruikOmschrijving": None,
                    "verblijfsobjectRedenopvoerOmschrijving": None,
                    "verblijfsobjectRedenafvoerOmschrijving": None,
                    "verblijfsobjectDocumentdatum": "2010-09-09",
                    "verblijfsobjectDocumentnummer": "GV00000406",
                    "verblijfsobjectBeginGeldigheid": "2010-09-09T02:00:00",
                    "verblijfsobjectEindGeldigheid": None,
                    "verblijfsobjectBagproces": None,
                    "kenmerkenInOnderzoek": None,
                    "pandenKenmerkenInOnderzoek": None,
                    "ligplaatsIdentificatie": None,
                    "ligplaatsVolgnummer": None,
                    "ligplaatsGeconstateerd": None,
                    "ligplaatsStatusOmschrijving": None,
                    "ligplaatsGeometrie": None,
                    "ligplaatsBeginGeldigheid": None,
                    "ligplaatsEindGeldigheid": None,
                    "ligplaatsDocumentdatum": None,
                    "ligplaatsDocumentnummer": None,
                    "ligplaatsBagproces": None,
                    "standplaatsIdentificatie": None,
                    "standplaatsVolgnummer": None,
                    "standplaatsGeconstateerd": None,
                    "standplaatsStatusOmschrijving": None,
                    "standplaatsGeometrie": None,
                    "standplaatsBeginGeldigheid": None,
                    "standplaatsEindGeldigheid": None,
                    "standplaatsDocumentdatum": None,
                    "standplaatsDocumentnummer": None,
                    "standplaatsBagproces": None,
                    "gebiedenBuurtIdentificatie": "03630980000103",
                    "gebiedenBuurtVolgnummer": 1,
                    "gebiedenBuurtNaam": "Contactbuurt",
                    "gebiedenBuurtCode": "EA02",
                    "gebiedenWijkIdentificatie": "03630970000020",
                    "gebiedenWijkVolgnummer": 1,
                    "gebiedenWijkNaam": "Sloterdijk-West",
                    "gebiedenWijkCode": "EA",
                    "gebiedenStadsdeelIdentificatie": "03630011872036",
                    "gebiedenStadsdeelVolgnummer": 3,
                    "gebiedenStadsdeelNaam": "West",
                    "gebiedenStadsdeelCode": "E",
                    "gebiedenGgwgebiedIdentificatie": "03630950000024",
                    "gebiedenGgwgebiedVolgnummer": 3,
                    "gebiedenGgwgebiedNaam": "Westerpark",
                    "gebiedenGgwgebiedCode": "GE03",
                    "panden": [
                        '{"identificatie":"0363100012085810","volgnummer":2,"status Pand":"Pand in gebruik","bouwjaar Pand":1961,"ligging Pand":"Tussengebouw","bagproces Pand":"Correctie","type woonobject Pand":"Eén woning","geconstateerd Pand":False}'
                    ],
                    "gebiedenBouwblokken": [
                        '{"identificatie":"03630012097150","volgnummer":1,"code":"DG17"}'
                    ],
                    "gebruiksdoelOmschrijvingen": ["industriefunctie"],
                    "standplaatsGebruiksdoelOmschrijvingen": None,
                    "ligplaatsGebruiksdoelOmschrijvingen": None,
                    "toegangOmschrijvingen": None,
                    "wozSoortObjectOmschrijving": ["Kantoor"],
                    "brkGemeenteNaam": "Amsterdam",
                    "adresseerbaarObjectPuntGeometrie": {
                        "type": "Point",
                        "coordinates": [118391, 489308],
                    },
                    "adresseerbaarObjectPuntGeometrieWgs84": {
                        "type": "Point",
                        "coordinates": [4.8494121, 52.390401],
                    },
                },
                "mokum": True,
                "bagNummeraanduidingId": "0363200000264601",
                "profileType": "private",
                "title": "Thuis",
            }
        ],
        "status": "OK",
    },
    "NOTIFICATIONS": {
        "content": [
            {
                "id": "facturen-open-notification",
                "datePublished": "2026-05-07T00:00:00",
                "sortPriority": 6,
                "hideDatePublished": True,
                "themaID": "AFIS",
                "themaTitle": "Facturen en betalen",
                "title": "Betaal tijdig om extra kosten te voorkomen",
                "description": "U heeft 48 openstaande facturen.",
                "link": {
                    "to": "/facturen-en-betalen",
                    "title": "Bekijk uw openstaande facturen",
                },
            },
            {
                "themaID": "PARKEREN",
                "themaTitle": "Parkeren",
                "id": "vergunning-Z-26-2252173-notification",
                "link": {
                    "to": "/parkeren/eigen-parkeerplaats/Z-26-2252173",
                    "title": "Bekijk details",
                },
                "datePublished": "2026-05-16T00:00:00",
                "title": "Aanvraag Eigen parkeerplaats (10GPT3) ontvangen",
                "description": "Wij hebben uw aanvraag Eigen parkeerplaats (10GPT3) met zaaknummer Z/26/2252173 ontvangen.",
            },
            {
                "id": "vergunning-126085267-notification",
                "datePublished": "2023-10-24T22:00:00.0000000Z",
                "themaID": "TOERISTISCHE_VERHUUR",
                "themaTitle": "Toeristische verhuur",
                "title": "Aanvraag vergunning bed & breakfast ontvangen",
                "description": "Wij hebben uw aanvraag voor een vergunning bed &amp; breakfast met zaaknummer Z2023-WK000237 ontvangen.",
                "link": {
                    "to": "/toeristische-verhuur/vergunning/bed-and-breakfast/126085267",
                    "title": "Bekijk uw aanvraag",
                },
            },
            {
                "themaID": "PARKEREN",
                "themaTitle": "Parkeren",
                "id": "vergunning-Z-23-2229751-notification",
                "link": {"to": "/parkeren/gpk/Z-23-2229751", "title": "Bekijk details"},
                "datePublished": "2023-09-29T00:00:00",
                "title": "Aanvraag Europese gehandicaptenparkeerkaart (GPK) in behandeling",
                "description": 'Wij hebben uw aanvraag Europese gehandicaptenparkeerkaart (GPK) met zaaknummer Z/23/2229751 in behandeling genomen. Lees meer over uw aanvraag op <a href="https://www.amsterdam.nl/parkeren/parkeren-gehandicapten/europese-gehandicaptenparkeerkaart/gehandicaptenparkeerkaart-aanvragen/#zo-lang-duurt-het" rel="noopener noreferrer">amsterdam.nl</a>.',
            },
        ],
        "status": "OK",
    },
    "OVERTREDINGEN": {
        "content": {
            "isKnown": False,
            "url": "https://ontheffingen-acc.amsterdam.nl/publiek/aanvragen",
        },
        "status": "OK",
    },
    "PARKEREN": {
        "content": {
            "isKnown": True,
            "url": "https://tma.acc.amsterdam.nl/aselectserver/server/openidconnect_authorize?state=digid&scope=openid&response_mode=form_post&response_type=code&approval_prompt=auto&redirect_uri=https%3A%2F%2Fdev01-ams-fo.egis-group.dev%2Fsso-oauth&client_id=weesp",
            "vergunningen": [
                {
                    "id": "Z-26-2252173",
                    "itemType": "folders",
                    "key": "8188882CCFBB4A06A13E5F73094AAFAD",
                    "title": "Eigen parkeerplaats (10GPT3)",
                    "caseType": "Eigen parkeerplaats",
                    "decision": None,
                    "identifier": "Z/26/2252173",
                    "processed": False,
                    "dateDecision": None,
                    "dateRequest": "2026-05-16T00:00:00",
                    "dateStart": None,
                    "dateEnd": None,
                    "kentekens": "10GPT3",
                    "vorigeKentekens": None,
                    "locations": [
                        {
                            "type": "n.v.t.",
                            "street": "Jodenbreestraat",
                            "houseNumber": "8",
                            "fiscalNumber": "121922486948",
                            "url": "https://data.amsterdam.nl/data/parkeervakken/parkeervakken//",
                        },
                        {
                            "type": "n.v.t.",
                            "street": "Jodenbreestraat",
                            "houseNumber": "8",
                            "fiscalNumber": "121922486948",
                            "url": "https://data.amsterdam.nl/data/parkeervakken/parkeervakken/121922486948/",
                        },
                    ],
                    "requestTypes": ["Verlenging"],
                    "isVerleend": False,
                    "dateDecisionFormatted": None,
                    "dateRequestFormatted": "16 mei 2026",
                    "steps": [
                        {
                            "id": "step-1",
                            "status": "Ontvangen",
                            "datePublished": "2026-05-16T00:00:00",
                            "description": "",
                            "documents": [],
                            "isActive": True,
                            "isChecked": True,
                        },
                        {
                            "id": "step-2",
                            "status": "In behandeling",
                            "datePublished": "",
                            "description": "",
                            "documents": [],
                            "isActive": False,
                            "isChecked": False,
                        },
                        {
                            "id": "step-3",
                            "status": "Afgehandeld",
                            "datePublished": "",
                            "description": "",
                            "documents": [],
                            "isActive": False,
                            "isChecked": False,
                        },
                    ],
                    "displayStatus": "Ontvangen",
                    "link": {
                        "to": "/parkeren/eigen-parkeerplaats/Z-26-2252173",
                        "title": "Bekijk hoe het met uw aanvraag staat",
                    },
                    "fetchSourceRaw": "https://test.mijn.amsterdam.nl/api/v1/services/decos/zaak-raw?key=8188882CCFBB4A06A13E5F73094AAFAD",
                    "fetchDocumentsUrl": "https://test.mijn.amsterdam.nl/api/v1/services/decos/documents?id=xE4O2_9UUSy5YfTT8Tf-Wqbs2xWlEYGaxbyQePGtFr3TqarrUiLaavJ9QeZSghBv0TNNJK4tF2y_94kAzRa3zTk_JM9w5RyK6MplxoWH1lY",
                },
                {
                    "id": "Z-25-2241646",
                    "itemType": "folders",
                    "key": "F7133D57C7FC4E93BB8597E1C5F44270",
                    "title": "Parkeerontheffingen blauwe zone particulieren (12RDT5)",
                    "caseType": "Parkeerontheffingen Blauwe zone particulieren",
                    "decision": None,
                    "identifier": "Z/25/2241646",
                    "processed": False,
                    "dateDecision": None,
                    "dateRequest": "2025-04-16T00:00:00",
                    "dateStart": "2025-05-01T00:00:00",
                    "dateEnd": None,
                    "kentekens": "12RDT5",
                    "isVerleend": False,
                    "dateDecisionFormatted": None,
                    "dateRequestFormatted": "16 april 2025",
                    "steps": [
                        {
                            "id": "step-1",
                            "status": "Ontvangen",
                            "datePublished": "2025-04-16T00:00:00",
                            "description": "",
                            "documents": [],
                            "isActive": False,
                            "isChecked": True,
                        },
                        {
                            "id": "step-2",
                            "status": "In behandeling",
                            "datePublished": "2025-04-16T00:00:00",
                            "description": "",
                            "documents": [],
                            "isActive": True,
                            "isChecked": True,
                        },
                        {
                            "id": "step-3",
                            "status": "Afgehandeld",
                            "datePublished": "",
                            "description": "",
                            "documents": [],
                            "isActive": False,
                            "isChecked": False,
                        },
                    ],
                    "displayStatus": "In behandeling",
                    "link": {
                        "to": "/parkeren/parkeerontheffingen-blauwe-zone-particulieren/Z-25-2241646",
                        "title": "Bekijk hoe het met uw aanvraag staat",
                    },
                    "fetchSourceRaw": "https://test.mijn.amsterdam.nl/api/v1/services/decos/zaak-raw?key=F7133D57C7FC4E93BB8597E1C5F44270",
                    "fetchDocumentsUrl": "https://test.mijn.amsterdam.nl/api/v1/services/decos/documents?id=7_b5Z4pEy4PtddGaAPAV-k7tYSKsVUl-ZfEhksa637e3RZfaFLDRrQCa01qK0XxDAF-5sh6wbhvRqI0ZWdeSjQYtA1EjWLbd4ptr_Gwewe0",
                },
                {
                    "id": "Z-23-2229751",
                    "itemType": "folders",
                    "key": "18BD2CED8D9D4E008EABAFC9ED1EAB35",
                    "title": "Europese gehandicaptenparkeerkaart (GPK)",
                    "caseType": "GPK",
                    "decision": None,
                    "identifier": "Z/23/2229751",
                    "processed": False,
                    "dateDecision": None,
                    "dateRequest": "2023-09-29T00:00:00",
                    "dateStart": None,
                    "dateEnd": None,
                    "cardNumber": None,
                    "cardType": "passagier",
                    "isVerleend": False,
                    "dateDecisionFormatted": None,
                    "dateRequestFormatted": "29 september 2023",
                    "steps": [
                        {
                            "id": "step-1",
                            "status": "Ontvangen",
                            "datePublished": "2023-09-29T00:00:00",
                            "description": "",
                            "documents": [],
                            "isActive": False,
                            "isChecked": True,
                        },
                        {
                            "id": "step-2",
                            "status": "In behandeling",
                            "datePublished": "2023-09-29T00:00:00",
                            "description": 'Lees meer over uw aanvraag op <a href="https://www.amsterdam.nl/parkeren/parkeren-gehandicapten/europese-gehandicaptenparkeerkaart/gehandicaptenparkeerkaart-aanvragen/#zo-lang-duurt-het" rel="noopener noreferrer">amsterdam.nl</a>.',
                            "documents": [],
                            "isActive": True,
                            "isChecked": True,
                        },
                        {
                            "id": "step-3",
                            "status": "Afgehandeld",
                            "datePublished": "",
                            "description": "",
                            "documents": [],
                            "isActive": False,
                            "isChecked": False,
                        },
                    ],
                    "displayStatus": "In behandeling",
                    "link": {
                        "to": "/parkeren/gpk/Z-23-2229751",
                        "title": "Bekijk hoe het met uw aanvraag staat",
                    },
                    "fetchSourceRaw": "https://test.mijn.amsterdam.nl/api/v1/services/decos/zaak-raw?key=18BD2CED8D9D4E008EABAFC9ED1EAB35",
                    "fetchDocumentsUrl": "https://test.mijn.amsterdam.nl/api/v1/services/decos/documents?id=eDE-iktMts2AZ_9K10k6LxwsRpl3Zz_iUp_FsEb-k0EcKreaX-wGcu3qad64H9k7AcUdu6Pb9Aklxw7ayJzQyu1Rpu35KxnLxdJL3K0178Q",
                },
            ],
        },
        "status": "OK",
    },
    "KLANT_CONTACT": {
        "content": {
            "afspraken": [],
            "contactmomenten": [
                {
                    "referenceNumber": "00159219",
                    "subject": "Algemeen",
                    "kanaal": None,
                    "datePublishedFormatted": "22 april 2026",
                    "datePublished": "2026-04-22 09:47:31",
                },
                {
                    "referenceNumber": "00159214",
                    "subject": "Algemeen",
                    "kanaal": None,
                    "datePublishedFormatted": "22 april 2026",
                    "datePublished": "2026-04-22 09:32:15",
                },
                {
                    "referenceNumber": "00159135",
                    "subject": "Algemeen",
                    "kanaal": "Stadsloket",
                    "datePublishedFormatted": "20 april 2026",
                    "datePublished": "2026-04-20 08:02:15",
                },
                {
                    "referenceNumber": "00001967",
                    "subject": "Algemeen",
                    "kanaal": "Telefoon",
                    "datePublishedFormatted": "23 mei 2024",
                    "datePublished": "2024-05-23 07:46:29",
                },
            ],
            "communicatievoorkeuren": {
                "aangeslotenDiensten": [
                    {
                        "id": "2884f739-46e1-4f23-b146-c83899dbfd10",
                        "naam": "zorgned-jzd",
                        "beschrijving": "JZD",
                    },
                    {"id": "zorgned", "beschrijving": "WMO en Jeugdzaken"},
                ],
                "standaardContactgegevens": {
                    "Email": {
                        "id": None,
                        "type": "Email",
                        "value": None,
                        "isVerified": False,
                        "dateModified": None,
                        "dateModifiedFormatted": None,
                    },
                    "Telefoonnummer": {
                        "id": None,
                        "type": "Telefoonnummer",
                        "value": None,
                        "isVerified": False,
                        "dateModified": None,
                        "dateModifiedFormatted": None,
                        "disabled": True,
                    },
                    "ApplicatieId": {
                        "id": None,
                        "type": "ApplicatieId",
                        "value": None,
                        "isVerified": False,
                        "dateModified": None,
                        "dateModifiedFormatted": None,
                    },
                    "Postadres": {
                        "id": None,
                        "type": "Postadres",
                        "dateModified": None,
                        "value": "Schakelstraat 14  H",
                        "dateModifiedFormatted": None,
                    },
                    "Berichtenbox": {
                        "id": None,
                        "type": "Berichtenbox",
                        "value": None,
                        "dateModified": None,
                        "dateModifiedFormatted": None,
                        "disabled": True,
                    },
                },
            },
        },
        "status": "OK",
    },
    "SUBSIDIES": {
        "content": {
            "isKnown": False,
            "url": "https://acc.mijnsubsidies.amsterdam.nl/dashboard?authMethod=digid",
        },
        "status": "OK",
    },
    "SVWI": {"content": None, "status": "POSTPONE"},
    "TOERISTISCHE_VERHUUR": {
        "content": {
            "lvvRegistraties": [],
            "vakantieverhuurVergunningen": [
                {
                    "id": "Z-25-2238908",
                    "itemType": "folders",
                    "key": "D678900046654BD192E2C83FB07FDAF5",
                    "title": "Vergunning vakantieverhuur",
                    "caseType": "Vakantieverhuur vergunningsaanvraag",
                    "decision": "Verleend",
                    "identifier": "Z/25/2238908",
                    "processed": False,
                    "dateDecision": None,
                    "dateRequest": "2025-01-09T00:00:00",
                    "location": "Tesselschadestraat 1 H 2 1054ET Amsterdam",
                    "dateStart": "2025-01-09T00:00:00",
                    "dateEnd": "2026-04-01T00:00:00",
                    "isExpired": True,
                    "dateStartFormatted": "09 januari 2025",
                    "dateEndFormatted": "01 april 2026",
                    "isVerleend": True,
                    "dateDecisionFormatted": None,
                    "dateRequestFormatted": "09 januari 2025",
                    "steps": [
                        {
                            "id": "step-1",
                            "status": "Ontvangen",
                            "datePublished": "2025-01-09T00:00:00",
                            "description": "",
                            "documents": [],
                            "isActive": False,
                            "isChecked": True,
                        },
                        {
                            "id": "step-2",
                            "status": "In behandeling",
                            "datePublished": "2025-01-09T00:00:00",
                            "description": "",
                            "documents": [],
                            "isActive": True,
                            "isChecked": True,
                        },
                        {
                            "id": "step-3",
                            "status": "Afgehandeld",
                            "datePublished": "",
                            "description": "",
                            "documents": [],
                            "isActive": False,
                            "isChecked": False,
                        },
                    ],
                    "displayStatus": "In behandeling",
                    "link": {
                        "to": "/toeristische-verhuur/vergunning/vakantieverhuur-vergunningsaanvraag/Z-25-2238908",
                        "title": "Bekijk hoe het met uw aanvraag staat",
                    },
                    "fetchSourceRaw": "https://test.mijn.amsterdam.nl/api/v1/services/decos/zaak-raw?key=D678900046654BD192E2C83FB07FDAF5",
                    "fetchDocumentsUrl": "https://test.mijn.amsterdam.nl/api/v1/services/decos/documents?id=c0_UxJDCLp3WyLVZ5U3qEUlVjKBTh9H_hXxW-jJWcCD0ojTS4IcOJ1ThKQfNdZKet7BTczznaj48-6DD0BoImO5ZGmZZ7HFMw6KPtS4rOpw",
                },
            ],
        },
        "status": "OK",
    },
    "WMO": {"content": [], "status": "OK"},
    "WPI_AANVRAGEN": {"content": [], "status": "OK"},
    "WPI_BBZ": {
        "content": [
            {
                "about": "Bbz",
                "dateEnd": None,
                "datePublished": "2026-01-20T16:36:12+01:00",
                "dateStart": "2021-09-22T00:00:00+02:00",
                "decision": None,
                "id": "2542b4b99f89ffec22ee61571981a47c",
                "statusId": "informatieOntvangen",
                "steps": [
                    {
                        "datePublished": "2021-09-22T00:00:00+02:00",
                        "documents": [
                            {
                                "datePublished": "2021-09-22T00:00:00+02:00",
                                "dcteId": "844",
                                "id": "400000493",
                                "title": "Aanvraag Bbz\n22 september 2021 00:00",
                                "url": "https://test.mijn.amsterdam.nl/api/v1/services/wpi/document?id=INcwSEUo9SN6ic_PGhWs-O4GxLEvzrnm6kX2UwIRkHYESGH3gqJQzhq05JMhvzTlZnNsm2ZyIbHGaLg5Xny4yg&isBulk=True&isDms=False",
                            },
                            {
                                "datePublished": "2021-09-22T00:00:00+02:00",
                                "dcteId": "844",
                                "id": "400000492",
                                "title": "Aanvraag Bbz\n22 september 2021 00:00",
                                "url": "https://test.mijn.amsterdam.nl/api/v1/services/wpi/document?id=XanuWqc9SyioSizirv6UwmkYeRUbTTNb0KZjasbPDNctAxQGTwY5UxhXSJhP4O-FAEnPqXRoRBlzWNi1f7P30g&isBulk=True&isDms=False",
                            },
                        ],
                        "id": "aanvraag",
                        "status": "Aanvraag",
                        "isActive": False,
                        "isChecked": True,
                        "description": "<p>Wij hebben uw aanvraag Bbz ontvangen. Het kan zijn dat er meer informatie en tijd nodig is om uw aanvraag te behandelen. Bekijk de aanvraag voor meer details.</p>",
                    },
                    {
                        "datePublished": "2023-05-11T11:23:39+02:00",
                        "documents": [
                            {
                                "datePublished": "2023-05-11T11:23:39+02:00",
                                "dcteId": "1538",
                                "id": "400000708",
                                "title": "Bbz: informatie doorgeven",
                                "url": "https://test.mijn.amsterdam.nl/api/v1/services/wpi/document?id=qDR_C7cJ8nR-XAvhK1JMiQymjFmllqZFgBcYjaAAJjzgP69JHNBNZnbgjWI2pJLvZpyuWVjxDrdjM-4HPjxL3w&isBulk=True&isDms=False",
                            }
                        ],
                        "id": "informatieOntvangen",
                        "status": "Informatie ontvangen",
                        "isActive": False,
                        "isChecked": True,
                        "description": "<p>Wij hebben uw formulier 'Bbz: informatie doorgeven' ontvangen op 11 mei om 11.23 uur. Het kan zijn dat er meer informatie en tijd nodig is om uw Bbz-uitkering definitief te kunnen berekenen. Bekijk het formulier voor meer details.</p><p>Wij maken een definitieve berekening van uw Bbz-uitkering en sturen u een besluit. We proberen dit binnen 3 maanden te doen. Het kan langer duren doordat het nog erg druk is op onze afdeling.</p>",
                    },
                    {
                        "datePublished": "2026-01-20T16:36:12+01:00",
                        "documents": [
                            {
                                "datePublished": "2026-01-20T16:36:12+01:00",
                                "dcteId": "1538",
                                "id": "23068535",
                                "title": "Bbz: informatie doorgeven",
                                "url": "https://test.mijn.amsterdam.nl/api/v1/services/wpi/document?id=ICH-BEH3n67-bDMcNGDLFo32qavDXWfyc6g3Fue7O8rTv_cL48s8jxs6O_z3sK3_NoM_0HUTr7B_L9K6AP6REA&isBulk=True&isDms=False",
                            }
                        ],
                        "id": "informatieOntvangen",
                        "status": "Informatie ontvangen",
                        "isActive": True,
                        "isChecked": True,
                        "description": "<p>Wij hebben uw formulier 'Bbz: informatie doorgeven' ontvangen op 20 januari om 16.36 uur. Het kan zijn dat er meer informatie en tijd nodig is om uw Bbz-uitkering definitief te kunnen berekenen. Bekijk het formulier voor meer details.</p><p>Wij maken een definitieve berekening van uw Bbz-uitkering en sturen u een besluit. We proberen dit binnen 3 maanden te doen. Het kan langer duren doordat het nog erg druk is op onze afdeling.</p>",
                    },
                ],
                "title": "Bbz",
                "link": {
                    "to": "/inkomen/bbz/1/2542b4b99f89ffec22ee61571981a47c",
                    "title": "Bekijk uw aanvraag",
                },
                "displayStatus": "Informatie ontvangen",
                "dateStartFormatted": "22 september 2021",
                "dateEndFormatted": None,
            }
        ],
        "status": "OK",
    },
    "WPI_SPECIFICATIES": {
        "content": {"jaaropgaven": [], "uitkeringsspecificaties": []},
        "status": "OK",
    },
    "WPI_TONK": {
        "content": [
            {
                "about": "TONK",
                "dateEnd": None,
                "datePublished": "2021-07-02T23:44:31+02:00",
                "dateStart": "2021-02-24T17:42:11+01:00",
                "decision": None,
                "id": "2f4079a4ea1d6c6355eea447e673888d",
                "statusId": "aanvraag",
                "steps": [
                    {
                        "datePublished": "2021-02-24T17:42:11+01:00",
                        "documents": [
                            {
                                "datePublished": "2021-02-24T17:42:11+01:00",
                                "dcteId": "802",
                                "id": "400000440",
                                "title": "Aanvraag TONK\n24 februari 2021 17:42",
                                "url": "https://test.mijn.amsterdam.nl/api/v1/services/wpi/document?id=28GPHEZODvFmSm6_NT4Si6jMTSeCkD5WD87hwlUeEs_XbACsFOK37x_c2Ez6bPnEiJ6QArNsb_m6kADLc495_w&isBulk=True&isDms=False",
                            },
                            {
                                "datePublished": "2021-02-26T14:10:43+01:00",
                                "dcteId": "802",
                                "id": "400000561",
                                "title": "Aanvraag TONK\n26 februari 2021 14:10",
                                "url": "https://test.mijn.amsterdam.nl/api/v1/services/wpi/document?id=UCXiCryvfTl0aTn250aQ1j5U1XcRzA7__HA_bL2YyXRmm70m7yO61foGAqSZkB9N0pIb2UCEN8ULvzqh9Xsy8Q&isBulk=True&isDms=False",
                            },
                            {
                                "datePublished": "2021-07-02T23:44:31+02:00",
                                "dcteId": "802",
                                "id": "400000782",
                                "title": "Aanvraag TONK\n02 juli 2021 23:44",
                                "url": "https://test.mijn.amsterdam.nl/api/v1/services/wpi/document?id=JOvjsxoAVehf8Cm03DbgFCgEqId6I_IpAnGfE0hBKd6wj0kwLEDb7q0ZXQfbZ7DYnpkm3AmwvVTtqJ6QaTRrAg&isBulk=True&isDms=False",
                            },
                        ],
                        "id": "aanvraag",
                        "productSpecific": "uitkering",
                        "status": "Aanvraag",
                        "isActive": True,
                        "isChecked": True,
                        "description": "<p>\n        Wij hebben uw aanvraag TONK ontvangen.\n      </p>",
                    }
                ],
                "title": "TONK",
                "link": {
                    "to": "/inkomen/tonk/1/2f4079a4ea1d6c6355eea447e673888d",
                    "title": "Bekijk uw aanvraag",
                },
                "displayStatus": "Aanvraag",
                "dateStartFormatted": "24 februari 2021",
                "dateEndFormatted": None,
            }
        ],
        "status": "OK",
    },
    "WPI_TOZO": {
        "content": [
            {
                "about": "Tozo 1",
                "dateEnd": None,
                "datePublished": "2022-06-24T12:20:54+02:00",
                "dateStart": "2020-03-28T10:33:49+01:00",
                "decision": None,
                "id": "cc1cecbe5bf7f201bf8a2972f47a5a9d",
                "statusId": "aanvraag",
                "steps": [
                    {
                        "datePublished": "2020-03-28T10:33:49+01:00",
                        "documents": [
                            {
                                "datePublished": "2020-03-28T10:33:49+01:00",
                                "dcteId": "770",
                                "id": "400001032",
                                "title": "Aanvraag Tozo 1\n28 maart 2020 10:33",
                                "url": "https://test.mijn.amsterdam.nl/api/v1/services/wpi/document?id=5AChvH3gudFI4GX4Eltdyg0YCxgGbTz8f5Yrz32WmwRIbPqmaCW0EkiTy4Pr3hg9EFrSRP11GWYFrII_zZkmjQ&isBulk=True&isDms=False",
                            },
                            {
                                "datePublished": "2020-03-28T10:33:49+01:00",
                                "dcteId": "756",
                                "id": "400000910",
                                "title": "Aanvraag Tozo 1\n28 maart 2020 10:33",
                                "url": "https://test.mijn.amsterdam.nl/api/v1/services/wpi/document?id=J22QK3S9M79xn6-GqtyX6alON7kMI5RqIYD__x-DtYhyv6oQuHIB2C9qVaGHpcSNRg5brJXdoXE_a5RJCLf9Ig&isBulk=True&isDms=False",
                            },
                            {
                                "datePublished": "2022-06-24T12:20:54+02:00",
                                "dcteId": "770",
                                "id": "400000645",
                                "title": "Aanvraag Tozo 1\n24 juni 2022 12:20",
                                "url": "https://test.mijn.amsterdam.nl/api/v1/services/wpi/document?id=teCkjZmRI9YUanchE-CVmq4nPe9poHNZI37iSYD9SMtbFa7JvLM5Qh1jMxj75i31Ts4q09led3ZGunhD2MNlJA&isBulk=True&isDms=False",
                            },
                        ],
                        "id": "aanvraag",
                        "status": "Aanvraag",
                        "isActive": True,
                        "isChecked": True,
                        "description": "<p>\n        Wij hebben uw aanvraag Tozo 1 ontvangen.\n      </p>",
                    }
                ],
                "title": "Tozo 1 (aangevraagd voor 1 juni 2020)",
                "link": {
                    "to": "/inkomen/tozo/1/cc1cecbe5bf7f201bf8a2972f47a5a9d",
                    "title": "Bekijk uw aanvraag",
                },
                "displayStatus": "Aanvraag",
                "dateStartFormatted": "28 maart 2020",
                "dateEndFormatted": None,
            },
            {
                "about": "Tozo 2",
                "dateEnd": None,
                "datePublished": "2021-06-17T13:23:54+02:00",
                "dateStart": "2020-06-04T15:06:17+02:00",
                "decision": None,
                "id": "44bcc9f2ab0cd9bd01492ec8a38e4702",
                "statusId": "inkomstenwijziging",
                "steps": [
                    {
                        "datePublished": "2020-06-04T15:06:17+02:00",
                        "documents": [
                            {
                                "datePublished": "2020-06-04T15:06:17+02:00",
                                "dcteId": "777",
                                "id": "400000964",
                                "title": "Aanvraag Tozo 2\n04 juni 2020 15:06",
                                "url": "https://test.mijn.amsterdam.nl/api/v1/services/wpi/document?id=uOLSK-yM1AoShEOsfnrAtJnXX1ApbhnAhA6NbqcqE7BUiVhbri-lGdP2YOZXxvHXAULklWhzH29lirCO_KSHqw&isBulk=True&isDms=False",
                            },
                            {
                                "datePublished": "2020-07-15T20:17:22+02:00",
                                "dcteId": "777",
                                "id": "400000988",
                                "title": "Aanvraag Tozo 2\n15 juli 2020 20:17",
                                "url": "https://test.mijn.amsterdam.nl/api/v1/services/wpi/document?id=NOeMvLzriDUwqfQHzZmgtbsKqgces_dh4Fb6fhlj2-kbuQ-N92qfm5_sVAZDCyLa6kBIHS89NqUe8CZFawcSbA&isBulk=True&isDms=False",
                            },
                            {
                                "datePublished": "2020-09-14T15:49:40+02:00",
                                "dcteId": "777",
                                "id": "400000989",
                                "title": "Aanvraag Tozo 2\n14 september 2020 15:49",
                                "url": "https://test.mijn.amsterdam.nl/api/v1/services/wpi/document?id=QbbRARo1fRT9vHIEwM-GUOhCCQnJ4DlS1cD2m39h9KD7UssgVPAreleAm2N9Vs-xFLOZ3bQbNDm2WYdtwPC89A&isBulk=True&isDms=False",
                            },
                        ],
                        "id": "aanvraag",
                        "status": "Aanvraag",
                        "isActive": False,
                        "isChecked": True,
                        "description": "<p>\n        Wij hebben uw aanvraag Tozo 2 ontvangen.\n      </p>",
                    },
                    {
                        "datePublished": "2020-12-17T14:57:35+01:00",
                        "documents": [
                            {
                                "datePublished": "2020-12-17T14:57:35+01:00",
                                "dcteId": "790",
                                "id": "400000599",
                                "title": "Wijziging inkomsten",
                                "url": "https://test.mijn.amsterdam.nl/api/v1/services/wpi/document?id=mf1Dij4sP3qYTn4PfWvuL2dGzWRyaNI68dKiJ2ZRHV5KlMgebLwbM8fwujSWj9wgzD8K3uHrA9Jg9oBnpP83nA&isBulk=True&isDms=False",
                            }
                        ],
                        "id": "inkomstenwijziging",
                        "status": "Wijziging inkomsten",
                        "isActive": False,
                        "isChecked": True,
                        "description": "\n    <p>Wij hebben een wijziging van uw inkomsten voor Tozo 2 (aangevraagd vanaf 1 juni 2020) ontvangen op 17 december om 14.57 uur</p>\n    <p>De wijziging wordt zo snel mogelijk verwerkt. Als u een nabetaling krijgt dan ziet u dat op uw uitkeringsspecificatie. Als u moet terugbetalen dan ontvangt u daarover een besluit per post.</p>",
                    },
                    {
                        "datePublished": "2020-12-18T14:27:08+01:00",
                        "documents": [
                            {
                                "datePublished": "2020-12-18T14:27:08+01:00",
                                "dcteId": "790",
                                "id": "400000284",
                                "title": "Wijziging inkomsten",
                                "url": "https://test.mijn.amsterdam.nl/api/v1/services/wpi/document?id=2GW8jcylvtme2L2VQf9rVBLi3_QLBK1S9btLgouA3JU3uKPHHMKpdadm4aX4-7EpymbztQaYtpupqByq3OPQ9A&isBulk=True&isDms=False",
                            }
                        ],
                        "id": "inkomstenwijziging",
                        "status": "Wijziging inkomsten",
                        "isActive": False,
                        "isChecked": True,
                        "description": "\n    <p>Wij hebben een wijziging van uw inkomsten voor Tozo 2 (aangevraagd vanaf 1 juni 2020) ontvangen op 18 december om 14.27 uur</p>\n    <p>De wijziging wordt zo snel mogelijk verwerkt. Als u een nabetaling krijgt dan ziet u dat op uw uitkeringsspecificatie. Als u moet terugbetalen dan ontvangt u daarover een besluit per post.</p>",
                    },
                    {
                        "datePublished": "2021-06-17T13:23:54+02:00",
                        "documents": [
                            {
                                "datePublished": "2021-06-17T13:23:54+02:00",
                                "dcteId": "790",
                                "id": "400000630",
                                "title": "Wijziging inkomsten",
                                "url": "https://test.mijn.amsterdam.nl/api/v1/services/wpi/document?id=YFA1YGLVlHPE34zcRPvKI_0cnATPqSYFDv6qYtoMUnNvkznh5Qud6WykHAnNHnVNPtJecsBy8XJoYwsgjY6V7Q&isBulk=True&isDms=False",
                            }
                        ],
                        "id": "inkomstenwijziging",
                        "status": "Wijziging inkomsten",
                        "isActive": True,
                        "isChecked": True,
                        "description": "\n    <p>Wij hebben een wijziging van uw inkomsten voor Tozo 2 (aangevraagd vanaf 1 juni 2020) ontvangen op 17 juni om 13.23 uur</p>\n    <p>De wijziging wordt zo snel mogelijk verwerkt. Als u een nabetaling krijgt dan ziet u dat op uw uitkeringsspecificatie. Als u moet terugbetalen dan ontvangt u daarover een besluit per post.</p>",
                    },
                ],
                "title": "Tozo 2 (aangevraagd vanaf 1 juni 2020)",
                "link": {
                    "to": "/inkomen/tozo/2/44bcc9f2ab0cd9bd01492ec8a38e4702",
                    "title": "Bekijk uw aanvraag",
                },
                "displayStatus": "Wijziging inkomsten",
                "dateStartFormatted": "04 juni 2020",
                "dateEndFormatted": None,
            },
            {
                "about": "Tozo 5",
                "dateEnd": None,
                "datePublished": "2021-07-01T00:00:00+02:00",
                "dateStart": "2021-07-01T00:00:00+02:00",
                "decision": None,
                "id": "d3de4ce5a2aaf2cdcaa273baee43b1f2",
                "statusId": "aanvraag",
                "steps": [
                    {
                        "datePublished": "2021-07-01T00:00:00+02:00",
                        "documents": [
                            {
                                "datePublished": "2021-07-01T00:00:00+02:00",
                                "dcteId": "837",
                                "id": "400000866",
                                "title": "Aanvraag Tozo 5\n01 juli 2021 00:00",
                                "url": "https://test.mijn.amsterdam.nl/api/v1/services/wpi/document?id=seNKa2dKWx_0nzgf8iL5Wcz4Du_zTkH1vVYpzWLZpxYRNm8tuJ7LBAM3AhDz82KfjOg-pSNpOtcZbCv0IpIsFQ&isBulk=True&isDms=False",
                            }
                        ],
                        "id": "aanvraag",
                        "status": "Aanvraag",
                        "isActive": True,
                        "isChecked": True,
                        "description": "<p>\n        Wij hebben uw aanvraag Tozo 5 ontvangen.\n      </p>",
                    }
                ],
                "title": "Tozo 5 (aangevraagd vanaf 1 juli 2021)",
                "link": {
                    "to": "/inkomen/tozo/5/d3de4ce5a2aaf2cdcaa273baee43b1f2",
                    "title": "Bekijk uw aanvraag",
                },
                "displayStatus": "Aanvraag",
                "dateStartFormatted": "01 juli 2021",
                "dateEndFormatted": None,
            },
        ],
        "status": "OK",
    },
    "WONEN": {
        "content": {
            "vve": {
                "bagId": "0363010000801904",
                "beschermdStadsdorpsgezicht": None,
                "buildYear": 1965,
                "district": "Nieuw-West",
                "kvkNummer": "50210556",
                "ligtInBeschermdGebied": "nee",
                "monumentStatus": None,
                "name": "Vereniging van Eigenaren Flatgebouw S.F. van Ossstraat 60 tot en met 358 (even) te Amsterdam-West",
                "numberOfApartments": 135,
            }
        },
        "status": "OK",
    },
    "JEUGD": {"content": [], "status": "OK"},
    "KTO": {
        "content": {
            "version": 1,
            "createdAt": "2026-01-20T14:51:03.230267+01:00",
            "activeFrom": "2026-01-20T14:50:40+01:00",
            "questions": [
                {
                    "id": 3,
                    "questionText": "Wat vindt u van deze pagina?",
                    "description": "Aantal sterren",
                    "questionType": "numeric",
                    "required": False,
                    "maxCharacters": 5,
                },
                {
                    "id": 2,
                    "questionText": "Heeft u nog een tip of compliment voor ons?",
                    "description": "Feedback vrij invul",
                    "questionType": "textarea",
                    "required": False,
                    "maxCharacters": 300,
                },
                {
                    "id": 1,
                    "questionText": "Uw e-mailadres (niet verplicht)",
                    "description": "E-mail",
                    "questionType": "email",
                    "required": False,
                    "maxCharacters": 0,
                },
            ],
        },
        "status": "OK",
    },
}
