# Generated by Django 6.0 on 2026-05-08
import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="NewsArticle",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("foreign_id", models.BigIntegerField(unique=True)),
                ("last_seen", models.DateTimeField(auto_now=True)),
                ("title", models.CharField(max_length=1000)),
                ("summary", models.TextField(blank=True, null=True, default=None)),
                ("intro", models.TextField(blank=True, null=True, default=None)),
                ("body", models.TextField(blank=True, null=True, default=None)),
                (
                    "type",
                    models.CharField(
                        max_length=30,
                        choices=[
                            ("article", "Article"),
                            ("highlight", "Highlight"),
                            ("liveblog", "Liveblog"),
                            ("district", "District"),
                        ],
                    ),
                ),
                (
                    "district",
                    models.CharField(
                        max_length=30,
                        choices=[
                            ("noord", "Noord"),
                            ("west", "West"),
                            ("zuid", "Zuid"),
                            ("oost", "Oost"),
                            ("centrum", "Centrum"),
                            ("nieuw-west", "Nieuw-West"),
                            ("zuidoost", "Zuidoost"),
                            ("weesp", "Weesp"),
                        ],
                        blank=True,
                        null=True,
                        default=None,
                    ),
                ),
                ("url", models.URLField(max_length=2048)),
                (
                    "creation_date",
                    models.DateTimeField(default=django.utils.timezone.now),
                ),
                (
                    "modification_date",
                    models.DateTimeField(default=django.utils.timezone.now),
                ),
                ("publication_date", models.DateTimeField()),
                ("expiration_date", models.DateTimeField(default=None, null=True)),
            ],
        ),
        migrations.CreateModel(
            name="NewsArticleImage",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("url", models.URLField(max_length=2048)),
                ("width", models.IntegerField()),
                ("height", models.IntegerField()),
                (
                    "article",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="images",
                        to="news.newsarticle",
                    ),
                ),
            ],
        ),
    ]
