# Generated by Django 6.0.5 on 2026-05-18 14:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='newsarticle',
            old_name='creation_date',
            new_name='creation_datetime',
        ),
        migrations.RenameField(
            model_name='newsarticle',
            old_name='expiration_date',
            new_name='expiration_datetime',
        ),
        migrations.RenameField(
            model_name='newsarticle',
            old_name='modification_date',
            new_name='modification_datetime',
        ),
        migrations.RenameField(
            model_name='newsarticle',
            old_name='publication_date',
            new_name='publication_datetime',
        ),
        migrations.CreateModel(
            name='LiveBlogItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creation_datetime', models.DateTimeField()),
                ('title', models.CharField(max_length=1000)),
                ('body', models.TextField(blank=True, null=True)),
                ('article', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='liveblog_items', to='news.newsarticle')),
            ],
            options={
                'ordering': ['-creation_datetime'],
            },
        ),
        migrations.CreateModel(
            name='LiveBlogItemImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.URLField(max_length=2048)),
                ('width', models.IntegerField()),
                ('height', models.IntegerField()),
                ('liveblog_item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='news.liveblogitem')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
