# Generated by Django 6.0.5 on 2026-05-19 11:53

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("news", "0001_initial"),
    ]

    operations = [
        migrations.AddConstraint(
            model_name="newsarticle",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    models.Q(("type", "district"), _negated=True),
                    ("district__isnull", False),
                    _connector="OR",
                ),
                name="district_article_requires_district",
            ),
        ),
    ]
