# Generated by Django 6.0.5 on 2026-05-19 09:48

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("news", "0002_rename_creation_date_newsarticle_creation_datetime_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="liveblogitemimage",
            name="foreign_id",
            field=models.BigIntegerField(default=0),
        ),
        migrations.AddField(
            model_name="newsarticleimage",
            name="foreign_id",
            field=models.BigIntegerField(default=0),
        ),
    ]
