# Generated by Django 6.0.5 on 2026-05-27 13:17

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("news", "0005_liveblognotification"),
    ]

    operations = [
        migrations.AddField(
            model_name="newsarticle",
            name="is_active_liveblog",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="newsarticle",
            name="liveblog_notification_send",
            field=models.DateTimeField(default=None, null=True),
        ),
    ]
