# Generated by Django 6.0.5 on 2026-05-28 10:56

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("news", "0006_newsarticle_is_active_liveblog_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="newsarticle",
            name="liveblog_version",
            field=models.IntegerField(default=None, null=True),
        ),
    ]
