# Generated by Django 6.0.5 on 2026-05-29 09:09

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("news", "0007_newsarticle_liveblog_version"),
    ]

    operations = [
        migrations.RenameField(
            model_name="liveblogitemimage",
            old_name="url",
            new_name="uri",
        ),
        migrations.RenameField(
            model_name="newsarticleimage",
            old_name="url",
            new_name="uri",
        ),
        migrations.AlterUniqueTogether(
            name="liveblogitemimage",
            unique_together={("liveblog_item", "uri")},
        ),
        migrations.AlterUniqueTogether(
            name="newsarticleimage",
            unique_together={("article", "uri")},
        ),
    ]
