# Generated by Django 6.0.5 on 2026-06-04 14:08

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("news", "0008_rename_url_liveblogitemimage_uri_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="newsarticle",
            name="deleted",
            field=models.BooleanField(db_index=True, default=False),
        ),
    ]
