# Generated by Django 6.0.5 on 2026-06-05

from django.db import migrations, models


def backfill_source_flags(apps, schema_editor):
    NewsArticle = apps.get_model("news", "NewsArticle")

    NewsArticle.objects.filter(type="article").update(in_all_news=True)
    NewsArticle.objects.filter(type="highlight").update(is_highlight=True)
    NewsArticle.objects.filter(type="liveblog").update(is_liveblog=True)
    NewsArticle.objects.filter(type="district").update(is_district=True)


class Migration(migrations.Migration):
    dependencies = [
        ("news", "0009_newsarticle_deleted"),
    ]

    operations = [
        migrations.AddField(
            model_name="newsarticle",
            name="in_all_news",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="newsarticle",
            name="is_district",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="newsarticle",
            name="is_highlight",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="newsarticle",
            name="is_liveblog",
            field=models.BooleanField(default=False),
        ),
        migrations.RunPython(backfill_source_flags, migrations.RunPython.noop),
    ]
