# Generated by Django 6.0.5 on 2026-06-09 06:05

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("news", "0009_newsarticle_deleted"),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name="newsarticle",
            name="district_article_requires_district",
        ),
        migrations.AddField(
            model_name="newsarticle",
            name="in_all_news",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="newsarticle",
            name="is_district",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="newsarticle",
            name="is_highlight",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="newsarticle",
            name="is_liveblog",
            field=models.BooleanField(default=False),
        ),
        migrations.AddConstraint(
            model_name="newsarticle",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    models.Q(("district__isnull", False), ("is_district", True)),
                    models.Q(("district__isnull", True), ("is_district", False)),
                    _connector="OR",
                ),
                name="district_article_requires_district",
            ),
        ),
        migrations.RemoveField(
            model_name="newsarticle",
            name="type",
        ),
    ]
