# Generated by Django 6.0.5 on 2026-06-12 08:37

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("news", "0010_remove_newsarticle_district_article_requires_district_and_more"),
    ]

    operations = [
        migrations.DeleteModel(
            name="LiveBlogItemImage",
        ),
    ]
