# Generated by Django 6.0.5 on 2026-06-17 14:42

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("news", "0011_delete_liveblogitemimage"),
    ]

    operations = [
        migrations.RenameField(
            model_name="newsarticleimage",
            old_name="article",
            new_name="parent",
        ),
        migrations.AddField(
            model_name="newsarticle",
            name="is_construction_work",
            field=models.BooleanField(default=False),
        ),
        migrations.AlterUniqueTogether(
            name="newsarticleimage",
            unique_together={("parent", "uri")},
        ),
    ]
