# Generated by Django 6.0.5 on 2026-06-18 07:47

import uuid

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("news", "0012_rename_article_newsarticleimage_parent_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="Project",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("foreign_id", models.BigIntegerField(unique=True)),
                ("active", models.BooleanField(default=True)),
                ("last_seen", models.DateTimeField()),
                ("hidden", models.BooleanField(default=False)),
                ("title", models.CharField(db_index=True, max_length=1000)),
                ("subtitle", models.CharField(blank=True, max_length=1000, null=True)),
                ("url", models.URLField(max_length=2048)),
                (
                    "timeline_title",
                    models.CharField(blank=True, max_length=1000, null=True),
                ),
                (
                    "timeline_intro",
                    models.CharField(blank=True, max_length=1000, null=True),
                ),
                ("coordinates_lat", models.FloatField(blank=True, null=True)),
                ("coordinates_lon", models.FloatField(blank=True, null=True)),
                (
                    "creation_date",
                    models.DateTimeField(default=django.utils.timezone.now),
                ),
                (
                    "modification_date",
                    models.DateTimeField(default=django.utils.timezone.now),
                ),
                ("publication_date", models.DateTimeField(default=None, null=True)),
                ("expiration_date", models.DateTimeField(default=None, null=True)),
            ],
            options={
                "ordering": ["title"],
            },
        ),
        migrations.CreateModel(
            name="ProjectContact",
            fields=[
                ("id", models.FloatField(primary_key=True, serialize=False)),
                ("name", models.CharField(blank=True, null=True)),
                ("email", models.CharField(blank=True, null=True)),
                ("phone", models.CharField(blank=True, null=True)),
                ("position", models.CharField(blank=True, null=True)),
                ("extra", models.CharField(blank=True, null=True)),
                (
                    "project",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="contacts",
                        to="news.project",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="ProjectSection",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("body", models.CharField(blank=True, null=True)),
                ("title", models.CharField()),
                (
                    "type",
                    models.CharField(
                        choices=[
                            ("where", "where"),
                            ("what", "what"),
                            ("when", "when"),
                            ("work", "work"),
                            ("contact", "contact"),
                        ],
                        max_length=10,
                    ),
                ),
                (
                    "project",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="sections",
                        to="news.project",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="ProjectSectionUrl",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("url", models.CharField()),
                ("label", models.CharField()),
                (
                    "section",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="links",
                        to="news.projectsection",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="ProjectTimelineItem",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("title", models.CharField(blank=True, null=True)),
                ("body", models.CharField(blank=True, null=True)),
                ("collapsed", models.BooleanField(blank=True, null=True)),
                (
                    "parent",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="items",
                        to="news.projecttimelineitem",
                    ),
                ),
                (
                    "project",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="timeline_items",
                        to="news.project",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="ProjectImage",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("foreign_id", models.BigIntegerField(default=0)),
                ("uri", models.URLField(max_length=2048)),
                ("width", models.IntegerField()),
                ("height", models.IntegerField()),
                (
                    "parent",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="images",
                        to="news.project",
                    ),
                ),
            ],
            options={
                "unique_together": {("parent", "uri")},
            },
        ),
    ]
