# Generated by Django 4.2.4 on 2024-02-05 10:10

import django.contrib.postgres.fields
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="AppRelease",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("version", models.CharField(max_length=100, unique=True)),
                (
                    "release_notes",
                    models.CharField(blank=True, max_length=2000, null=True),
                ),
                ("published", models.DateTimeField(null=True)),
                ("unpublished", models.DateTimeField(null=True)),
                ("created", models.DateTimeField(auto_now_add=True)),
                ("modified", models.DateTimeField(auto_now=True)),
                (
                    "module_order",
                    django.contrib.postgres.fields.ArrayField(
                        base_field=models.CharField(max_length=500), size=None
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Module",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("slug", models.CharField(max_length=100, unique=True)),
                (
                    "status",
                    models.IntegerField(
                        choices=[(0, "inactive"), (1, "active")], default=1
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="ModuleVersion",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("version", models.CharField(max_length=100)),
                ("title", models.CharField(max_length=500)),
                ("icon", models.CharField(max_length=100)),
                ("description", models.CharField(max_length=1000)),
                ("created", models.DateTimeField(auto_now_add=True)),
                ("modified", models.DateTimeField(auto_now=True)),
                (
                    "module",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT, to="modules.module"
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="ReleaseModuleStatus",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "status",
                    models.IntegerField(
                        choices=[(0, "inactive"), (1, "active")], default=1
                    ),
                ),
                (
                    "app_release",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="modules.apprelease",
                    ),
                ),
                (
                    "module_version",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="modules.moduleversion",
                    ),
                ),
            ],
        ),
        migrations.AddConstraint(
            model_name="releasemodulestatus",
            constraint=models.UniqueConstraint(
                fields=("app_release", "module_version"),
                name="unique_app_release_module_version",
            ),
        ),
        migrations.AddConstraint(
            model_name="moduleversion",
            constraint=models.UniqueConstraint(
                fields=("module", "version"), name="unique_module_version"
            ),
        ),
    ]
