# Generated by Django 4.2.4 on 2024-02-20 15:33

from django.db import migrations, models


class Migration(migrations.Migration):
    replaces = [
        ("modules", "0002_moduleversion_deprecated_date_and_more"),
        ("modules", "0003_remove_moduleversion_deprecated_date_and_more"),
        ("modules", "0004_rename_deprecated_apprelease_deprecated_date"),
        ("modules", "0005_rename_deprecated_date_apprelease_deprecated"),
    ]

    dependencies = [
        ("modules", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="apprelease",
            name="deprecated",
            field=models.DateTimeField(null=True),
        ),
    ]
