# Generated by Django 5.1 on 2025-06-12 13:37

import django.contrib.postgres.fields
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        (
            "modules",
            "0002_moduleversion_deprecated_date_and_more_squashed_0005_rename_deprecated_date_apprelease_deprecated",
        ),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="releasemodulestatus",
            options={
                "ordering": ["sort_order"],
                "verbose_name": "Release Module State",
                "verbose_name_plural": "Release Module Status",
            },
        ),
        migrations.AddField(
            model_name="apprelease",
            name="modules",
            field=models.ManyToManyField(
                through="modules.ReleaseModuleStatus", to="modules.moduleversion"
            ),
        ),
        migrations.AddField(
            model_name="module",
            name="reason",
            field=models.CharField(
                blank=True,
                help_text="Reason for the status change",
                max_length=500,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="releasemodulestatus",
            name="reason",
            field=models.CharField(
                blank=True,
                help_text="Reason for the status change",
                max_length=500,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="releasemodulestatus",
            name="sort_order",
            field=models.PositiveIntegerField(db_index=True, null=True),
        ),
        migrations.AlterField(
            model_name="apprelease",
            name="deprecated",
            field=models.DateTimeField(
                blank=True,
                help_text="De deprecateddatum bepaalt vanaf wanneer gebruikers van deze release een update suggestie melding krijgen.",
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="apprelease",
            name="module_order",
            field=django.contrib.postgres.fields.ArrayField(
                base_field=models.CharField(max_length=500), default=list, size=None
            ),
        ),
        migrations.AlterField(
            model_name="apprelease",
            name="published",
            field=models.DateTimeField(
                blank=True,
                help_text="De publicatiedatum bepaalt vanaf wanneer de release niet meer als pre-release te zien is en de release in aanmerking komt voor voor gebruik als latest version in update meldingen.",
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="apprelease",
            name="unpublished",
            field=models.DateTimeField(
                blank=True,
                help_text="De ongepubliceerd datum bepaalt vanaf wanneer gebruikers van deze release een geforceerde update melding krijgen en de app voor deze gebruikers onbruikbaar is.",
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="releasemodulestatus",
            name="app_release",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT, to="modules.apprelease"
            ),
        ),
        migrations.AlterField(
            model_name="releasemodulestatus",
            name="module_version",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT, to="modules.moduleversion"
            ),
        ),
    ]
