# Generated by Django 5.1 on 2025-06-12 13:47

from django.contrib.postgres import fields
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("modules", "0007_save_module_version_status_sort_order"),
    ]

    operations = [
        migrations.AlterField(
            model_name="apprelease",
            name="module_order",
            field=fields.ArrayField(
                base_field=models.CharField(max_length=500),
                blank=True,
                null=True,
                size=None,
            ),
        ),
        migrations.AlterField(
            model_name="releasemodulestatus",
            name="sort_order",
            field=models.PositiveIntegerField(db_index=True),
        ),
        migrations.RemoveField(
            model_name="module",
            name="reason",
        ),
        migrations.RemoveField(
            model_name="releasemodulestatus",
            name="reason",
        ),
        migrations.AddField(
            model_name="module",
            name="app_reason",
            field=models.CharField(
                blank=True,
                help_text="Reason for the status change. Visible in the app.",
                max_length=500,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="module",
            name="fallback_url",
            field=models.URLField(
                blank=True,
                help_text="URL to redirect users to when the module is not available.",
                max_length=500,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="module",
            name="note",
            field=models.CharField(
                blank=True,
                help_text="Reason for the status change. Visible internally only.",
                max_length=500,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="releasemodulestatus",
            name="app_reason",
            field=models.CharField(
                blank=True,
                help_text="Reason for the status change. Visible in the app.",
                max_length=500,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="releasemodulestatus",
            name="fallback_url",
            field=models.URLField(
                blank=True,
                help_text="URL to redirect users to when the module is not available.",
                max_length=500,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="releasemodulestatus",
            name="note",
            field=models.CharField(
                blank=True,
                help_text="Reason for the status change. Visible internally only.",
                max_length=500,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="moduleversion",
            name="description",
            field=models.TextField(max_length=1000),
        ),
        migrations.AlterField(
            model_name="moduleversion",
            name="icon",
            field=models.CharField(
                choices=[
                    ("alert", "alert"),
                    ("announcement", "announcement"),
                    ("chat", "chat"),
                    ("chatting", "chatting"),
                    ("eye", "eye"),
                    ("facade", "facade"),
                    ("housing", "housing"),
                    ("info", "info"),
                    ("organic-waste-container", "organic-waste-container"),
                    ("construction-work", "construction-work"),
                    ("parking", "parking"),
                    ("trash-bin", "trash-bin"),
                    ("city-pass", "city-pass"),
                ],
                max_length=100,
            ),
        ),
    ]
