# Generated by Django 5.1 on 2025-06-19 16:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("modules", "0008_remove_apprelease_module_order"),
    ]

    operations = [
        migrations.AlterField(
            model_name="apprelease",
            name="created",
            field=models.DateTimeField(auto_now_add=True, verbose_name="Aangemaakt"),
        ),
        migrations.AlterField(
            model_name="apprelease",
            name="deprecated",
            field=models.DateTimeField(
                blank=True,
                help_text="De deprecateddatum bepaalt vanaf wanneer gebruikers van deze release een update suggestie melding krijgen.",
                null=True,
                verbose_name="Deprecated",
            ),
        ),
        migrations.AlterField(
            model_name="apprelease",
            name="modified",
            field=models.DateTimeField(auto_now=True, verbose_name="Laatste bewerking"),
        ),
        migrations.AlterField(
            model_name="apprelease",
            name="modules",
            field=models.ManyToManyField(
                through="modules.ReleaseModuleStatus",
                to="modules.moduleversion",
                verbose_name="Modules in deze release",
            ),
        ),
        migrations.AlterField(
            model_name="apprelease",
            name="published",
            field=models.DateTimeField(
                blank=True,
                help_text="De publicatiedatum bepaalt vanaf wanneer de release niet meer als pre-release te zien is en de release in aanmerking komt voor voor gebruik als latest version in update meldingen.",
                null=True,
                verbose_name="Gepubliceerd",
            ),
        ),
        migrations.AlterField(
            model_name="apprelease",
            name="unpublished",
            field=models.DateTimeField(
                blank=True,
                help_text="De ongepubliceerd datum bepaalt vanaf wanneer gebruikers van deze release een geforceerde update melding krijgen en de app voor deze gebruikers onbruikbaar is.",
                null=True,
                verbose_name="Ongepubliceerd",
            ),
        ),
        migrations.AlterField(
            model_name="apprelease",
            name="version",
            field=models.CharField(max_length=100, unique=True, verbose_name="Versie"),
        ),
        migrations.AlterField(
            model_name="module",
            name="app_reason",
            field=models.CharField(
                blank=True,
                help_text="Rede voor status wijziging. Zichtbaar in de app.",
                max_length=500,
                null=True,
                verbose_name="App reden",
            ),
        ),
        migrations.AlterField(
            model_name="module",
            name="fallback_url",
            field=models.URLField(
                blank=True,
                help_text="URL om als backup te gebruiken.",
                max_length=500,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="module",
            name="note",
            field=models.CharField(
                blank=True,
                help_text="Rede voor status wijziging. Alleen intern zichtbaar.",
                max_length=500,
                null=True,
                verbose_name="Notitie",
            ),
        ),
        migrations.AlterField(
            model_name="moduleversion",
            name="created",
            field=models.DateTimeField(auto_now_add=True, verbose_name="Aangemaakt"),
        ),
        migrations.AlterField(
            model_name="moduleversion",
            name="description",
            field=models.TextField(max_length=1000, verbose_name="Omschrijving"),
        ),
        migrations.AlterField(
            model_name="moduleversion",
            name="icon",
            field=models.CharField(
                choices=[
                    ("alert", "alert"),
                    ("announcement", "announcement"),
                    ("chat", "chat"),
                    ("chatting", "chatting"),
                    ("eye", "eye"),
                    ("facade", "facade"),
                    ("housing", "housing"),
                    ("info", "info"),
                    ("organic-waste-container", "organic-waste-container"),
                    ("construction-work", "construction-work"),
                    ("parking", "parking"),
                    ("trash-bin", "trash-bin"),
                    ("city-pass", "city-pass"),
                ],
                max_length=100,
                verbose_name="Icoon",
            ),
        ),
        migrations.AlterField(
            model_name="moduleversion",
            name="modified",
            field=models.DateTimeField(auto_now=True, verbose_name="Laatste wijziging"),
        ),
        migrations.AlterField(
            model_name="moduleversion",
            name="title",
            field=models.CharField(max_length=500, verbose_name="Titel"),
        ),
        migrations.AlterField(
            model_name="moduleversion",
            name="version",
            field=models.CharField(max_length=100, verbose_name="Versie"),
        ),
        migrations.AlterField(
            model_name="releasemodulestatus",
            name="app_reason",
            field=models.CharField(
                blank=True,
                help_text="Rede voor status wijziging. Zichtbaar in de app.",
                max_length=500,
                null=True,
                verbose_name="App reden",
            ),
        ),
        migrations.AlterField(
            model_name="releasemodulestatus",
            name="fallback_url",
            field=models.URLField(
                blank=True,
                help_text="URL om als backup te gebruiken.",
                max_length=500,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="releasemodulestatus",
            name="module_version",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                to="modules.moduleversion",
                verbose_name="Module versie",
            ),
        ),
        migrations.AlterField(
            model_name="releasemodulestatus",
            name="note",
            field=models.CharField(
                blank=True,
                help_text="Rede voor status wijziging. Alleen intern zichtbaar.",
                max_length=500,
                null=True,
                verbose_name="Notitie",
            ),
        ),
    ]
