# Generated by Django 5.1 on 2025-07-01 16:08

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        (
            "modules",
            "0009_alter_apprelease_created_alter_apprelease_deprecated_and_more",
        ),
    ]

    operations = [
        migrations.AlterField(
            model_name="releasemodulestatus",
            name="app_reason",
            field=models.CharField(
                blank=True, max_length=500, null=True, verbose_name="App reden"
            ),
        ),
        migrations.AlterField(
            model_name="releasemodulestatus",
            name="fallback_url",
            field=models.URLField(blank=True, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name="releasemodulestatus",
            name="note",
            field=models.CharField(
                blank=True, max_length=500, null=True, verbose_name="Notitie"
            ),
        ),
    ]
