# Generated by Django 5.1 on 2025-07-16 14:22

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("modules", "0010_alter_releasemodulestatus_app_reason_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="apprelease",
            name="release_notes",
            field=models.CharField(
                blank=True, default="*** No release notes provided ***", max_length=2000
            ),
            preserve_default=False,
        ),
    ]
