# Generated by Django 5.1 on 2025-11-25 14:58

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("modules", "0013_alter_moduleversion_icon"),
    ]

    operations = [
        migrations.AlterField(
            model_name="moduleversion",
            name="icon",
            field=models.CharField(
                choices=[
                    ("alert", "alert"),
                    ("announcement", "announcement"),
                    ("chat", "chat"),
                    ("chatting", "chatting"),
                    ("city-pass", "city-pass"),
                    ("eye", "eye"),
                    ("facade", "facade"),
                    ("fire", "fire"),
                    ("housing", "housing"),
                    ("info", "info"),
                    ("my-amsterdam", "my-amsterdam"),
                    ("organic-waste-container", "organic-waste-container"),
                    ("construction-work", "construction-work"),
                    ("parking", "parking"),
                    ("trash-bin", "trash-bin"),
                    ("trash-bag", "trash-bag"),
                    ("vote", "vote"),
                ],
                max_length=100,
                verbose_name="Icoon",
            ),
        ),
    ]
