# Generated by Django 5.1 on 2025-12-01 16:23

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("modules", "0014_alter_moduleversion_icon"),
    ]

    operations = [
        migrations.AddField(
            model_name="module",
            name="button_label",
            field=models.CharField(
                default="Bekijk op Amsterdam.nl",
                help_text="Label voor de knop die naar de fallback URL verwijst.",
                max_length=150,
                verbose_name="Knop label",
            ),
        ),
        migrations.AddField(
            model_name="releasemodulestatus",
            name="button_label",
            field=models.CharField(
                default="Bekijk op Amsterdam.nl",
                help_text="Label voor de knop die naar de fallback URL verwijst.",
                max_length=150,
                verbose_name="Knop label",
            ),
        ),
    ]
