# Generated by Django 5.1 on 2026-02-05 10:13

import core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('modules', '0015_module_button_label_releasemodulestatus_button_label'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Titel')),
                ('message', models.TextField(verbose_name='Bericht')),
                ('url', models.URLField(blank=True, null=True)),
                ('deeplink', models.CharField(blank=True, null=True, validators=[core.validators.AappDeeplinkValidator()])),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('send_at', models.DateTimeField(blank=True, null=True, verbose_name='Verstuurd op')),
                ('nr_sessions', models.PositiveIntegerField(default=0, editable=False, verbose_name='Aantal berichten verstuurd')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='notifications', to=settings.AUTH_USER_MODEL, verbose_name='Aangemaakt door')),
            ],
            options={
                'verbose_name': 'Notificatie',
                'verbose_name_plural': 'Notificaties',
            },
        ),
    ]
