# Generated by Django 5.1 on 2026-02-06 11:17

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("modules", "0016_notification"),
    ]

    operations = [
        migrations.AlterField(
            model_name="notification",
            name="nr_sessions",
            field=models.PositiveIntegerField(
                default=0, editable=False, verbose_name="Bereik"
            ),
        ),
        migrations.AlterField(
            model_name="notification",
            name="send_at",
            field=models.DateTimeField(
                blank=True, null=True, verbose_name="Versturen op"
            ),
        ),
    ]
