# Generated by Django 5.1 on 2026-02-09 14:12

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("modules", "0016_notification"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="TestDevice",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "device_id",
                    models.CharField(
                        max_length=255, unique=True, verbose_name="Device ID"
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        blank=True, max_length=255, null=True, verbose_name="Naam"
                    ),
                ),
            ],
            options={
                "verbose_name": "Test toestel",
                "verbose_name_plural": "Test toestellen",
            },
        ),
        migrations.AddField(
            model_name="notification",
            name="is_test",
            field=models.BooleanField(default=True, verbose_name="Test notificatie"),
        ),
        migrations.AlterField(
            model_name="notification",
            name="nr_sessions",
            field=models.PositiveIntegerField(
                default=0, editable=False, verbose_name="Bereik"
            ),
        ),
        migrations.AlterField(
            model_name="notification",
            name="send_at",
            field=models.DateTimeField(
                blank=True, null=True, verbose_name="Versturen op"
            ),
        ),
        migrations.AddConstraint(
            model_name="notification",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    ("url__isnull", True), ("deeplink__isnull", True), _connector="OR"
                ),
                name="url_and_deeplink_mutually_exclusive",
            ),
        ),
    ]
