# Generated by Django 5.1 on 2026-03-04 11:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('modules', '0017_testdevice_notification_is_test_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='moduleversion',
            name='icon',
            field=models.CharField(choices=[('alert', 'alert'), ('announcement', 'announcement'), ('chat', 'chat'), ('chatting', 'chatting'), ('city-pass', 'city-pass'), ('eye', 'eye'), ('facade', 'facade'), ('fire', 'fire'), ('housing', 'housing'), ('info', 'info'), ('map-marker-on-map', 'map-marker-on-map'), ('my-amsterdam', 'my-amsterdam'), ('organic-waste-container', 'organic-waste-container'), ('construction-work', 'construction-work'), ('parking', 'parking'), ('trash-bin', 'trash-bin'), ('trash-bag', 'trash-bag'), ('vote', 'vote')], max_length=100, verbose_name='Icoon'),
        ),
    ]
