# Generated by Django 6.0.3 on 2026-04-07 14:31

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("modules", "0018_alter_moduleversion_icon"),
    ]

    operations = [
        migrations.AlterField(
            model_name="apprelease",
            name="modules",
            field=models.ManyToManyField(
                through="modules.ReleaseModuleStatus",
                through_fields=("app_release", "module_version"),
                to="modules.moduleversion",
                verbose_name="Modules in deze release",
            ),
        ),
    ]
