# Generated by Django 6.0.5 on 2026-07-14 07:59

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("modules", "0023_alter_moduleversion_icon"),
    ]

    operations = [
        migrations.AddField(
            model_name="module",
            name="is_mams_theme",
            field=models.BooleanField(
                default=False,
                help_text="Geeft aan of dit een thema van Mijn Amsterdam is.",
                verbose_name="Mijn Amsterdam thema",
            ),
        ),
    ]
