# Generated by Django 6.0.5 on 2026-07-14 08:56

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("modules", "0024_module_is_mams_theme"),
    ]

    operations = [
        migrations.AlterField(
            model_name="moduleversion",
            name="icon",
            field=models.CharField(
                choices=[
                    ("alert", "alert"),
                    ("announcement", "announcement"),
                    ("boat-charging", "boat-charging"),
                    ("chat", "chat"),
                    ("chatting", "chatting"),
                    ("city-pass", "city-pass"),
                    ("crown", "crown"),
                    ("document", "document"),
                    ("eye", "eye"),
                    ("fire", "fire"),
                    ("house", "house"),
                    ("info", "info"),
                    ("mams-income", "mams-income"),
                    ("mams-invoices", "mams-invoices"),
                    ("map-marker-on-map", "map-marker-on-map"),
                    ("my-amsterdam", "my-amsterdam"),
                    ("newspaper", "newspaper"),
                    ("construction-work", "construction-work"),
                    ("parking", "parking"),
                    ("trash-bin", "trash-bin"),
                    ("trash-bag", "trash-bag"),
                    ("vote", "vote"),
                ],
                max_length=100,
                verbose_name="Icoon",
            ),
        ),
    ]
