# Generated by Django 4.2.15 on 2024-11-04 18:18

import uuid

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Client",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("external_id", models.CharField(max_length=1000, unique=True)),
                ("os", models.CharField()),
                ("firebase_token", models.CharField(max_length=1000, null=True)),
                ("receive_push", models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name="Notification",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("title", models.CharField(max_length=1000)),
                ("body", models.CharField(max_length=1000)),
                ("module_slug", models.CharField()),
                ("context", models.JSONField()),
                ("client_id", models.CharField(null=True)),
                ("created_at", models.DateTimeField()),
                ("pushed_at", models.DateTimeField(auto_now_add=True)),
                ("is_read", models.BooleanField(default=False)),
            ],
        ),
    ]
