# Generated by Django 4.2.16 on 2024-11-18 14:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("notification", "0002_remove_client_receive_push"),
    ]

    operations = [
        migrations.RenameField(
            model_name="notification",
            old_name="client_id",
            new_name="client",
        ),
        migrations.AlterField(
            model_name="notification",
            name="client",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="notification.client"
            ),
        ),
    ]
