# Generated by Django 4.2.16 on 2024-11-20 11:11

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("notification", "0004_configure_timescaledb"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="Client",
            new_name="Device",
        ),
        migrations.RenameField(
            model_name="notification",
            old_name="client",
            new_name="device",
        ),
    ]
