# Generated by Django 4.2.17 on 2025-01-22 14:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("notification", "0006_imagevariant_imageset_notification_image_set"),
    ]

    operations = [
        migrations.RenameField(
            model_name="imageset",
            old_name="firebase_image",
            new_name="image_small",
        ),
        migrations.RenameField(
            model_name="imageset",
            old_name="thumbnail_image",
            new_name="image_medium",
        ),
        migrations.RenameField(
            model_name="imageset",
            old_name="large_image",
            new_name="image_large",
        ),
    ]
