# Generated by Django 4.2.17 on 2025-01-30 15:41

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("notification", "0007_rename_large_image_imageset_image_large_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="notification",
            name="image_set",
        ),
        migrations.AddField(
            model_name="notification",
            name="image",
            field=models.IntegerField(default=None, null=True),
        ),
        migrations.DeleteModel(
            name="ImageSet",
        ),
        migrations.DeleteModel(
            name="ImageVariant",
        ),
    ]
