# Generated by Django 4.2.18 on 2025-03-06 14:53

import uuid

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("notification", "0009_notification_notification_type_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="notificationpushserviceenabled",
            name="service_name",
            field=models.CharField(
                choices=[("construction-work", "CONSTRUCTION_WORK")]
            ),
        ),
        migrations.CreateModel(
            name="ScheduledNotification",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("title", models.CharField(max_length=1000)),
                ("body", models.CharField(max_length=1000)),
                ("module_slug", models.CharField()),
                ("context", models.JSONField()),
                ("notification_type", models.CharField()),
                ("image", models.IntegerField(default=None, null=True)),
                ("created_at", models.DateTimeField()),
                ("identifier", models.CharField()),
                ("scheduled_for", models.DateTimeField()),
                (
                    "device_ids",
                    models.ManyToManyField(
                        related_name="scheduled_notifications", to="notification.device"
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="notification",
            name="schedule",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="notification.schedulednotification",
            ),
        ),
        migrations.AddConstraint(
            model_name="schedulednotification",
            constraint=models.UniqueConstraint(
                fields=("identifier",), name="unique_identifier"
            ),
        ),
    ]
