# Generated by Django 4.2.18 on 2025-03-11 10:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "notification",
            "0010_alter_notificationpushserviceenabled_service_name_and_more",
        ),
    ]

    operations = [
        migrations.AddField(
            model_name="schedulednotification",
            name="pushed_at",
            field=models.DateTimeField(null=True),
        ),
    ]
