# Generated by Django 4.2.18 on 2025-03-12 09:01

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("notification", "0011_schedulednotification_pushed_at"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="NotificationPushTypeEnabled",
            new_name="NotificationPushTypeDisabled",
        ),
        migrations.RenameModel(
            old_name="NotificationPushServiceEnabled",
            new_name="NotificationPushModuleDisabled",
        ),
        migrations.RenameField(
            model_name="notificationpushmoduledisabled",
            old_name="service_name",
            new_name="module_slug",
        ),
        migrations.AlterField(
            model_name="notificationpushmoduledisabled",
            name="module_slug",
            field=models.CharField(),
        ),
        migrations.RenameField(
            model_name="schedulednotification",
            old_name="device_ids",
            new_name="devices",
        ),
    ]
