# Generated by Django 5.2 on 2025-04-30 13:29

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("notification", "0012_notificationpushtypedisabled_and_more"),
    ]

    operations = [
        migrations.AddIndex(
            model_name="notification",
            index=models.Index(
                fields=["module_slug"], name="notificatio_module__ed45a2_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="notification",
            index=models.Index(
                fields=["notification_type"], name="notificatio_notific_a5f01d_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="notification",
            index=models.Index(
                fields=["created_at"], name="notificatio_created_fcd7aa_idx"
            ),
        ),
    ]
