# Generated by Django 5.2 on 2025-05-01 11:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("notification", "0013_notification_notificatio_module__ed45a2_idx_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="notification",
            name="schedule",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                to="notification.schedulednotification",
            ),
        ),
        migrations.CreateModel(
            name="NotificationLast",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("module_slug", models.CharField()),
                ("notification_scope", models.CharField()),
                ("last_create", models.DateTimeField(auto_now=True)),
                (
                    "device",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="notification.device",
                    ),
                ),
            ],
            options={
                "indexes": [
                    models.Index(
                        fields=["device", "module_slug"],
                        name="notificatio_device__720af4_idx",
                    )
                ],
                "unique_together": {("device", "notification_scope")},
            },
        ),
    ]
