# Generated by Django 5.2 on 2025-05-01 14:55

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("notification", "0014_alter_notification_schedule_notificationlast"),
    ]

    operations = [
        migrations.AlterField(
            model_name="notification",
            name="pushed_at",
            field=models.DateTimeField(null=True),
        ),
    ]
