# Generated by Django 5.2.3 on 2025-06-25 14:40

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("notification", "0015_alter_notification_pushed_at"),
    ]

    operations = [
        migrations.AddIndex(
            model_name="schedulednotification",
            index=models.Index(
                fields=["module_slug"], name="notificatio_module__5587aa_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="schedulednotification",
            index=models.Index(
                fields=["notification_type"], name="notificatio_notific_7d1a17_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="schedulednotification",
            index=models.Index(
                fields=["created_at"], name="notificatio_created_a458be_idx"
            ),
        ),
    ]
