# Generated by Django 5.1 on 2025-07-07 10:09

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        (
            "notification",
            "0016_schedulednotification_notificatio_module__5587aa_idx_and_more",
        ),
    ]

    operations = [
        migrations.AddField(
            model_name="schedulednotification",
            name="expires_at",
            field=models.DateTimeField(default="3000-01-01"),
        ),
        migrations.AddIndex(
            model_name="schedulednotification",
            index=models.Index(
                condition=models.Q(("pushed_at__isnull", True)),
                fields=["scheduled_for"],
                name="idx_notif_sched_for_unpushed",
            ),
        ),
    ]
