# Generated by Django 5.1 on 2025-07-31 13:16

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("notification", "0017_schedulednotification_expires_at_and_more"),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name="schedulednotification",
            name="idx_notif_sched_for_unpushed",
        ),
        migrations.RemoveField(
            model_name="notification",
            name="schedule",
        ),
        migrations.RunSQL(
            "delete from notification_schedulednotification ns where pushed_at is not null;"
        ),
    ]
