# Generated by Django 5.1 on 2025-07-31 13:16

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("notification", "0017_schedulednotification_expires_at_and_more"),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name="schedulednotification",
            name="idx_notif_sched_for_unpushed",
        ),
        migrations.RemoveField(
            model_name="notification",
            name="schedule",
        ),
        migrations.RemoveField(
            model_name="schedulednotification",
            name="pushed_at",
        ),
        migrations.AddIndex(
            model_name="schedulednotification",
            index=models.Index(
                fields=["scheduled_for"], name="notificatio_schedul_9eff1f_idx"
            ),
        ),
    ]
