# Generated by Django 5.1 on 2025-08-13 08:51

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        (
            "notification",
            "0019_remove_schedulednotification_idx_notif_sched_for_unpushed_and_more",
        ),
    ]

    operations = [
        migrations.AddConstraint(
            model_name="schedulednotification",
            constraint=models.CheckConstraint(
                condition=models.Q(("expires_at__gt", models.F("scheduled_for"))),
                name="expires_after_scheduled_for",
            ),
        ),
    ]
