# Generated by Django 5.1 on 2025-08-26 09:22

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("notification", "0020_schedulednotification_expires_after_scheduled_for"),
    ]

    operations = [
        migrations.AddField(
            model_name="notification",
            name="device_external_id",
            field=models.CharField(max_length=1000, null=True),
        ),
        migrations.AddIndex(
            model_name="notification",
            index=models.Index(
                fields=["device_external_id"], name="notificatio_device__b04bb6_idx"
            ),
        ),
        migrations.RunSQL(
            "UPDATE notification_notification nn SET device_external_id = d.external_id "
            "FROM notification_device d WHERE nn.device_id = d.id"
        ),
        migrations.AlterField(
            model_name="notification",
            name="device_external_id",
            field=models.CharField(max_length=1000),
        ),
    ]
