# Generated by Django 5.1 on 2025-08-27 09:18

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("notification", "0021_notification_device_external_id_and_more"),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="notificationpushmoduledisabled",
            unique_together={("device", "module_slug")},
        ),
        migrations.AlterUniqueTogether(
            name="notificationpushtypedisabled",
            unique_together={("device", "notification_type")},
        ),
    ]
