# Generated by Django 5.1 on 2025-08-26 09:22

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("notification", "0023_disable_timescaledb"),
    ]

    operations = [
        migrations.RunSQL(
            "UPDATE notification_notification nn SET device_external_id = d.external_id "
            "FROM notification_device d WHERE nn.device_id = d.id",
            reverse_sql="",
        )
    ]
