# Generated by Django 5.1 on 2025-11-04 13:51

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("notification", "0024_notification_device_external_id_fix"),
    ]

    operations = [
        migrations.AddField(
            model_name="schedulednotification",
            name="make_push",
            field=models.BooleanField(default=True),
        ),
    ]
