# Generated by Django 5.1 on 2026-02-09 13:33

from django.db import migrations, models

import core.validators


class Migration(migrations.Migration):
    dependencies = [
        ("notification", "0025_schedulednotification_make_push"),
    ]

    operations = [
        migrations.AlterField(
            model_name="notification",
            name="context",
            field=models.JSONField(validators=[core.validators.context_validator]),
        ),
        migrations.AlterField(
            model_name="schedulednotification",
            name="context",
            field=models.JSONField(validators=[core.validators.context_validator]),
        ),
    ]
