# Generated by Django 5.1 on 2026-02-25 13:42

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        (
            "notification",
            "0026_alter_notification_context_alter_notification_image_and_more",
        ),
    ]

    operations = [
        migrations.AddField(
            model_name="device",
            name="last_seen",
            field=models.DateTimeField(auto_now=True),
        ),
    ]
