# Generated by Django 5.1 on 2026-02-16 08:50

from django.db import migrations, models

import core.validators


class Migration(migrations.Migration):
    dependencies = [
        (
            "notification",
            "0026_alter_notification_context_alter_notification_image_and_more",
        ),
    ]

    operations = [
        migrations.AlterField(
            model_name="notification",
            name="context",
            field=models.JSONField(validators=[core.validators.context_validator]),
        ),
        migrations.AlterField(
            model_name="schedulednotification",
            name="context",
            field=models.JSONField(validators=[core.validators.context_validator]),
        ),
    ]
