# Generated by Django 5.1 on 2026-03-13 11:41

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("notification", "0027_device_last_seen"),
    ]

    operations = [
        migrations.CreateModel(
            name="WasteNotification",
            fields=[
                (
                    "device_id",
                    models.CharField(max_length=255, primary_key=True, serialize=False),
                ),
                (
                    "bag_nummeraanduiding_id",
                    models.CharField(max_length=255, null=True),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(null=True)),
            ],
        ),
    ]
