# Generated by Django 5.1 on 2026-03-11 16:50

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("notification", "0027_device_last_seen"),
    ]

    operations = [
        migrations.AlterField(
            model_name="notificationlast",
            name="last_create",
            field=models.DateTimeField(),
        ),
    ]
