# Generated by Django 5.1 on 2026-03-17 17:06

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("notification", "0028_alter_notificationlast_last_create"),
    ]

    operations = [
        migrations.AddField(
            model_name="schedulednotification",
            name="is_ready",
            field=models.BooleanField(default=False),
        ),
    ]
