# Generated by Django 5.1 on 2026-03-20 15:27

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("notification", "0030_wastedevice"),
    ]

    operations = [
        migrations.CreateModel(
            name="BurningGuideDevice",
            fields=[
                (
                    "device_id",
                    models.CharField(max_length=255, primary_key=True, serialize=False),
                ),
                ("postal_code", models.CharField(max_length=4)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("send_at", models.DateTimeField(null=True)),
            ],
        ),
    ]
