# Generated by Django 5.1 on 2026-03-23 14:53

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("notification", "0031_burningguidedevice"),
    ]

    operations = [
        migrations.AlterField(
            model_name="burningguidedevice",
            name="postal_code",
            field=models.CharField(max_length=4, null=True),
        ),
    ]
