# Generated by Django 6.0.4 on 2026-04-23 08:52

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("notification", "0032_alter_burningguidedevice_postal_code"),
    ]

    operations = [
        migrations.AddField(
            model_name="notification",
            name="is_visible",
            field=models.BooleanField(default=True),
        ),
    ]
