# Generated by Django 6.0.5 on 2026-06-26 12:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("notification", "0034_device_cascade_for_service_device_records"),
    ]

    operations = [
        migrations.CreateModel(
            name="BoatChargingDevice",
            fields=[
                (
                    "device",
                    models.OneToOneField(
                        db_column="device_id",
                        on_delete=django.db.models.deletion.CASCADE,
                        primary_key=True,
                        related_name="boat_charging_device",
                        serialize=False,
                        to="notification.device",
                        to_field="external_id",
                    ),
                ),
                ("session_id", models.CharField(max_length=255, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("sent_notifications", models.JSONField(default=dict)),
            ],
        ),
    ]
