# Generated by Django 6.0.5 on 2026-07-01 13:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("notification", "0034_device_cascade_for_service_device_records"),
    ]

    operations = [
        migrations.CreateModel(
            name="BoatChargingSession",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("session_id", models.CharField(max_length=255)),
                ("first_send_at", models.DateTimeField(null=True)),
                ("second_send_at", models.DateTimeField(null=True)),
                ("last_send_at", models.DateTimeField(null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "device",
                    models.ForeignKey(
                        db_column="device_id",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="boat_charging_session",
                        to="notification.device",
                        to_field="external_id",
                    ),
                ),
            ],
        ),
    ]
