# Generated by Django 6.0.5 on 2026-07-06 08:33

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("notification", "0035_boatchargingsession"),
    ]

    operations = [
        migrations.AddField(
            model_name="boatchargingsession",
            name="deleted",
            field=models.BooleanField(default=False),
        ),
    ]
