# Generated by Django 6.1 on 2026-08-27 08:37

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("notification", "0036_boatchargingsession_deleted"),
    ]

    operations = [
        migrations.AddField(
            model_name="wastedevice",
            name="postal_area",
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="wastedevice",
            name="route_name_bulk",
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="wastedevice",
            name="route_name_glas",
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="wastedevice",
            name="route_name_organic",
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="wastedevice",
            name="route_name_paper",
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="wastedevice",
            name="route_name_plastic",
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="wastedevice",
            name="route_name_residual",
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="wastedevice",
            name="route_name_textile",
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="wastedevice",
            name="routes_updated_at",
            field=models.DateTimeField(null=True),
        ),
    ]
