# Generated by Django 6.0.5 on 2026-07-09 15:04

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("notification", "0036_boatchargingsession_deleted"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="wastedevice",
            name="device",
        ),
        migrations.DeleteModel(
            name="BurningGuideDevice",
        ),
        migrations.DeleteModel(
            name="WasteDevice",
        ),
    ]
