# Generated by Django 4.2.14 on 2024-07-24 10:07

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("city_pass", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="refreshtoken",
            name="expires_at",
            field=models.DateTimeField(null=True),
        ),
    ]
