# Generated by Django 4.2.14 on 2024-08-13 07:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("city_pass", "0002_refreshtoken_expires_at"),
    ]

    operations = [
        migrations.CreateModel(
            name="PassData",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("pass_number", models.BigIntegerField()),
                ("encrypted_transaction_key", models.CharField()),
                (
                    "session",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="city_pass.session",
                    ),
                ),
            ],
        ),
    ]
