# Generated by Django 4.2.15 on 2024-08-14 11:31

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("city_pass", "0003_passdata"),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="passdata",
            unique_together={("pass_number", "session")},
        ),
    ]
