# Generated by Django 4.2.15 on 2024-08-14 14:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('city_pass', '0004_alter_passdata_unique_together'),
    ]

    operations = [
        migrations.AlterField(
            model_name='passdata',
            name='pass_number',
            field=models.CharField(),
        ),
    ]
