# Generated by Django 5.2.3 on 2025-06-18 12:43

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("city_pass", "0005_alter_passdata_pass_number"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Budget",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("code", models.CharField(max_length=255, unique=True)),
                ("title", models.CharField(max_length=255, verbose_name="Titel")),
                (
                    "description",
                    models.TextField(
                        blank=True, null=True, verbose_name="Omschrijving"
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Aangemaakt op"
                    ),
                ),
            ],
            options={
                "verbose_name": "Budget",
                "verbose_name_plural": "Budgetten",
            },
        ),
        migrations.AddField(
            model_name="session",
            name="device_id",
            field=models.CharField(max_length=255, null=True, unique=True),
        ),
        migrations.AddField(
            model_name="passdata",
            name="budgets",
            field=models.ManyToManyField(
                blank=True, to="city_pass.budget", verbose_name="Budgetten"
            ),
        ),
        migrations.CreateModel(
            name="Notification",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=255, verbose_name="Titel")),
                ("message", models.TextField(verbose_name="Bericht")),
                ("url", models.URLField(blank=True, null=True)),
                (
                    "image",
                    models.ImageField(
                        blank=True,
                        null=True,
                        upload_to="city-pass/media/",
                        verbose_name="Afbeelding",
                    ),
                ),
                (
                    "image_description",
                    models.CharField(
                        blank=True,
                        max_length=255,
                        null=True,
                        verbose_name="Afbeelding omschrijving",
                    ),
                ),
                (
                    "image_set_id",
                    models.CharField(
                        blank=True,
                        max_length=255,
                        null=True,
                        verbose_name="Image Set ID",
                    ),
                ),
                (
                    "send_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Verstuurd op"
                    ),
                ),
                (
                    "nr_sessions",
                    models.PositiveIntegerField(
                        default=0,
                        editable=False,
                        verbose_name="Aantal berichten verstuurd",
                    ),
                ),
                (
                    "budgets",
                    models.ManyToManyField(
                        blank=True, to="city_pass.budget", verbose_name="Budgetten"
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="notifications",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Aangemaakt door",
                    ),
                ),
            ],
            options={
                "verbose_name": "Notificatie",
                "verbose_name_plural": "Notificaties",
            },
        ),
    ]
