# Generated by Django 5.1 on 2025-12-11 09:46

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("city_pass", "0006_budget_session_device_id_passdata_budgets_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="notification",
            name="title",
            field=models.CharField(
                default="Stadspas", max_length=255, verbose_name="Titel"
            ),
        ),
    ]
