# Generated by Django 6.0.5 on 2026-07-09 15:04

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("city_pass", "0007_alter_notification_title"),
    ]

    operations = [
        migrations.AddField(
            model_name="session",
            name="device_id_internal",
            field=models.CharField(max_length=255, null=True, unique=True),
        ),
    ]
