# Generated by Django 4.2.4 on 2024-05-07 10:08

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("construction_work", "0007_delete_asset"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="projectmanager",
            name="manager_key",
        ),
        migrations.AddField(
            model_name="projectmanager",
            name="name",
            field=models.CharField(default="unknown", max_length=1000),
            preserve_default=False,
        ),
    ]
