# Generated by Django 4.2.13 on 2024-05-08 14:53

from django.db import migrations, models

from construction_work.validators import AmsterdamEmailValidator


class Migration(migrations.Migration):
    dependencies = [
        ("construction_work", "0008_remove_projectmanager_manager_key_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="projectmanager",
            name="email",
            field=models.EmailField(
                max_length=254,
                unique=True,
                validators=[AmsterdamEmailValidator()],
            ),
        ),
    ]
