# Generated by Django 4.2.13 on 2024-05-22 14:41

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("construction_work", "0009_alter_projectmanager_email"),
    ]

    operations = [
        migrations.AddField(
            model_name="project",
            name="hidden",
            field=models.BooleanField(blank=True, default=False),
        ),
    ]
