# Generated by Django 4.2.13 on 2024-06-17 13:56

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("construction_work", "0010_project_hidden"),
    ]

    operations = [
        migrations.AddField(
            model_name="image",
            name="image",
            field=models.ImageField(blank=True, null=True, upload_to="images/"),
        ),
    ]
