# Generated by Django 4.2.13 on 2024-06-17 13:56

import io
import logging

from django.core.files.base import ContentFile
from django.db import migrations
from PIL import Image

logger = logging.getLogger(__name__)


def migrate_binary_to_image(apps, schema_editor):
    ImageModel = apps.get_model("construction_work", "Image")
    image_count = ImageModel.objects.all().count()
    logger.debug(f"Amount of images in database: {image_count}")

    for instance in ImageModel.objects.all():
        if not instance.data:
            instance.remove()
            logger.debug(
                f"Image had no data, so was removed from database [{instance.pk=}]"
            )

        # Convert binary data to image
        image = Image.open(io.BytesIO(instance.data))
        image_io = io.BytesIO()
        image.save(image_io, format="JPEG")
        instance.image.save(
            f"warning-image-{instance.pk}.jpg",
            ContentFile(image_io.getvalue()),
        )
        logger.debug(
            f"Image succesfully migrated [{instance.pk=}, {instance.image.name=}]"
        )

    logger.debug(f"Finished migration of all images to blob storage [{image_count=}]")


def reverse_migrate_binary_to_image(apps, schema_editor):
    ImageModel = apps.get_model("construction_work", "Image")
    for instance in ImageModel.objects.all():
        if instance.image:
            instance.image.delete(save=False)
            instance.image = None
            instance.save()


class Migration(migrations.Migration):
    dependencies = [
        ("construction_work", "0011_image_image"),
    ]

    operations = [
        migrations.RunPython(migrate_binary_to_image, reverse_migrate_binary_to_image),
    ]
