# Generated by Django 4.2.13 on 2024-06-17 14:05

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("construction_work", "0012_migrate_binary_to_image"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="image",
            name="data",
        ),
    ]
