# Generated by Django 4.2.13 on 2024-06-18 10:16

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("construction_work", "0013_remove_image_data"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="image",
            name="coordinates",
        ),
        migrations.RemoveField(
            model_name="image",
            name="mime_type",
        ),
    ]
