# Generated by Django 4.2.15 on 2024-10-22 12:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("construction_work", "0014_remove_image_coordinates_remove_image_mime_type"),
    ]

    operations = [
        migrations.AlterField(
            model_name="warningimage",
            name="warning",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="construction_work.warningmessage",
            ),
        ),
    ]
