# Generated by Django 4.2.16 on 2024-11-07 14:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("construction_work", "0014_remove_image_coordinates_remove_image_mime_type"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="image",
            name="aspect_ratio",
        ),
        migrations.RemoveField(
            model_name="warningimage",
            name="is_main",
        ),
        migrations.AlterField(
            model_name="warningimage",
            name="warning",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="construction_work.warningmessage",
            ),
        ),
    ]
