# Generated by Django 4.2.16 on 2024-11-11 13:29

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("construction_work", "0015_remove_image_aspect_ratio_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="warningmessage",
            name="notification_sent",
            field=models.BooleanField(default=False),
        ),
        migrations.DeleteModel(
            name="Notification",
        ),
    ]
