# Generated by Django 4.2.16 on 2024-12-05 16:52

import uuid

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "construction_work",
            "0016_warningmessage_notification_sent_delete_notification",
        ),
    ]

    operations = [
        migrations.CreateModel(
            name="ArticleImage",
            fields=[
                ("id", models.IntegerField(primary_key=True, serialize=False)),
                ("aspectRatio", models.FloatField()),
                ("alternativeText", models.CharField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name="ProjectImage",
            fields=[
                ("id", models.IntegerField(primary_key=True, serialize=False)),
                ("aspectRatio", models.FloatField()),
                ("alternativeText", models.CharField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name="ProjectSection",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("body", models.CharField(blank=True, null=True)),
                ("title", models.CharField()),
                (
                    "type",
                    models.CharField(
                        choices=[
                            ("what", "what"),
                            ("when", "when"),
                            ("work", "work"),
                            ("contact", "contact"),
                        ],
                        max_length=10,
                    ),
                ),
            ],
        ),
        migrations.RemoveField(
            model_name="article",
            name="image",
        ),
        migrations.RemoveField(
            model_name="project",
            name="contacts",
        ),
        migrations.RemoveField(
            model_name="project",
            name="coordinates",
        ),
        migrations.RemoveField(
            model_name="project",
            name="image",
        ),
        migrations.RemoveField(
            model_name="project",
            name="images",
        ),
        migrations.RemoveField(
            model_name="project",
            name="sections",
        ),
        migrations.RemoveField(
            model_name="project",
            name="timeline",
        ),
        migrations.AddField(
            model_name="project",
            name="coordinates_lat",
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="project",
            name="coordinates_lon",
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="project",
            name="timeline_intro",
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
        migrations.AddField(
            model_name="project",
            name="timeline_title",
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
        migrations.AlterField(
            model_name="article",
            name="publication_date",
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name="article",
            name="title",
            field=models.CharField(db_index=True, max_length=1000),
        ),
        migrations.AlterField(
            model_name="article",
            name="url",
            field=models.URLField(max_length=2048),
        ),
        migrations.AlterField(
            model_name="project",
            name="active",
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name="project",
            name="hidden",
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name="project",
            name="last_seen",
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name="project",
            name="subtitle",
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
        migrations.AlterField(
            model_name="project",
            name="title",
            field=models.CharField(db_index=True, max_length=1000),
        ),
        migrations.AlterField(
            model_name="project",
            name="url",
            field=models.URLField(max_length=2048),
        ),
        migrations.CreateModel(
            name="ProjectTimelineItem",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("title", models.CharField(blank=True, null=True)),
                ("body", models.CharField(blank=True, null=True)),
                ("collapsed", models.BooleanField(blank=True, null=True)),
                (
                    "parent",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="items",
                        to="construction_work.projecttimelineitem",
                    ),
                ),
                (
                    "project",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="timeline_items",
                        to="construction_work.project",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="ProjectSectionUrl",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("url", models.CharField()),
                ("label", models.CharField()),
                (
                    "section",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="links",
                        to="construction_work.projectsection",
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="projectsection",
            name="project",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="sections",
                to="construction_work.project",
            ),
        ),
        migrations.CreateModel(
            name="ProjectImageSource",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("uri", models.CharField(unique=True)),
                ("width", models.IntegerField()),
                ("height", models.IntegerField()),
                (
                    "image",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="sources",
                        to="construction_work.projectimage",
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="projectimage",
            name="parent",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="image",
                to="construction_work.project",
            ),
        ),
        migrations.CreateModel(
            name="ProjectContact",
            fields=[
                ("id", models.FloatField(primary_key=True, serialize=False)),
                ("name", models.CharField(blank=True, null=True)),
                ("email", models.CharField(blank=True, null=True)),
                ("phone", models.CharField(blank=True, null=True)),
                ("position", models.CharField(blank=True, null=True)),
                (
                    "project",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="contacts",
                        to="construction_work.project",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="ArticleImageSource",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("uri", models.CharField()),
                ("width", models.IntegerField()),
                ("height", models.IntegerField()),
                (
                    "image",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="sources",
                        to="construction_work.articleimage",
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="articleimage",
            name="parent",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="image",
                to="construction_work.article",
            ),
        ),
        migrations.AlterField(
            model_name="projectimagesource",
            name="uri",
            field=models.CharField(),
        ),
        migrations.AlterField(
            model_name="projectsection",
            name="type",
            field=models.CharField(
                choices=[
                    ("where", "where"),
                    ("what", "what"),
                    ("when", "when"),
                    ("work", "work"),
                    ("contact", "contact"),
                ],
                max_length=10,
            ),
        ),
    ]
