# Generated by Django 4.2.17 on 2025-02-04 16:03

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("construction_work", "0017_articleimage_projectimage_projectsection_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="image",
            name="image",
            field=models.ImageField(
                blank=True, null=True, upload_to="construction-work/images/"
            ),
        ),
    ]
