# Generated by Django 4.2.18 on 2025-03-04 14:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("construction_work", "0018_alter_image_image"),
    ]

    operations = [
        migrations.AddField(
            model_name="image",
            name="warning_image",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="construction_work.warningimage",
            ),
        ),
        migrations.RunSQL(
            """
        update construction_work_image cwi 
        set warning_image_id = cwwi.warningimage_id
        from construction_work_warningimage_images cwwi 
        where cwi.id = cwwi.image_id;
        """
        ),
        migrations.AlterField(
            model_name="image",
            name="warning_image",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to="construction_work.warningimage",
            ),
        ),
        migrations.RemoveField(
            model_name="warningimage",
            name="images",
        ),
    ]
