# Generated by Django 4.2.18 on 2025-03-05 11:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("construction_work", "0019_image_warning_image"),
    ]

    operations = [
        migrations.AddField(
            model_name="warningimage",
            name="image_set_id",
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name="image",
            name="image",
            field=models.URLField(),
        ),
    ]
