# Generated by Django 5.2 on 2025-05-01 11:23

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("construction_work", "0020_warningimage_image_set_id_alter_image_image"),
    ]

    operations = [
        migrations.AddField(
            model_name="articleimage",
            name="image_set",
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="projectimage",
            name="image_set",
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
