# Generated by Django 5.1 on 2026-03-26 15:13

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("construction_work", "0021_articleimage_image_set_projectimage_image_set"),
    ]

    operations = [
        migrations.AddField(
            model_name="projectcontact",
            name="extra",
            field=models.CharField(blank=True, null=True),
        ),
    ]
