MOCK_DATA = {
    "type": "FeatureCollection",
    "features": [
        {
            "type": "Feature",
            "geometry": {"type": "Point", "coordinates": [4.89274394, 52.37107917]},
            "properties": {
                "id": "12624938",
                "title": "Rokin (gemeente)",
                "description": "Niet geopend op Koningsdag",
                "street": "Rokin",
                "street_number": "67",
                "zip": "1012KK",
                "city": "Amsterdam",
                "meta": [],
            },
        },
        {
            "type": "Feature",
            "geometry": {"type": "Point", "coordinates": [4.89404573, 52.37679018]},
            "properties": {
                "id": "12624941",
                "title": "Q-park Nieuwezijds Kolk",
                "description": "Niet geopend op Koningsdag",
                "street": "Nieuwezijds Voorburgwal",
                "street_number": "40",
                "zip": "1012SB",
                "city": "Amsterdam",
                "meta": [],
            },
        },
        {
            "type": "Feature",
            "geometry": {"type": "Point", "coordinates": [4.89516483, 52.37387383]},
            "properties": {
                "id": "12624944",
                "title": "Q-park Bijenkorf",
                "description": "Niet geopend op Koningsdag",
                "street": "Q-park Bijenkorf",
                "street_number": "15",
                "zip": "1012JW",
                "city": "Amsterdam",
                "meta": [],
            },
        },
        {
            "type": "Feature",
            "geometry": {"type": "Point", "coordinates": [4.89678461, 52.37884542]},
            "properties": {
                "id": "12624947",
                "title": "Q-park P 1 (CS)",
                "description": "Niet geopend op Koningsdag",
                "street": "Prins Hendrikkade",
                "street_number": "20A",
                "zip": "1012TL",
                "city": "Amsterdam",
                "meta": [],
            },
        },
        {
            "type": "Feature",
            "geometry": {"type": "Point", "coordinates": [4.87672199, 52.36993104]},
            "properties": {
                "id": "12624950",
                "title": "Q-park Europarking, Marnixstraat",
                "description": "Niet geopend op Koningsdag",
                "street": "Marnixstraat",
                "street_number": "250",
                "zip": "1016TL",
                "city": "Amsterdam",
                "meta": [],
            },
        },
        {
            "type": "Feature",
            "geometry": {"type": "Point", "coordinates": [4.88000013, 52.36190111]},
            "properties": {
                "id": "12624953",
                "title": "Q-park Byzantium",
                "description": "Niet geopend op Koningsdag",
                "street": "Tesselschadestraat",
                "street_number": "1G",
                "zip": "1054ET",
                "city": "Amsterdam",
                "meta": [],
            },
        },
        {
            "type": "Feature",
            "geometry": {"type": "Point", "coordinates": [4.8907596, 52.36729441]},
            "properties": {
                "id": "12624956",
                "title": "Q-park Kalverstraat",
                "description": "Niet geopend op Koningsdag",
                "street": "Q-park Kalverstraat",
                "street_number": "451C",
                "zip": "1012WP",
                "city": "Amsterdam",
                "meta": [],
            },
        },
        {
            "type": "Feature",
            "geometry": {"type": "Point", "coordinates": [4.89605496, 52.36642671]},
            "properties": {
                "id": "12624959",
                "title": "Q-park Rembrandtplein",
                "description": "Niet geopend op Koningsdag",
                "street": "Rembrandtplein",
                "street_number": "5",
                "zip": "1017CT",
                "city": "Amsterdam",
                "meta": [],
            },
        },
    ],
}
