MOCK_DATA = {
    "type": "FeatureCollection",
    "features": [
        {
            "type": "Feature",
            "geometry": {"type": "MultiPoint", "coordinates": [[4.899551, 52.377938]]},
            "properties": {
                "id": "12345678",
                "title": "EHBO-post Centraal Station",
                "description": "<p>EHBO-posten voor eerste hulp bij ongevallen tijdens Koningsdag 11.30 - 23.30 uur</p>",
                "street": "Burgwallen-Nieuwezijds",
                "street_number": "52,344986-4,899534",
                "city": "Amsterdam",
                "website": "http://www.amsterdam.nl/koningsdag",
                "meta": [],
            },
        },
        {
            "type": "Feature",
            "geometry": {"type": "Point", "coordinates": [4.893404, 52.372925]},
            "properties": {
                "id": "12345677",
                "title": "EHBO-post Dam",
                "description": "EHBO-posten voor eerste hulp bij ongevallen tijdens Koningsdag 12.30 - 22.30 uur",
                "street": "Dam",
                "street_number": "nationaal monument tussen de leeuwen",
                "city": "Amsterdam",
                "website": "http://www.amsterdam.nl/koningsdag",
                "meta": [],
            },
        },
        {
            "type": "Feature",
            "geometry": {"type": "MultiPoint", "coordinates": [[4.897163, 52.366412]]},
            "properties": {
                "id": "12345676",
                "title": "EHBO-post Rembrandtplein",
                "description": "<p>EHBO-posten voor eerste hulp bij ongevallen tijdens Koningsdag 12.30 - 22.30 uur</p>",
                "street": "Rembrandtplein",
                "street_number": "19",
                "city": "Amsterdam",
                "website": "http://www.amsterdam.nl/koningsdag",
                "meta": [],
            },
        },
        {
            "type": "Feature",
            "geometry": {"type": "MultiPoint", "coordinates": [[4.887322, 52.37996]]},
            "properties": {
                "id": "12345675",
                "title": "EHBO-post Noordermarkt",
                "description": "<p>EHBO-posten voor eerste hulp bij ongevallen tijdens Koningsdag 11.00 - 22.30 uur</p>",
                "street": "Noordermarkt",
                "street_number": "47-46",
                "city": "Amsterdam",
                "website": "http://www.amsterdam.nl/koningsdag",
                "meta": [],
            },
        },
        {
            "type": "Feature",
            "geometry": {"type": "Point", "coordinates": [4.889467, 52.367448]},
            "properties": {
                "id": "12345674",
                "title": "EHBO-post Koningsplein",
                "description": "EHBO-posten voor eerste hulp bij ongevallen tijdens Koningsdag 12.30 - 22.30 uur",
                "street": "Koningsplein ",
                "street_number": "t.o.2",
                "city": "Amsterdam",
                "website": "http://www.amsterdam.nl/koningsdag",
                "meta": [],
            },
        },
        {
            "type": "Feature",
            "geometry": {"type": "MultiPoint", "coordinates": [[4.88439, 52.374169]]},
            "properties": {
                "id": "12345673",
                "title": "EHBO-post Westerstraat",
                "description": "<p>EHBO-posten voor eerste hulp bij ongevallen tijdens Koningsdag 13.00 - 20.00 uur</p>",
                "street": "Westermarkt",
                "street_number": "homomonument",
                "city": "Amsterdam",
                "website": "http://www.amsterdam.nl/koningsdag",
                "meta": [],
            },
        },
    ],
}
