MOCK_DATA = {
    "type": "FeatureCollection",
    "features": [
        {
            "type": "Feature",
            "geometry": {"type": "Point", "coordinates": [4.89772303, 52.36231791]},
            "properties": {
                "id": "12345673",
                "title": "Kindervrijmarkt Amstelveld (tot aan de speeltoestellen)",
                "description": "Deze vrijmarkt is speciaal voor kinderen (tot 16 jaar)",
                "street": "Amstelveld ",
                "street_number": "1",
                "zip": "1017 JD",
                "city": "Amsterdam",
                "website": "http:\/\/www.amsterdam.nl\/koningsdag",
                "meta": [],
            },
        },
        {
            "type": "Feature",
            "geometry": {"type": "Point", "coordinates": [4.82184893, 52.37973118]},
            "properties": {
                "id": "12345674",
                "title": "Kindervrijmarkt Plein \u201840-\u201845",
                "description": "Deze vrijmarkt is speciaal voor kinderen (tot 16 jaar)",
                "street": "Plein \u201840-\u201845",
                "street_number": "1",
                "zip": "1063 KP",
                "city": "Amsterdam",
                "website": "http:\/\/www.amsterdam.nl\/koningsdag",
                "meta": [],
            },
        },
        {
            "type": "Feature",
            "geometry": {"type": "Point", "coordinates": [4.89548725, 52.36598396]},
            "properties": {
                "id": "12345675",
                "title": "Kindervrijmarkt Rembrandtplein",
                "description": "Deze vrijmarkt is speciaal voor kinderen (tot 16 jaar)",
                "street": "Rembrandtplein",
                "street_number": "8",
                "zip": "1017 CV",
                "city": "Amsterdam",
                "website": "http:\/\/www.amsterdam.nl\/koningsdag",
                "meta": [],
            },
        },
        {
            "type": "Feature",
            "geometry": {"type": "Point", "coordinates": [4.90114087, 52.36991696]},
            "properties": {
                "id": "12345676",
                "title": "Kindervrijmarkt Sint Antoniesluis tot de rijbaan van de auto\u2019s",
                "description": "Deze vrijmarkt is speciaal voor kinderen (tot 16 jaar)",
                "street": "Sint Antoniesluis",
                "street_number": "20",
                "zip": "1011 JB",
                "city": "Amsterdam",
                "website": "http:\/\/www.amsterdam.nl\/koningsdag",
                "meta": [],
            },
        },
        {
            "type": "Feature",
            "geometry": {"type": "Point", "coordinates": [4.88120577, 52.38620006]},
            "properties": {
                "id": "12345677",
                "title": "Kindervrijmarkt Westerpark",
                "description": "Deze vrijmarkt is speciaal voor kinderen (tot 16 jaar)",
                "street": "Westerpark",
                "street_number": "1",
                "zip": "1013 RR",
                "city": "Amsterdam",
                "website": "http:\/\/www.amsterdam.nl\/koningsdag",
                "meta": [],
            },
        },
        {
            "type": "Feature",
            "geometry": {"type": "Point", "coordinates": [5.04041173, 52.30805691]},
            "properties": {
                "id": "12345679",
                "title": "Kindervrijmarkt Weesp (tussen Breedstraat en Binnenveer)",
                "description": "Deze vrijmarkt is speciaal voor kinderen (tot 16 jaar)",
                "street": "Oudegracht",
                "street_number": "5",
                "zip": "1381 CD",
                "city": "Amsterdam",
                "website": "http:\/\/www.amsterdam.nl\/koningsdag",
                "meta": [],
            },
        },
        {
            "type": "Feature",
            "geometry": {"type": "Point", "coordinates": [5.04205888, 52.30750369]},
            "properties": {
                "id": "12345678",
                "title": "Kindervrijmarkt Weesp (tussen Pleinbrug en Slijkstraatbrug)",
                "description": "Deze vrijmarkt is speciaal voor kinderen (tot 16 jaar)",
                "street": "Pleinbrug",
                "zip": "1381 BB",
                "city": "Amsterdam",
                "website": "http:\/\/www.amsterdam.nl\/koningsdag",
                "meta": [],
            },
        },
    ],
}
