MOCK_DATA = {
    "type": "FeatureCollection",
    "features": [
        {
            "type": "Feature",
            "geometry": {"type": "Point", "coordinates": [4.94060319, 52.31371028]},
            "properties": {
                "id": "12651425",
                "title": "P+R P1 ArenA",
                "description": "13,- euro per 24 uur of 6,- euro na 10.00 uur",
                "street": "Burgemeester Stramanweg",
                "street_number": "130",
                "zip": "1101EP",
                "city": "Amsterdam",
                "website": "https://www.amsterdam.nl/parkeren/parkeren-reizen/plaatsen-binnen-stad/p1-arena/",
                "meta": [],
            },
        },
        {
            "type": "Feature",
            "geometry": {"type": "Point", "coordinates": [4.93921224, 52.39928601]},
            "properties": {
                "id": "12651428",
                "title": "P+R Boven 't Y",
                "description": "13,- euro per 24 uur of 6,- euro na 10.00 uur",
                "street": "Buikslotermeerplein",
                "street_number": "237",
                "zip": "1025XB",
                "city": "Amsterdam",
                "website": "https://www.amsterdam.nl/parkeren/parkeren-reizen/plaatsen-binnen-stad/pr-boven-t-y/",
                "meta": [],
            },
        },
        {
            "type": "Feature",
            "geometry": {"type": "Point", "coordinates": [4.93012558, 52.39921852]},
            "properties": {
                "id": "12651431",
                "title": "P+R Noord",
                "description": "13,- euro per 24 uur of 6,- euro na 10.00 uur",
                "street": "Nieuwe Leeuwarderweg",
                "street_number": "25",
                "zip": "1022BP",
                "city": "Amsterdam",
                "website": "https://www.amsterdam.nl/parkeren/parkeren-reizen/plaatsen-binnen-stad/noord/",
                "meta": [],
            },
        },
        {
            "type": "Feature",
            "geometry": {"type": "Point", "coordinates": [4.83842824, 52.39002707]},
            "properties": {
                "id": "12651434",
                "title": "P+R Sloterdijk",
                "description": "13,- euro per 24 uur of 6,- euro na 10.00 uur",
                "street": "Piarcoplein",
                "street_number": "1",
                "zip": "1043DW",
                "city": "Amsterdam",
                "website": "https://www.amsterdam.nl/parkeren/parkeren-reizen/plaatsen-binnen-stad/pr-sloterdijk/",
                "meta": [],
            },
        },
        {
            "type": "Feature",
            "geometry": {"type": "Point", "coordinates": [4.96411545, 52.36968307]},
            "properties": {
                "id": "12651437",
                "title": "P+R Zeeburg II",
                "description": "13,- euro per 24 uur of 6,- euro na 10.00 uur",
                "street": "Zuiderzeeweg",
                "street_number": "8",
                "zip": "1095KG",
                "city": "Amsterdam",
                "website": "https://www.amsterdam.nl/parkeren/parkeren-reizen/plaatsen-binnen-stad/pr-zeeburg/",
                "meta": [],
            },
        },
        {
            "type": "Feature",
            "geometry": {"type": "Point", "coordinates": [4.97238288, 52.3707905]},
            "properties": {
                "id": "12651440",
                "title": "P+R Zeeburg III",
                "description": "13,- euro per 24 uur of 6,- euro na 10.00 uur",
                "street": "Anthonie van Akernstraat",
                "zip": "1095MV",
                "city": "Amsterdam",
                "website": "https://www.amsterdam.nl/parkeren/parkeren-reizen/plaatsen-binnen-stad/pr-zeeburg-iii/",
                "meta": [],
            },
        },
    ],
}
