MOCK_DATA = {
    "type": "FeatureCollection",
    "features": [
        {
            "type": "Feature",
            "geometry": {
                "type": "Point",
                "coordinates": [4.8035219984679, 52.358951785977],
            },
            "properties": {
                "id": "12576375",
                "title": "Osdorpplein",
                "street": "Osdorpplein",
                "street_number": "626",
                "zip": "1068 TB",
                "city": "Amsterdam",
                "meta": [],
            },
        },
        {
            "type": "Feature",
            "geometry": {"type": "Point", "coordinates": [4.8190084, 52.3811667]},
            "properties": {
                "id": "12576378",
                "title": "Plein '40-'45 ",
                "street": "Burgemeester de Vlugtlaan",
                "street_number": "t/o 182",
                "zip": "1063 BS",
                "city": "Amsterdam",
                "meta": [],
            },
        },
        {
            "type": "Feature",
            "geometry": {"type": "Point", "coordinates": [4.9402136, 52.3974454]},
            "properties": {
                "id": "12576381",
                "title": "Buikslotermeerplein",
                "street": "Buikslotermeerplein",
                "street_number": "310",
                "zip": "1025 GB",
                "city": "Amsterdam",
                "meta": [],
            },
        },
        {
            "type": "Feature",
            "geometry": {
                "type": "Point",
                "coordinates": [4.8953802709368, 52.400955459104],
            },
            "properties": {
                "id": "12576384",
                "title": "NDSM-plein",
                "street": "NDSM-plein",
                "street_number": "78-80",
                "zip": "1033 WC",
                "city": "Amsterdam",
                "meta": [],
            },
        },
        {
            "type": "Feature",
            "geometry": {"type": "Point", "coordinates": [4.933442, 52.3555073]},
            "properties": {
                "id": "12576387",
                "title": "Bredewegfestival 1",
                "street": "Pythagorasstraat",
                "street_number": "27",
                "zip": "1098 EV",
                "city": "Amsterdam",
                "meta": [],
            },
        },
        {
            "type": "Feature",
            "geometry": {"type": "Point", "coordinates": [4.9286088, 52.3551998]},
            "properties": {
                "id": "12576390",
                "title": "Bredewegfestival 2",
                "street": "Linnaeuskade",
                "street_number": "t/o 1",
                "zip": "1098 BR",
                "city": "Amsterdam",
                "meta": [],
            },
        },
        {
            "type": "Feature",
            "geometry": {"type": "Point", "coordinates": [5.0403982, 52.307036]},
            "properties": {
                "id": "12576393",
                "title": "Weesp",
                "street": "Nieuwstad",
                "street_number": "36",
                "zip": "1381 CC",
                "city": "Amsterdam",
                "meta": [],
            },
        },
        {
            "type": "Feature",
            "geometry": {"type": "Point", "coordinates": [4.874245, 52.3866512]},
            "properties": {
                "id": "12576396",
                "title": "Westerpark 1",
                "street": "Pazzanistraat",
                "street_number": "1",
                "zip": "1014 DB",
                "city": "Amsterdam",
                "meta": [],
            },
        },
        {
            "type": "Feature",
            "geometry": {
                "type": "Point",
                "coordinates": [4.8658623542896, 52.35881702509],
            },
            "properties": {
                "id": "12576399",
                "title": "Vondelpark 1",
                "street": "thv Kattenlaan IN HET PARK",
                "street_number": "6",
                "zip": "1071 AA",
                "city": "Amsterdam",
                "meta": [],
            },
        },
        {
            "type": "Feature",
            "geometry": {
                "type": "Point",
                "coordinates": [4.8561417273034, 52.355219694187],
            },
            "properties": {
                "id": "12576402",
                "title": "Vondelpark 2",
                "street": "thv Amstelveenseweg IN HET PARK",
                "street_number": "t/o 124",
                "zip": "1075 XL",
                "city": "Amsterdam",
                "meta": [],
            },
        },
        {
            "type": "Feature",
            "geometry": {
                "type": "Point",
                "coordinates": [4.8666342868243, 52.356255348632],
            },
            "properties": {
                "id": "12576405",
                "title": "Vondelpark 3",
                "street": "thv Koninginneweg IN HET PARK",
                "street_number": "bij 2",
                "zip": "1075 XS",
                "city": "Amsterdam",
                "meta": [],
            },
        },
        {
            "type": "Feature",
            "geometry": {
                "type": "Point",
                "coordinates": [4.8757971849748, 52.360357124618],
            },
            "properties": {
                "id": "12576408",
                "title": "Vondelpark 4",
                "street": "nabij viaduct Van Baerlestraat IN HET PARK",
                "city": "Amsterdam",
                "meta": [],
            },
        },
        {
            "type": "Feature",
            "geometry": {
                "type": "Point",
                "coordinates": [4.8692829984676, 52.350749602483],
            },
            "properties": {
                "id": "12576411",
                "title": "Apollolaan/Witsenstraat",
                "street": "Apollolaan",
                "street_number": "166",
                "zip": "1077 AZ",
                "city": "Amsterdam",
                "meta": [],
            },
        },
        {
            "type": "Feature",
            "geometry": {
                "type": "Point",
                "coordinates": [4.8786450928174, 52.350615636674],
            },
            "properties": {
                "id": "12576414",
                "title": "Apollolaan/Beethovenstraat",
                "street": "Apollolaan",
                "street_number": "84",
                "zip": "1077 BD",
                "city": "Amsterdam",
                "meta": [],
            },
        },
        {
            "type": "Feature",
            "geometry": {"type": "Point", "coordinates": [4.8962306, 52.3536902]},
            "properties": {
                "id": "12576417",
                "title": "Sarphatipark",
                "street": "Sarphatipark",
                "street_number": "t/o 80",
                "city": "Amsterdam",
                "meta": [],
            },
        },
    ],
}
