# Generated by Django 4.2.7 on 2024-01-18 11:44

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("contact", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="openinghours",
            old_name="city_office_id",
            new_name="city_office",
        ),
        migrations.RenameField(
            model_name="openinghoursexception",
            old_name="city_office_id",
            new_name="city_office",
        ),
    ]
