# Generated by Django 5.2 on 2025-04-25 09:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("contact", "0003_migrate_to_django_admin"),
    ]

    operations = [
        migrations.AlterField(
            model_name="openinghours",
            name="city_office",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to="contact.cityoffice",
                verbose_name="Stadskantoor",
            ),
        ),
        migrations.AlterField(
            model_name="openinghours",
            name="day_of_week",
            field=models.IntegerField(
                choices=[
                    (0, "Zondag"),
                    (1, "Maandag"),
                    (2, "Dinsdag"),
                    (3, "Woensdag"),
                    (4, "Donderdag"),
                    (5, "Vrijdag"),
                    (6, "Zaterdag"),
                ],
                verbose_name="Dag van de week",
            ),
        ),
        migrations.AlterField(
            model_name="openinghoursexception",
            name="city_office",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to="contact.cityoffice",
                verbose_name="Stadskantoor",
            ),
        ),
        migrations.AlterField(
            model_name="openinghoursexception",
            name="date",
            field=models.DateField(verbose_name="Datum"),
        ),
    ]
