# Generated by Django 5.2.1 on 2025-05-26 09:19

import django.db.models.deletion
from django.core.management import call_command
from django.db import migrations, models

DATE_OFFICE_MAPPING = {}


def capture_exception_data(apps, schema_editor):
    OpeningHoursException = apps.get_model("contact", "OpeningHoursException")

    for exception in OpeningHoursException.objects.all():
        if exception.date not in DATE_OFFICE_MAPPING:
            DATE_OFFICE_MAPPING[exception.date] = {}

        if exception.opens_time is None or exception.closes_time is None:
            if "all_day" not in DATE_OFFICE_MAPPING[exception.date]:
                DATE_OFFICE_MAPPING[exception.date]["all_day"] = []

            DATE_OFFICE_MAPPING[exception.date]["all_day"].append(
                exception.city_office.identifier
            )
            continue

        time_slot = f"{exception.opens_time.strftime('%H:%M')}-{exception.closes_time.strftime('%H:%M')}"
        if time_slot not in DATE_OFFICE_MAPPING[exception.date]:
            DATE_OFFICE_MAPPING[exception.date][time_slot] = []

        DATE_OFFICE_MAPPING[exception.date][time_slot].append(
            exception.city_office.identifier
        )


def load_exception_data(apps, schema_editor):
    OpeningHoursException = apps.get_model("contact", "OpeningHoursException")
    CityOffice = apps.get_model("contact", "CityOffice")

    # Delete all existing exceptions
    OpeningHoursException.objects.all().delete()

    for date, data in DATE_OFFICE_MAPPING.items():
        for time_slot, offices in data.items():
            offices = CityOffice.objects.filter(identifier__in=offices)
            if len(offices) == 0:
                continue

            exception = OpeningHoursException.objects.create(
                date=date,
                opens_time=time_slot.split("-")[0] if time_slot != "all_day" else None,
                closes_time=time_slot.split("-")[1] if time_slot != "all_day" else None,
            )
            exception.affected_offices.set(offices)
            exception.save()


def load_regular_hours(apps, schema_editor):
    call_command("initregularhours", verbosity=0)


class Migration(migrations.Migration):
    dependencies = [
        ("contact", "0004_alter_openinghours_city_office_and_more"),
    ]

    operations = [
        migrations.RunPython(capture_exception_data),
        migrations.AlterUniqueTogether(
            name="openinghoursexception",
            unique_together=set(),
        ),
        migrations.AddField(
            model_name="openinghoursexception",
            name="affected_offices",
            field=models.ManyToManyField(
                help_text="Selecteer de stadsloketten waar deze uitzondering voor geldt",
                to="contact.cityoffice",
                verbose_name="Stadsloketten",
            ),
        ),
        migrations.AddField(
            model_name="openinghoursexception",
            name="description",
            field=models.CharField(
                blank=True,
                max_length=200,
                null=True,
                verbose_name="Rede van de uitzondering",
            ),
        ),
        migrations.CreateModel(
            name="CityOfficeOpeningHours",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "city_office",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="contact.cityoffice",
                        verbose_name="Stadsloket",
                    ),
                ),
            ],
            options={
                "verbose_name": "Openingstijd regulier",
                "verbose_name_plural": "Openingstijden regulier",
            },
        ),
        migrations.CreateModel(
            name="RegularOpeningHours",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("opens_time", models.TimeField(blank=True, null=True)),
                ("closes_time", models.TimeField(blank=True, null=True)),
                (
                    "day_of_week",
                    models.IntegerField(
                        choices=[
                            (0, "Zondag"),
                            (1, "Maandag"),
                            (2, "Dinsdag"),
                            (3, "Woensdag"),
                            (4, "Donderdag"),
                            (5, "Vrijdag"),
                            (6, "Zaterdag"),
                        ],
                        verbose_name="Dag van de week",
                    ),
                ),
                (
                    "city_office_opening_hours",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="contact.cityofficeopeninghours",
                        verbose_name="Openingstijden stadsloket",
                    ),
                ),
            ],
            options={
                "verbose_name": "Openingstijd",
                "verbose_name_plural": "Openingstijden",
                "unique_together": {("city_office_opening_hours", "day_of_week")},
            },
        ),
        migrations.DeleteModel(
            name="OpeningHours",
        ),
        migrations.RemoveField(
            model_name="openinghoursexception",
            name="city_office",
        ),
        migrations.RunPython(load_exception_data),
        migrations.RunPython(load_regular_hours),
    ]
