# Generated by Django 5.1 on 2025-08-26 16:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("contact", "0005_openinghours_refactor_custom_data_migration"),
    ]

    operations = [
        migrations.CreateModel(
            name="Question",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("question_text", models.CharField()),
                ("description", models.TextField(blank=True, null=True)),
                (
                    "question_type",
                    models.CharField(
                        choices=[
                            ("text", "Text"),
                            ("radio", "Radio"),
                            ("select", "Select"),
                            ("checkbox", "Check"),
                        ],
                        max_length=20,
                    ),
                ),
                ("required", models.BooleanField()),
                (
                    "conditions_type",
                    models.CharField(
                        choices=[("and", "and"), ("or", "or")],
                        default="and",
                        max_length=3,
                    ),
                ),
                (
                    "default",
                    models.CharField(
                        blank=True, default="Open antwoord", max_length=100, null=True
                    ),
                ),
                (
                    "orientation",
                    models.CharField(
                        choices=[
                            ("horizontal", "Horizontal"),
                            ("vertical", "Vertical"),
                        ],
                        max_length=20,
                    ),
                ),
                ("min_characters", models.IntegerField(default=10)),
                ("max_characters", models.IntegerField(default=500)),
                ("sort_order", models.PositiveIntegerField()),
            ],
            options={
                "verbose_name": "Vraag",
                "verbose_name_plural": "Vragen",
                "ordering": ["sort_order"],
            },
        ),
        migrations.CreateModel(
            name="Survey",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "title",
                    models.CharField(max_length=200, unique=True, verbose_name="Titel"),
                ),
                (
                    "description",
                    models.TextField(max_length=1000, verbose_name="Beschrijving"),
                ),
                (
                    "unique_code",
                    models.CharField(
                        max_length=100, unique=True, verbose_name="Unieke code"
                    ),
                ),
                (
                    "team",
                    models.CharField(
                        choices=[("aapp", "Aapp"), ("mams", "Mams")],
                        verbose_name="Team",
                    ),
                ),
                (
                    "fraction",
                    models.FloatField(
                        default=1.0,
                        help_text="Hoeveel procent van de gebruikers moet deze vragenlijst krijgen?",
                        verbose_name="Fractie",
                    ),
                ),
                (
                    "cooldown",
                    models.IntegerField(
                        default=0,
                        help_text="Aantal dagen voordat een gebruiker deze vragenlijst opnieuw aangeboden kan krijgen. 0 = geen cooldown.",
                        verbose_name="Cooldown",
                    ),
                ),
                (
                    "minimum_actions",
                    models.IntegerField(
                        default=0,
                        help_text="Minimaal aantal acties dat een gebruiker moet hebben uitgevoerd voordat deze vragenlijst wordt aangeboden.",
                        verbose_name="Minimaal aantal acties",
                    ),
                ),
            ],
            options={
                "verbose_name": "Vragenlijst",
                "verbose_name_plural": "Vragenlijsten",
            },
        ),
        migrations.CreateModel(
            name="Choice",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("text", models.CharField(max_length=100)),
                ("label", models.CharField(max_length=100)),
                ("show_textfield", models.BooleanField(default=False)),
                ("sort_order", models.PositiveIntegerField()),
                (
                    "question",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="choices",
                        to="contact.question",
                    ),
                ),
            ],
            options={
                "verbose_name": "Keuze",
                "verbose_name_plural": "Keuzes",
                "ordering": ["sort_order"],
            },
        ),
        migrations.CreateModel(
            name="SurveyVersion",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("version", models.PositiveIntegerField(verbose_name="Versie")),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Aangemaakt op"
                    ),
                ),
                (
                    "active_from",
                    models.DateTimeField(null=True, verbose_name="Actief vanaf"),
                ),
                (
                    "survey",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to="contact.survey",
                        verbose_name="Vragenlijst",
                    ),
                ),
            ],
            options={
                "verbose_name": "Vragenlijst versie",
                "verbose_name_plural": "Vragenlijst versies",
                "ordering": ["-version"],
                "unique_together": {("survey", "version")},
            },
        ),
        migrations.CreateModel(
            name="SurveyVersionEntry",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("entry_point", models.CharField(max_length=1000)),
                ("metadata", models.JSONField(default=dict)),
                (
                    "survey_version",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to="contact.surveyversion",
                    ),
                ),
            ],
            options={
                "verbose_name": "Ingevulde vragenlijst",
                "verbose_name_plural": "Ingevulde vragenlijsten",
            },
        ),
        migrations.CreateModel(
            name="Answer",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("answer", models.CharField(max_length=1000)),
                (
                    "question",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        to="contact.question",
                    ),
                ),
                (
                    "survey_version_entry",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="answers",
                        to="contact.surveyversionentry",
                    ),
                ),
            ],
            options={
                "verbose_name": "Antwoord",
                "verbose_name_plural": "Antwoorden",
            },
        ),
        migrations.CreateModel(
            name="SurveyVersionQuestion",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("sort_order", models.PositiveIntegerField(null=True)),
                (
                    "question",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to="contact.question",
                    ),
                ),
                (
                    "survey_version",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to="contact.surveyversion",
                    ),
                ),
            ],
            options={
                "verbose_name": "Vragenlijst vraag",
                "verbose_name_plural": "Vragenlijst vragen",
                "ordering": ["sort_order"],
                "unique_together": {("survey_version", "question")},
            },
        ),
        migrations.AddField(
            model_name="question",
            name="survey_versions",
            field=models.ManyToManyField(
                related_name="questions",
                through="contact.SurveyVersionQuestion",
                to="contact.surveyversion",
                verbose_name="Vragenlijst versies",
            ),
        ),
        migrations.CreateModel(
            name="Condition",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("value", models.CharField(max_length=100)),
                (
                    "type",
                    models.CharField(
                        choices=[
                            ("equal", "Equal"),
                            ("not_equal", "Not Equal"),
                            ("contains", "Contains"),
                            ("not_contains", "Not Contains"),
                        ],
                        max_length=20,
                    ),
                ),
                (
                    "question",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="conditions",
                        to="contact.question",
                    ),
                ),
                (
                    "reference_question",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="reference_question",
                        to="contact.question",
                    ),
                ),
            ],
            options={
                "verbose_name": "Conditie",
                "verbose_name_plural": "Condities",
                "unique_together": {("question", "value")},
            },
        ),
    ]
