# Generated by Django 5.1 on 2025-09-03 13:03

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("contact", "0006_question_survey_choice_surveyversion_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="openinghoursexception",
            name="description",
            field=models.CharField(
                blank=True,
                max_length=200,
                null=True,
                verbose_name="Reden van de uitzondering",
            ),
        ),
    ]
