# Generated by Django 5.1 on 2025-09-16 08:34

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("contact", "0007_alter_openinghoursexception_description"),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="condition",
            unique_together=None,
        ),
        migrations.AlterUniqueTogether(
            name="surveyversionquestion",
            unique_together=None,
        ),
        migrations.AlterUniqueTogether(
            name="surveyversion",
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name="choice",
            name="question",
        ),
        migrations.RemoveField(
            model_name="condition",
            name="question",
        ),
        migrations.RemoveField(
            model_name="condition",
            name="reference_question",
        ),
        migrations.RemoveField(
            model_name="question",
            name="survey_versions",
        ),
        migrations.RemoveField(
            model_name="surveyversionquestion",
            name="question",
        ),
        migrations.RemoveField(
            model_name="surveyversion",
            name="survey",
        ),
        migrations.RemoveField(
            model_name="surveyversionquestion",
            name="survey_version",
        ),
        migrations.RemoveField(
            model_name="surveyversionentry",
            name="survey_version",
        ),
        migrations.DeleteModel(
            name="Answer",
        ),
        migrations.DeleteModel(
            name="Choice",
        ),
        migrations.DeleteModel(
            name="Condition",
        ),
        migrations.DeleteModel(
            name="Question",
        ),
        migrations.DeleteModel(
            name="Survey",
        ),
        migrations.DeleteModel(
            name="SurveyVersionQuestion",
        ),
        migrations.DeleteModel(
            name="SurveyVersion",
        ),
        migrations.DeleteModel(
            name="SurveyVersionEntry",
        ),
    ]
