# Generated by Django 6.0.8 on 2026-09-15 09:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("contact", "0008_remove_choice_question_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="NeighborhoodNotes",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=200)),
                ("body", models.TextField()),
                ("contact_name", models.CharField(max_length=50)),
                ("contact_number", models.CharField(max_length=10)),
                ("lat", models.DecimalField(decimal_places=6, max_digits=9)),
                ("lng", models.DecimalField(decimal_places=6, max_digits=9)),
                ("external_device_id", models.CharField(max_length=100)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name="NeighborhoodNotesImage",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("foreign_id", models.BigIntegerField()),
                ("uri", models.URLField(max_length=2048)),
                ("width", models.IntegerField()),
                ("height", models.IntegerField()),
                (
                    "note",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="images",
                        to="contact.neighborhoodnotes",
                    ),
                ),
            ],
            options={
                "unique_together": {("note", "uri")},
            },
        ),
    ]
