MOCK_DATA = {
    "_embedded": {
        "afvalwijzer": [
            {
                "afvalwijzerOphaaldagen2": "maandag",
                "afvalwijzerFractieNaam": "Papier en karton",
                "afvalwijzerFractieCode": "Papier",
                "afvalwijzerBuitenzettenVanafTot": "Donderdag 21.00 tot vrijdag 07.00 uur",
                "afvalwijzerBuitenzetten": "Donderdag 21.00 tot vrijdag 07.00 uur",
                "afvalwijzerBuitenzettenVanaf": "Donderdag 21.00",
                "afvalwijzerBuitenzettenTot": "tot vrijdag 07.00 uur",
                "afvalwijzerAfvalkalenderOpmerking": "note",
                "afvalwijzerInstructie2": "hoe",
                "afvalwijzerAfvalkalenderMelding": None,
                "afvalwijzerAfvalkalenderFrequentie": "oneven week",
                "afvalwijzerButtontekst": "Test",
                "afvalwijzerUrl": "https://test.nl",
                "afvalwijzerWaar": "Test",
                "gebruiksdoelWoonfunctie": True,
                "afvalwijzerBasisroutetypeCode": "",
                "straatnaam": "straatNaam",
                "huisnummer": "10",
                "huisletter": None,
                "huisnummertoevoeging": None,
                "postcode": "1020AB",
                "woonplaatsnaam": "Amsterdam",
            },
            {
                "afvalwijzerOphaaldagen2": "dinsdag",
                "afvalwijzerFractieNaam": "Groente fruit en tuin",
                "afvalwijzerFractieCode": "GFE",
                "afvalwijzerBuitenzettenVanafTot": "Maandag vanaf 21.00 tot dinsdag 07.00 uur",
                "afvalwijzerBuitenzetten": "Maandag vanaf 21.00 tot dinsdag 07.00 uur",
                "afvalwijzerBuitenzettenVanaf": "Maandag vanaf 21.00",
                "afvalwijzerBuitenzettenTot": "tot dinsdag 07.00 uur",
                "afvalwijzerAfvalkalenderOpmerking": "note",
                "afvalwijzerInstructie2": "hoe",
                "afvalwijzerAfvalkalenderMelding": None,
                "afvalwijzerAfvalkalenderFrequentie": "even week",
                "afvalwijzerButtontekst": "Test",
                "afvalwijzerUrl": "https://test.nl",
                "afvalwijzerWaar": "Test",
                "gebruiksdoelWoonfunctie": True,
                "afvalwijzerBasisroutetypeCode": "",
                "straatnaam": "straatNaam",
                "huisnummer": "10",
                "huisletter": None,
                "huisnummertoevoeging": None,
                "postcode": "1020AB",
                "woonplaatsnaam": "Amsterdam",
            },
        ]
    }
}
