MOCK_DATA = {
    "_embedded": {
        "afvalwijzer": [
            {
                "_links": {},
                "id": "123~Rest",
                "straatnaam": "Straatnaam",
                "huisnummer": 1,
                "huisletter": None,
                "huisnummertoevoeging": None,
                "postcode": "1023AB",
                "woonplaatsnaam": "Amsterdam",
                "statusAdres": "Verblijfsobject in gebruik",
                "gebruiksdoelWoonfunctie": True,
                "afvalwijzerInstructie": None,
                "afvalwijzerBasisroutetypeId": "123",
                "afvalwijzerRoutenaam": "Routenaam_ROL",
                "afvalwijzerPerXWeken": "1",
                "afvalwijzerBuitenzettenVanafTot": "Dinsdag vanaf 21.00 tot woensdag 07.00 uur",
                "afvalwijzerBuitenzettenVanaf": "Dinsdag vanaf 21.00",
                "afvalwijzerBuitenzettenTot": "tot woensdag 07.00 uur",
                "afvalwijzerAfvalkalenderOpmerking": None,
                "afvalwijzerAfvalkalenderFrequentie": None,
                "afvalwijzerFractieNaam": "Restafval",
                "afvalwijzerFractieCode": "Rest",
                "afvalwijzerFractieVolgnummer": 1,
                "afvalwijzerRoutetypeNaam": "Rolcontainer Route",
                "afvalwijzerOphaaldagen": "woensdag",
                "afvalwijzerOphaaldagenArray": ["woensdag"],
                "afvalwijzerAfvalkalenderMelding": None,
                "afvalwijzerAfvalkalenderVan": None,
                "afvalwijzerAfvalkalenderTot": None,
                "afvalwijzerBasisroutetype": "Inzamelgebied",
                "afvalwijzerBasisroutetypeOmschrijving": "Rolcontainer Route",
                "afvalwijzerBasisroutetypeCode": "ROLCONTAIN",
                "afvalwijzerInstructie2": "In rolcontainer",
                "afvalwijzerOphaaldagen2": "woensdag",
                "afvalwijzerOphaaldagen2Array": ["woensdag"],
                "afvalwijzerWaar": "Aan de rand van de stoep of op de vaste plek",
                "afvalwijzerBuitenzetten": "Dinsdag vanaf 21.00 tot woensdag 07.00 uur",
                "afvalwijzerButtontekst": None,
                "afvalwijzerUrl": None,
                "bagNummeraanduidingId": "1234",
            },
            {
                "_links": {},
                "id": "123~Grof afval",
                "straatnaam": "Straatnaam",
                "huisnummer": 1,
                "huisletter": None,
                "huisnummertoevoeging": None,
                "postcode": "1023VV",
                "woonplaatsnaam": "Amsterdam",
                "statusAdres": "Verblijfsobject in gebruik",
                "gebruiksdoelWoonfunctie": True,
                "afvalwijzerInstructie": None,
                "afvalwijzerBasisroutetypeId": "123",
                "afvalwijzerRoutenaam": "Routenaam21.00",
                "afvalwijzerPerXWeken": "1",
                "afvalwijzerBuitenzettenVanafTot": "Dinsdag vanaf 21.00 tot woensdag 07.00 uur",
                "afvalwijzerBuitenzettenVanaf": "Dinsdag vanaf 21.00",
                "afvalwijzerBuitenzettenTot": "tot woensdag 07.00 uur",
                "afvalwijzerAfvalkalenderOpmerking": "",
                "afvalwijzerAfvalkalenderFrequentie": "",
                "afvalwijzerFractieNaam": "Grof afval",
                "afvalwijzerFractieCode": "GA",
                "afvalwijzerFractieVolgnummer": 3,
                "afvalwijzerRoutetypeNaam": "Grof afval vaste dag",
                "afvalwijzerOphaaldagen": "woensdag",
                "afvalwijzerOphaaldagenArray": ["woensdag"],
                "afvalwijzerAfvalkalenderMelding": None,
                "afvalwijzerAfvalkalenderVan": None,
                "afvalwijzerAfvalkalenderTot": None,
                "afvalwijzerBasisroutetype": "Inzamelgebied",
                "afvalwijzerBasisroutetypeOmschrijving": "Waar grof niet op afspraak wordt ingezameld.",
                "afvalwijzerBasisroutetypeCode": "GROFVAST",
                "afvalwijzerInstructie2": "Breng uw grof afval naar een Recyclepunt of buiten zetten",
                "afvalwijzerOphaaldagen2": "woensdag",
                "afvalwijzerOphaaldagen2Array": ["woensdag"],
                "afvalwijzerWaar": "Aan de rand van de stoep of op de vaste plek",
                "afvalwijzerBuitenzetten": "Dinsdag vanaf 21.00 tot woensdag 07.00 uur",
                "afvalwijzerButtontekst": None,
                "afvalwijzerUrl": "https://kaart.amsterdam.nl/recyclepunten",
                "bagNummeraanduidingId": "123",
            },
        ]
    }
}
