MOCK_DATA = {
    "_embedded": {
        "afvalwijzer": [
            {
                "id": "id",
                "gebruiksdoelWoonfunctie": True,
                "afvalwijzerInstructie": None,
                "afvalwijzerBasisroutetypeId": "routid",
                "afvalwijzerRoutenaam": "RouteNaam",
                "afvalwijzerPerXWeken": "4",
                "afvalwijzerBuitenzettenVanafTot": "Donderdag 21.00 tot vrijdag 07.00 uur",
                "afvalwijzerBuitenzettenVanaf": "Donderdag 21.00",
                "afvalwijzerBuitenzettenTot": "tot vrijdag 07.00 uur",
                "afvalwijzerAfvalkalenderOpmerking": None,
                "afvalwijzerAfvalkalenderFrequentie": "12-12 / 9-1 / 6-2 / 6-3 / 3-4 / 1-5 / 29-5 / 26-6 / 24-7 / 21-8 / 18-9 / 16-10 / 13-11 / 11-12",
                "afvalwijzerFractieNaam": "Papier en karton",
                "afvalwijzerFractieCode": "Papier",
                "afvalwijzerFractieVolgnummer": 13,
                "afvalwijzerRoutetypeNaam": "Rolcontainer Route",
                "afvalwijzerOphaaldagen": "vrijdag",
                "afvalwijzerOphaaldagenArray": ["vrijdag"],
                "afvalwijzerAfvalkalenderMelding": None,
                "afvalwijzerAfvalkalenderVan": None,
                "afvalwijzerAfvalkalenderTot": None,
                "afvalwijzerBasisroutetype": "Inzamelgebied",
                "afvalwijzerBasisroutetypeOmschrijving": "Rolcontainer Route",
                "afvalwijzerBasisroutetypeCode": "Rolcontainer code",
                "afvalwijzerGeometrie": {},
                "afvalwijzerInstructie2": "In rolcontainer",
                "afvalwijzerOphaaldagen2": "vrijdag",
                "afvalwijzerOphaaldagen2Array": ["vrijdag"],
                "afvalwijzerWaar": "Aan de rand van de stoep of op de vaste plek",
                "afvalwijzerBuitenzetten": "Donderdag 21.00 tot vrijdag 07.00 uur",
                "afvalwijzerButtontekst": None,
                "afvalwijzerUrl": None,
                "bagNummeraanduidingId": "bagId",
                "gbdBuurtId": "buurtId",
                "gbdBuurtCode": "buurtCode",
                "afvalwijzerInzamelgebiedNaam": "gebiedNaam",
                "afvalwijzerInzamelgebiedCode": "gebiedCode",
            },
        ]
    }
}
