MOCK_DATA = {
    "_embedded": {
        "afvalwijzer": [
            {
                "_links": {},
                "afvalwijzerInstructie": None,
                "afvalwijzerBasisroutetypeId": "Id",
                "afvalwijzerRoutenaam": "RouteNaam",
                "afvalwijzerPerXWeken": "1",
                "afvalwijzerBuitenzettenVanafTot": "Zondag vanaf 21.00 tot maandag 07.00 uur",
                "afvalwijzerBuitenzettenVanaf": "Zondag vanaf 21.00",
                "afvalwijzerBuitenzettenTot": "tot maandag 07.00 uur",
                "afvalwijzerAfvalkalenderOpmerking": None,
                "afvalwijzerAfvalkalenderFrequentie": "Dit is een onbekende frequentie",
                "afvalwijzerFractieNaam": "Papier en karton",
                "afvalwijzerFractieCode": "Papier",
                "afvalwijzerFractieVolgnummer": 13,
                "afvalwijzerRoutetypeNaam": "Rolcontainer Route",
                "afvalwijzerOphaaldagen": "maandag",
                "afvalwijzerOphaaldagenArray": ["maandag"],
                "afvalwijzerAfvalkalenderMelding": None,
                "afvalwijzerAfvalkalenderVan": None,
                "afvalwijzerAfvalkalenderTot": None,
                "afvalwijzerBasisroutetype": "Inzamelgebied",
                "afvalwijzerBasisroutetypeOmschrijving": "Rolcontainer Route",
                "afvalwijzerInstructie2": "In rolcontainer",
                "afvalwijzerOphaaldagen2": "maandag",
                "afvalwijzerOphaaldagen2Array": ["maandag"],
                "afvalwijzerWaar": "Aan de rand van de stoep of op de vaste plek",
                "afvalwijzerBuitenzetten": "Zondag vanaf 21.00 tot maandag 07.00 uur",
                "afvalwijzerButtontekst": None,
                "afvalwijzerUrl": None,
                "bagNummeraanduidingId": "x",
                "gbdBuurtId": "y",
                "gbdBuurtCode": "z",
                "afvalwijzerInzamelgebiedNaam": "a",
                "afvalwijzerInzamelgebiedCode": "b",
                "gebruiksdoelWoonfunctie": True,
                "afvalwijzerBasisroutetypeCode": None,
            },
        ]
    }
}
