MOCK_DATA = {
    "_embedded": {
        "afvalwijzer": [
            {
                "id": "123~Papier en karton",
                "straatnaam": "Straatnaam",
                "huisnummer": 1,
                "huisletter": None,
                "huisnummertoevoeging": None,
                "postcode": "1023NT",
                "woonplaatsnaam": "Amsterdam",
                "statusAdres": "Verblijfsobject in gebruik",
                "gebruiksdoelWoonfunctie": True,
                "afvalwijzerInstructie": None,
                "afvalwijzerBasisroutetypeId": "123",
                "afvalwijzerRoutenaam": "Routenaam21.00",
                "afvalwijzerPerXWeken": "1",
                "afvalwijzerBuitenzettenVanafTot": "Donderdag vanaf 21.00 tot vrijdag 07.00 uur",
                "afvalwijzerBuitenzettenVanaf": "Donderdag vanaf 21.00",
                "afvalwijzerBuitenzettenTot": "tot vrijdag 07.00 uur",
                "afvalwijzerAfvalkalenderOpmerking": "Vrijdag, 23-1 / 20-2 / 20-3 / 17-4 / 15-5 / 12-6 / 10-7 / 7-8 / 4-9 / 2-10 / 30-10 / 27-11 / 25-12",
                "afvalwijzerAfvalkalenderFrequentie": "om de 4 weken",
                "afvalwijzerFractieNaam": "Papier en karton",
                "afvalwijzerFractieCode": "Papier",
                "afvalwijzerFractieVolgnummer": 1,
                "afvalwijzerRoutetypeNaam": "Rolcontainer Route",
                "afvalwijzerOphaaldagen": "vrijdag",
                "afvalwijzerOphaaldagenArray": ["vrijdag"],
                "afvalwijzerAfvalkalenderMelding": None,
                "afvalwijzerAfvalkalenderVan": None,
                "afvalwijzerAfvalkalenderTot": None,
                "afvalwijzerBasisroutetype": "Inzamelgebied",
                "afvalwijzerBasisroutetypeOmschrijving": "Rolcontainer Route",
                "afvalwijzerBasisroutetypeCode": "ROLCONTAIN",
                "afvalwijzerInstructie2": "In rolcontainer",
                "afvalwijzerOphaaldagen2": "vrijdag",
                "afvalwijzerOphaaldagen2Array": ["vrijdag"],
                "afvalwijzerWaar": "Aan de rand van de stoep of op de vaste plek",
                "afvalwijzerBuitenzetten": "Donderdag vanaf 21.00 tot vrijdag 07.00 uur",
                "afvalwijzerButtontekst": None,
                "afvalwijzerUrl": None,
                "bagNummeraanduidingId": "123",
            },
        ]
    }
}
