MOCK_DATA = {
    "_embedded": {
        "afvalwijzer": [
            {
                "afvalwijzerPerXWeken": None,
                "afvalwijzerBuitenzetten": None,
                "afvalwijzerBuitenzettenVanaf": None,
                "afvalwijzerBuitenzettenTot": None,
                "afvalwijzerAfvalkalenderOpmerking": None,
                "afvalwijzerFractieNaam": "Glas",
                "afvalwijzerFractieCode": "Glas",
                "afvalwijzerOphaaldagen2": None,
                "afvalwijzerAfvalkalenderMelding": None,
                "afvalwijzerInstructie2": None,
                "afvalwijzerAfvalkalenderVan": None,
                "afvalwijzerAfvalkalenderTot": None,
                "afvalwijzerAfvalkalenderFrequentie": None,
                "afvalwijzerButtontekst": "Test",
                "afvalwijzerUrl": "https://test.nl",
                "afvalwijzerWaar": "Test",
                "gebruiksdoelWoonfunctie": True,
                "afvalwijzerBasisroutetypeCode": None,
                "straatnaam": "straatNaam",
                "huisnummer": "10",
                "huisletter": "A",
                "huisnummertoevoeging": "-C",
                "postcode": "1020AB",
                "woonplaatsnaam": "Amsterdam",
            },
            {
                "afvalwijzerPerXWeken": "1",
                "afvalwijzerBuitenzetten": None,
                "afvalwijzerBuitenzettenVanafTot": "",
                "afvalwijzerBuitenzettenVanaf": None,
                "afvalwijzerBuitenzettenTot": None,
                "afvalwijzerAfvalkalenderOpmerking": '<b>Tuinafval: </b> breng het naar <a href="https://maps.amsterdam.nl/tuinkorven/?LANG=nl">een tuinkorf in de buurt</a>, naar <a href="https://kaart.amsterdam.nl/afvalpunten">een Recyclepunt</a> of anders bij het grof afval.',
                "afvalwijzerFractieNaam": "Groente, fruit, etensresten en tuinafval",
                "afvalwijzerFractieCode": "GFE",
                "afvalwijzerOphaaldagen2": "maandag, dinsdag, woensdag",
                "afvalwijzerAfvalkalenderMelding": "Breng uw kerstboom naar een <a href=http://amsterdam.nl/recyclepunten>Recyclepunt.  </a>",
                "afvalwijzerInstructie2": None,
                "afvalwijzerAfvalkalenderVan": "2025-01-17T00:00:00",
                "afvalwijzerAfvalkalenderTot": "2025-01-31T00:00:00",
                "afvalwijzerAfvalkalenderFrequentie": None,
                "afvalwijzerButtontekst": "Test",
                "afvalwijzerUrl": "https://test.nl",
                "afvalwijzerWaar": "Test",
                "gebruiksdoelWoonfunctie": True,
                "afvalwijzerBasisroutetypeCode": None,
                "bagNummeraanduidingId": "12345",
                "straatnaam": "straatNaam",
                "huisnummer": "10",
                "huisletter": "A",
                "huisnummertoevoeging": "-C",
                "postcode": "1020AB",
                "woonplaatsnaam": "Amsterdam",
            },
        ]
    }
}
