MOCK_DATA = {
    "type": "FeatureCollection",
    "name": "OPENBARE_TOILETTEN",
    "features": [
        {
            "id": 1,
            "type": "Feature",
            "geometry": {"type": "Point", "coordinates": [4.8900955, 52.3672802]},
            "properties": {
                "Soort": "Amsterdamse krul",
                "Prijs_per_gebruik": 0,
                "Dagen_geopend": "",
                "Openingstijden": "24 uur",
                "Omschrijving": "Singel tov Bloemenmarkt",
                "Foto": "IMG_8829.jpg",
                "SELECTIE": "KRUL",
            },
        },
        {
            "id": 2,
            "type": "Feature",
            "geometry": {"type": "Point", "coordinates": [4.8892087, 52.3674372]},
            "properties": {
                "Soort": "Openbaar toilet, rolstoeltoegankelijk",
                "Prijs_per_gebruik": 0.5,
                "Dagen_geopend": "ma - di - wo - do - vr - za - zo",
                "Openingstijden": "24 uur per dag",
                "Omschrijving": "Koningsplein",
                "Foto": "IMG_8832.jpg",
                "SELECTIE": "TOEGANG",
            },
        },
        {
            "id": 3,
            "type": "Feature",
            "geometry": {"type": "Point", "coordinates": [4.8922195, 52.3662449]},
            "properties": {
                "Soort": "Verzinkbaar urinoir",
                "Prijs_per_gebruik": 0,
                "Dagen_geopend": "",
                "Openingstijden": "Donderdag tot en met zondag van 18.00 - 7.00 uur.\n\nTussen 15.30 - 18.00 uur verplaatsing naar bovengronds.\ntussen 07.00 - 09.00 uur verplaatsing naar ondergronds.",
                "Omschrijving": "Urilift",
                "Foto": "reguliersdwarsstraat.JPG",
                "SELECTIE": "URILIFT",
            },
        },
        {
            "id": 7,
            "type": "Feature",
            "geometry": {"type": "Point", "coordinates": [4.894839, 52.329087]},
            "properties": {
                "Soort": "Openbaar toilet",
                "Prijs_per_gebruik": 0,
                "Dagen_geopend": "",
                "Openingstijden": "",
                "Omschrijving": "",
                "Foto": "",
                "SELECTIE": "OPENBAAR",
            },
        },
        {
            "id": 8,
            "type": "Feature",
            "geometry": {"type": "Point", "coordinates": [4.893252, 52.331956]},
            "properties": {
                "Soort": "Openbaar toilet",
                "Prijs_per_gebruik": 0,
                "Dagen_geopend": "",
                "Openingstijden": "",
                "Omschrijving": "",
                "Foto": "",
                "SELECTIE": "OPENBAAR",
            },
        },
        {
            "id": 11,
            "type": "Feature",
            "geometry": {"type": "Point", "coordinates": [4.898217, 52.3739024]},
            "properties": {
                "Soort": "Amsterdamse krul",
                "Prijs_per_gebruik": 0,
                "Dagen_geopend": "",
                "Openingstijden": "24 uur",
                "Omschrijving": "Oudekerkplein Zuidzijde",
                "Foto": "IMG_9103.jpg",
                "SELECTIE": "KRUL",
            },
        },
        {
            "id": 12,
            "type": "Feature",
            "geometry": {"type": "Point", "coordinates": [4.892413, 52.37708]},
            "properties": {
                "Soort": "Amsterdamse krul",
                "Prijs_per_gebruik": 0,
                "Dagen_geopend": "",
                "Openingstijden": "24 uur",
                "Omschrijving": "Singel tov 43",
                "Foto": "IMG_9031.jpg",
                "SELECTIE": "KRUL",
            },
        },
        {
            "id": 13,
            "type": "Feature",
            "geometry": {"type": "Point", "coordinates": [4.884908, 52.374496]},
            "properties": {
                "Soort": "Amsterdamse krul",
                "Prijs_per_gebruik": 0,
                "Dagen_geopend": "ma - di - wo - do - vr - za - zo",
                "Openingstijden": "24 uur per dag",
                "Omschrijving": "Westermarkt Prinsengracht - twee krullen",
                "Foto": "IMG_9022.jpg",
                "SELECTIE": "KRUL",
            },
        },
        {
            "id": 14,
            "type": "Feature",
            "geometry": {"type": "Point", "coordinates": [4.889051, 52.373057]},
            "properties": {
                "Soort": "Amsterdamse krul",
                "Prijs_per_gebruik": 0,
                "Dagen_geopend": "",
                "Openingstijden": "24 uur",
                "Omschrijving": "Singel / Raadhuisstraat",
                "Foto": "IMG_9027.jpg",
                "SELECTIE": "KRUL",
            },
        },
        {
            "id": 15,
            "type": "Feature",
            "geometry": {"type": "Point", "coordinates": [4.889522, 52.374254]},
            "properties": {
                "Soort": "Amsterdamse krul",
                "Prijs_per_gebruik": 0,
                "Dagen_geopend": "",
                "Openingstijden": "24 uur",
                "Omschrijving": "Singel tov 167",
                "Foto": "IMG_9030.jpg",
                "SELECTIE": "KRUL",
            },
        },
        {
            "id": 16,
            "type": "Feature",
            "geometry": {"type": "Point", "coordinates": [4.888361, 52.370394]},
            "properties": {
                "Soort": "Amsterdamse krul",
                "Prijs_per_gebruik": 0,
                "Dagen_geopend": "",
                "Openingstijden": "24 uur",
                "Omschrijving": "Singel tov 311",
                "Foto": "IMG_9025.jpg",
                "SELECTIE": "KRUL",
            },
        },
        {
            "id": 17,
            "type": "Feature",
            "geometry": {"type": "Point", "coordinates": [4.894051, 52.378983]},
            "properties": {
                "Soort": "Amsterdamse krul",
                "Prijs_per_gebruik": 0,
                "Dagen_geopend": "",
                "Openingstijden": "24 uur",
                "Omschrijving": "Brouwersgracht / Singel nabij Singelsluis",
                "Foto": "IMG_9016.JPG",
                "SELECTIE": "KRUL",
            },
        },
        {
            "id": 18,
            "type": "Feature",
            "geometry": {"type": "Point", "coordinates": [4.898922, 52.3744669]},
            "properties": {
                "Soort": "Amsterdamse krul",
                "Prijs_per_gebruik": 0,
                "Dagen_geopend": "",
                "Openingstijden": "24 uur",
                "Omschrijving": "Oudekerkplein noordzijde",
                "Foto": "IMG_9100.jpg",
                "SELECTIE": "KRUL",
            },
        },
        {
            "id": 19,
            "type": "Feature",
            "geometry": {"type": "Point", "coordinates": [4.898609, 52.373178]},
            "properties": {
                "Soort": "Amsterdamse krul",
                "Prijs_per_gebruik": 0,
                "Dagen_geopend": "",
                "Openingstijden": "24 uur",
                "Omschrijving": "Oudezijds Achterburgwal tov 78",
                "Foto": "IMG_9105.jpg",
                "SELECTIE": "KRUL",
            },
        },
        {
            "id": 20,
            "type": "Feature",
            "geometry": {"type": "Point", "coordinates": [4.89816, 52.372601]},
            "properties": {
                "Soort": "Amsterdamse krul",
                "Prijs_per_gebruik": 0,
                "Dagen_geopend": "",
                "Openingstijden": "24 uur",
                "Omschrijving": "Oudezijds Achterburgwal / Brandesteeg",
                "Foto": "IMG_9106.jpg",
                "SELECTIE": "KRUL",
            },
        },
        {
            "id": 21,
            "type": "Feature",
            "geometry": {"type": "Point", "coordinates": [4.89553, 52.371457]},
            "properties": {
                "Soort": "Amsterdamse krul",
                "Prijs_per_gebruik": 0,
                "Dagen_geopend": "",
                "Openingstijden": "24 uur",
                "Omschrijving": "Oudezijds Voorburgwal, Prinsenhof / Hotel The Grand",
                "Foto": "IMG_9108.jpg",
                "SELECTIE": "KRUL",
            },
        },
        {
            "id": 22,
            "type": "Feature",
            "geometry": {"type": "Point", "coordinates": [4.889736, 52.364351]},
            "properties": {
                "Soort": "Amsterdamse krul",
                "Prijs_per_gebruik": 0,
                "Dagen_geopend": "",
                "Openingstijden": "24 uur",
                "Omschrijving": "Nieuwe Spiegelgracht - Keizersgracht",
                "Foto": "IMG_8834.JPG",
                "SELECTIE": "KRUL",
            },
        },
        {
            "id": 23,
            "type": "Feature",
            "geometry": {"type": "Point", "coordinates": [4.8985876, 52.3639136]},
            "properties": {
                "Soort": "Amsterdamse krul",
                "Prijs_per_gebruik": 0,
                "Dagen_geopend": "",
                "Openingstijden": "24 uur",
                "Omschrijving": "Utrechtse straat",
                "Foto": "IMG_8818.jpg",
                "SELECTIE": "KRUL",
            },
        },
        {
            "id": 25,
            "type": "Feature",
            "geometry": {"type": "Point", "coordinates": [4.880664, 52.379636]},
            "properties": {
                "Soort": "Amsterdamse krul",
                "Prijs_per_gebruik": 0,
                "Dagen_geopend": "ma - di - wo - do - vr - za - zo",
                "Openingstijden": "24 uur per dag",
                "Omschrijving": "Lindengracht",
                "Foto": "IMG_8981.jpg",
                "SELECTIE": "KRUL",
            },
        },
        {
            "id": 27,
            "type": "Feature",
            "geometry": {"type": "Point", "coordinates": [4.877074, 52.368764]},
            "properties": {
                "Soort": "Amsterdamse krul",
                "Prijs_per_gebruik": 0,
                "Dagen_geopend": "",
                "Openingstijden": "24 uur",
                "Omschrijving": "Marnixstraat - Elandsgracht tov bureau van Politie",
                "Foto": "IMG_8976.jpg",
                "SELECTIE": "KRUL",
            },
        },
        {
            "id": 29,
            "type": "Feature",
            "geometry": {"type": "Point", "coordinates": [4.8864027, 52.3619726]},
            "properties": {
                "Soort": "Amsterdamse krul",
                "Prijs_per_gebruik": 0,
                "Dagen_geopend": "",
                "Openingstijden": "24 uur",
                "Omschrijving": "Lijnbaansgracht 282",
                "Foto": "IMG_8836.jpg",
                "SELECTIE": "KRUL",
            },
        },
        {
            "id": 30,
            "type": "Feature",
            "geometry": {"type": "Point", "coordinates": [4.8961937, 52.3620631]},
            "properties": {
                "Soort": "Amsterdamse krul",
                "Prijs_per_gebruik": 0,
                "Dagen_geopend": "ma - di - wo - do - vr - za - zo",
                "Openingstijden": "24 uur per dag",
                "Omschrijving": "Amstelveld",
                "Foto": "IMG_8819.jpg",
                "SELECTIE": "KRUL",
            },
        },
        {
            "id": 31,
            "type": "Feature",
            "geometry": {"type": "Point", "coordinates": [4.8801821, 52.3812911]},
            "properties": {
                "Soort": "Amsterdamse krul",
                "Prijs_per_gebruik": 0,
                "Dagen_geopend": "",
                "Openingstijden": "24 uur",
                "Omschrijving": "Marnixplantsoen, nabij brug",
                "Foto": "IMG_9020.jpg",
                "SELECTIE": "KRUL",
            },
        },
        {
            "id": 32,
            "type": "Feature",
            "geometry": {"type": "Point", "coordinates": [0, 0]},
            "properties": {
                "Soort": "Amsterdamse krul",
                "Prijs_per_gebruik": 0,
                "Dagen_geopend": "",
                "Openingstijden": "",
                "Omschrijving": "Nieuwe Achtergracht",
                "Foto": "IMG_8930.jpg",
                "SELECTIE": "KRUL",
            },
        },
        {
            "id": 33,
            "type": "Feature",
            "geometry": {"type": "Point", "coordinates": [4.865594, 52.358558]},
            "properties": {
                "Soort": "Openbaar toilet, rolstoeltoegankelijk",
                "Prijs_per_gebruik": 0,
                "Dagen_geopend": "",
                "Openingstijden": "Geopend in de lente en (na) zomer, bij mooi weer",
                "Omschrijving": "nabij het pierenbadje",
                "Foto": "vondelpark01.JPG",
                "SELECTIE": "TOEGANG",
            },
        },
        {
            "id": 34,
            "type": "Feature",
            "geometry": {"type": "Point", "coordinates": [4.871436, 52.358575]},
            "properties": {
                "Soort": "Openbaar toilet",
                "Prijs_per_gebruik": 0,
                "Dagen_geopend": "",
                "Openingstijden": "Geopend in de lente en (na) zomer, bij mooi weer",
                "Omschrijving": "nabij openluchtheater",
                "Foto": "vondelpark02.JPG",
                "SELECTIE": "OPENBAAR",
            },
        },
        {
            "id": 35,
            "type": "Feature",
            "geometry": {"type": "Point", "coordinates": [4.886989, 52.35404]},
            "properties": {
                "Soort": "Amsterdamse krul",
                "Prijs_per_gebruik": 0,
                "Dagen_geopend": "",
                "Openingstijden": "24 uur",
                "Omschrijving": "Ruysdaelkade / Govert Flinckstraat",
                "Foto": "IMG_8969.jpg",
                "SELECTIE": "KRUL",
            },
        },
        {
            "id": 36,
            "type": "Feature",
            "geometry": {"type": "Point", "coordinates": [4.886433, 52.357767]},
            "properties": {
                "Soort": "Amsterdamse krul",
                "Prijs_per_gebruik": 0,
                "Dagen_geopend": "",
                "Openingstijden": "24 uur per dag",
                "Omschrijving": "Hobbemakade /  Honthorststraat - Brandweerkazerne",
                "Foto": "IMG_8936.jpg",
                "SELECTIE": "KRUL",
            },
        },
        {
            "id": 37,
            "type": "Feature",
            "geometry": {"type": "Point", "coordinates": [4.8784841, 52.3556267]},
            "properties": {
                "Soort": "Amsterdamse krul",
                "Prijs_per_gebruik": 0,
                "Dagen_geopend": "ma - di - wo - do - vr - za - zo",
                "Openingstijden": "24 uur per dag",
                "Omschrijving": "Naast het Concertgebouw",
                "Foto": "IMG_8972.jpg",
                "SELECTIE": "KRUL",
            },
        },
        {
            "id": 38,
            "type": "Feature",
            "geometry": {"type": "Point", "coordinates": [4.891667, 52.379413]},
            "properties": {
                "Soort": "Amsterdamse krul",
                "Prijs_per_gebruik": 0,
                "Dagen_geopend": "",
                "Openingstijden": "24 uur",
                "Omschrijving": "Herenmarkt / Brouwersgracht",
                "Foto": "IMG_9017.JPG",
                "SELECTIE": "KRUL",
            },
        },
        {
            "id": 39,
            "type": "Feature",
            "geometry": {"type": "Point", "coordinates": [4.911695, 52.37022]},
            "properties": {
                "Soort": "Amsterdamse krul",
                "Prijs_per_gebruik": 0,
                "Dagen_geopend": "ma - di - wo - do - vr - za - zo",
                "Openingstijden": "24 uur per dag",
                "Omschrijving": "Kadijksplein ",
                "Foto": "kadijksplein.JPG",
                "SELECTIE": "KRUL",
            },
        },
        {
            "id": 40,
            "type": "Feature",
            "geometry": {"type": "Point", "coordinates": [4.913126, 52.3676861]},
            "properties": {
                "Soort": "Amsterdamse krul",
                "Prijs_per_gebruik": 0,
                "Dagen_geopend": "ma - di - wo - do - vr - za - zo",
                "Openingstijden": "24 uur per dag",
                "Omschrijving": "Kerklaan, nabij ingang Artis",
                "Foto": "artis.JPG",
                "SELECTIE": "KRUL",
            },
        },
        {
            "id": 42,
            "type": "Feature",
            "geometry": {"type": "Point", "coordinates": [4.919494, 52.360293]},
            "properties": {
                "Soort": "Amsterdamse krul",
                "Prijs_per_gebruik": 0,
                "Dagen_geopend": "",
                "Openingstijden": "24 uur",
                "Omschrijving": "Oosterpark",
                "Foto": "IMG_20190220_125412.jpg",
                "SELECTIE": "KRUL",
            },
        },
        {
            "id": 45,
            "type": "Feature",
            "geometry": {"type": "Point", "coordinates": [4.856356, 52.3593632]},
            "properties": {
                "Soort": "Amsterdamse krul",
                "Prijs_per_gebruik": 0,
                "Dagen_geopend": "",
                "Openingstijden": "24 uur",
                "Omschrijving": "Derde kostverlorenkade / Vosmaerstraat",
                "Foto": "Kostverlorenkade.JPG",
                "SELECTIE": "KRUL",
            },
        },
        {
            "id": 46,
            "type": "Feature",
            "geometry": {"type": "Point", "coordinates": [4.884215, 52.343593]},
            "properties": {
                "Soort": "Openbaar toilet",
                "Prijs_per_gebruik": 0,
                "Dagen_geopend": "",
                "Openingstijden": "Open bij mooi weer. Zie http://parkkiosk.nl/. ",
                "Omschrijving": "Toilet bij kiosk, beheerd door de gemeente",
                "Foto": "beatrixpark.JPG",
                "SELECTIE": "OPENBAAR",
            },
        },
        {
            "id": 47,
            "type": "Feature",
            "geometry": {"type": "Point", "coordinates": [4.9221546, 52.3859969]},
            "properties": {
                "Soort": "Amsterdamse krul",
                "Prijs_per_gebruik": 0,
                "Dagen_geopend": "",
                "Openingstijden": "",
                "Omschrijving": "Meeuwenlaan / Hamerstraat",
                "Foto": "15505002048947976083692405215953.jpg",
                "SELECTIE": "KRUL",
            },
        },
        {
            "id": 48,
            "type": "Feature",
            "geometry": {"type": "Point", "coordinates": [4.9226835, 52.3903263]},
            "properties": {
                "Soort": "Openbaar toilet, rolstoeltoegankelijk",
                "Prijs_per_gebruik": 0,
                "Dagen_geopend": "ma - di - wo - do - vr - za - zo",
                "Openingstijden": "Alleen open als pierenbadje ook open is als het boven de 20 graden is en van mei tot en met september.\n\nMeer informatie: https://www.amsterdam.nl/sport/zwemmen/openbare/",
                "Omschrijving": "Openbaar toilet bij het pierenbadje.\r\nGerenoveerd in 2019",
                "Foto": "15504996584588417992438976311472.jpg",
                "SELECTIE": "TOEGANG",
            },
        },
        {
            "id": 49,
            "type": "Feature",
            "geometry": {"type": "Point", "coordinates": [4.895908, 52.3652109]},
            "properties": {
                "Soort": "Verzinkbaar urinoir",
                "Prijs_per_gebruik": 0,
                "Dagen_geopend": "",
                "Openingstijden": "Donderdag tot en met zondag van 18.00 - 7.00 uur.\n\nTussen 15.30 - 18.00 uur verplaatsing naar bovengronds.\ntussen 07.00 - 09.00 uur verplaatsing naar ondergronds.",
                "Omschrijving": "Urilift",
                "Foto": "IMG_8823.jpg",
                "SELECTIE": "URILIFT",
            },
        },
        {
            "id": 50,
            "type": "Feature",
            "geometry": {"type": "Point", "coordinates": [4.89684, 52.3661357]},
            "properties": {
                "Soort": "Verzinkbaar urinoir",
                "Prijs_per_gebruik": 0,
                "Dagen_geopend": "",
                "Openingstijden": "Donderdag tot en met zondag van 18.00 - 7.00 uur.\n\nTussen 15.30 - 18.00 uur verplaatsing naar bovengronds.\ntussen 07.00 - 09.00 uur verplaatsing naar ondergronds.",
                "Omschrijving": "Urilift",
                "Foto": "IMG_8817.jpg",
                "SELECTIE": "URILIFT",
            },
        },
        {
            "id": 51,
            "type": "Feature",
            "geometry": {"type": "Point", "coordinates": [4.8954716, 52.3670664]},
            "properties": {
                "Soort": "Verzinkbaar urinoir",
                "Prijs_per_gebruik": 0,
                "Dagen_geopend": "",
                "Openingstijden": "Donderdag tot en met zondag van 18.00 - 7.00 uur.\n\nTussen 15.30 - 18.00 uur verplaatsing naar bovengronds.\ntussen 07.00 - 09.00 uur verplaatsing naar ondergronds.",
                "Omschrijving": "Urilift",
                "Foto": "IMG_8828.jpg",
                "SELECTIE": "URILIFT",
            },
        },
        {
            "id": 52,
            "type": "Feature",
            "geometry": {"type": "Point", "coordinates": [4.90012, 52.366569]},
            "properties": {
                "Soort": "Verzinkbaar urinoir",
                "Prijs_per_gebruik": 0,
                "Dagen_geopend": "",
                "Openingstijden": "Donderdag tot en met zondag van 18.00 - 7.00 uur.\n\nTussen 15.30 - 18.00 uur verplaatsing naar bovengronds.\ntussen 07.00 - 09.00 uur verplaatsing naar ondergronds.",
                "Omschrijving": "Urilift",
                "Foto": "IMG_8815.jpg",
                "SELECTIE": "URILIFT",
            },
        },
        {
            "id": 54,
            "type": "Feature",
            "geometry": {"type": "Point", "coordinates": [0, 0]},
            "properties": {
                "Soort": "Amsterdamse krul",
                "Prijs_per_gebruik": 0,
                "Dagen_geopend": "",
                "Openingstijden": "",
                "Omschrijving": "",
                "Foto": "IMG_8813.jpg",
                "SELECTIE": "KRUL",
            },
        },
        {
            "id": 58,
            "type": "Feature",
            "geometry": {"type": "Point", "coordinates": [4.8934825, 52.3244413]},
            "properties": {
                "Soort": "Overig urinoir",
                "Prijs_per_gebruik": 0,
                "Dagen_geopend": "ma - di - wo - do - vr - za - zo",
                "Openingstijden": "24 uur per dag",
                "Omschrijving": "",
                "Foto": "Urinoir Amstelpark.JPG",
                "SELECTIE": "OVERIG",
            },
        },
        {
            "id": 59,
            "type": "Feature",
            "geometry": {"type": "Point", "coordinates": [4.9035267, 52.3822]},
            "properties": {
                "Soort": "Amsterdamse krul",
                "Prijs_per_gebruik": 0,
                "Dagen_geopend": "ma - di - wo - do - vr - za - zo",
                "Openingstijden": "",
                "Omschrijving": "Buiksloterwegveer",
                "Foto": "15504979726392887865421236777614.jpg",
                "SELECTIE": "KRUL",
            },
        },
        {
            "id": 60,
            "type": "Feature",
            "geometry": {"type": "Point", "coordinates": [4.8820227, 52.3634935]},
            "properties": {
                "Soort": "Openbaar toilet, rolstoeltoegankelijk",
                "Prijs_per_gebruik": 0.5,
                "Dagen_geopend": "",
                "Openingstijden": "24 uur per dag",
                "Omschrijving": "Leidseplein",
                "Foto": "_IMG7221V3.jpg",
                "SELECTIE": "TOEGANG",
            },
        },
        {
            "id": 61,
            "type": "Feature",
            "geometry": {"type": "Point", "coordinates": [4.8813468, 52.3625239]},
            "properties": {
                "Soort": "Openbaar toilet, rolstoeltoegankelijk",
                "Prijs_per_gebruik": 0.5,
                "Dagen_geopend": "ma - di - wo - do - vr - za - zo",
                "Openingstijden": "24 uur per dag",
                "Omschrijving": "Leidse Bosje",
                "Foto": "IMG_8973.jpg",
                "SELECTIE": "TOEGANG",
            },
        },
        {
            "id": 65,
            "type": "Feature",
            "geometry": {"type": "Point", "coordinates": [4.8950783, 52.3740568]},
            "properties": {
                "Soort": "Openbaar toilet",
                "Prijs_per_gebruik": 0.5,
                "Dagen_geopend": "ma - di - wo - do - vr - za - zo",
                "Openingstijden": "24 uur per dag",
                "Omschrijving": "Beursplein, Fietsenstalling ",
                "Foto": "IMG_9109.jpg",
                "SELECTIE": "OPENBAAR",
            },
        },
        {
            "id": 66,
            "type": "Feature",
            "geometry": {"type": "Point", "coordinates": [4.9407396, 52.313946]},
            "properties": {
                "Soort": "Toilet in parkeergarage",
                "Prijs_per_gebruik": 0,
                "Dagen_geopend": "ma - di - wo - do - vr - za - zo",
                "Openingstijden": "",
                "Omschrijving": "Arena, P+R",
                "Foto": "",
                "SELECTIE": "PARKEER",
            },
        },
        {
            "id": 67,
            "type": "Feature",
            "geometry": {"type": "Point", "coordinates": [4.8454177, 52.3790613]},
            "properties": {
                "Soort": "Toilet in parkeergarage",
                "Prijs_per_gebruik": 0,
                "Dagen_geopend": "ma - di - wo - do - vr - za - zo",
                "Openingstijden": "24 uur per dag",
                "Omschrijving": "P+R (alleen voor parkeerders)",
                "Foto": "",
                "SELECTIE": "PARKEER",
            },
        },
        {
            "id": 68,
            "type": "Feature",
            "geometry": {"type": "Point", "coordinates": [4.8897745, 52.3397984]},
            "properties": {
                "Soort": "Toilet in parkeergarage",
                "Prijs_per_gebruik": 0,
                "Dagen_geopend": "ma - di - wo - do - vr - za - zo",
                "Openingstijden": "24 uur per dag",
                "Omschrijving": "Rai, P+R (alleen voor parkeerders)",
                "Foto": "",
                "SELECTIE": "PARKEER",
            },
        },
        {
            "id": 69,
            "type": "Feature",
            "geometry": {"type": "Point", "coordinates": [4.8384517, 52.3900344]},
            "properties": {
                "Soort": "Toilet in parkeergarage",
                "Prijs_per_gebruik": 0,
                "Dagen_geopend": "",
                "Openingstijden": "24 uur per dag",
                "Omschrijving": "P+R (alleen voor parkeerders)",
                "Foto": "",
                "SELECTIE": "PARKEER",
            },
        },
        {
            "id": 70,
            "type": "Feature",
            "geometry": {"type": "Point", "coordinates": [4.8551699, 52.3443055]},
            "properties": {
                "Soort": "Toilet in parkeergarage",
                "Prijs_per_gebruik": 0,
                "Dagen_geopend": "ma - di - wo - do - vr - za - zo",
                "Openingstijden": "24 uur per dag",
                "Omschrijving": "Olympisch Stadion, P+R (alleen voor parkeerders)",
                "Foto": "",
                "SELECTIE": "PARKEER",
            },
        },
        {
            "id": 71,
            "type": "Feature",
            "geometry": {"type": "Point", "coordinates": [4.8828409, 52.3638526]},
            "properties": {
                "Soort": "Verzinkbaar urinoir",
                "Prijs_per_gebruik": 0,
                "Dagen_geopend": "",
                "Openingstijden": "Donderdag tot en met zondag van 18.00 - 7.00 uur.\r\n\r\nTussen 15.30 - 18.00 uur verplaatsing naar bovengronds.\r\ntussen 07.00 - 09.00 uur verplaatsing naar ondergronds.",
                "Omschrijving": "Urilift",
                "Foto": "IMG_8842.jpg",
                "SELECTIE": "URILIFT",
            },
        },
        {
            "id": 72,
            "type": "Feature",
            "geometry": {"type": "Point", "coordinates": [4.9363291, 52.3979741]},
            "properties": {
                "Soort": "Overig urinoir",
                "Prijs_per_gebruik": 0,
                "Dagen_geopend": "ma - di - wo - do - vr - za - zo",
                "Openingstijden": "24 uur per dag",
                "Omschrijving": "Buikslotermeerplein / Het Breed, Taxistandplaats",
                "Foto": "Screenshot_20190218_145610.jpg",
                "SELECTIE": "OVERIG",
            },
        },
        {
            "id": 73,
            "type": "Feature",
            "geometry": {"type": "Point", "coordinates": [4.8844891, 52.3849458]},
            "properties": {
                "Soort": "Toilet in parkeergarage",
                "Prijs_per_gebruik": 0,
                "Dagen_geopend": "ma - di - wo - do - vr - za - zo",
                "Openingstijden": "24 uur per dag",
                "Omschrijving": "Willemspoort, Parkeergarage (alleen voor parkeerders)",
                "Foto": "",
                "SELECTIE": "PARKEER",
            },
        },
        {
            "id": 74,
            "type": "Feature",
            "geometry": {"type": "Point", "coordinates": [4.9142073, 52.3780827]},
            "properties": {
                "Soort": "Toilet in parkeergarage",
                "Prijs_per_gebruik": 0,
                "Dagen_geopend": "ma - di - wo - do - vr - za - zo",
                "Openingstijden": "24 uur per dag",
                "Omschrijving": "Parkeergarage (alleen voor parkeerders)",
                "Foto": "",
                "SELECTIE": "PARKEER",
            },
        },
        {
            "id": 75,
            "type": "Feature",
            "geometry": {"type": "Point", "coordinates": [4.9085917, 52.3698034]},
            "properties": {
                "Soort": "Toilet in parkeergarage",
                "Prijs_per_gebruik": 0,
                "Dagen_geopend": "ma - di - wo - do - vr - za - zo",
                "Openingstijden": "24 uur per dag",
                "Omschrijving": "Parkeergarage (alleen voor parkeerders)",
                "Foto": "",
                "SELECTIE": "PARKEER",
            },
        },
        {
            "id": 76,
            "type": "Feature",
            "geometry": {"type": "Point", "coordinates": [4.9011082, 52.36735]},
            "properties": {
                "Soort": "Toilet in parkeergarage",
                "Prijs_per_gebruik": 0,
                "Dagen_geopend": "ma - di - wo - do - vr - za - zo",
                "Openingstijden": "24 uur per dag",
                "Omschrijving": "Amstel 1, Parkeergarage (alleen voor parkeerders)",
                "Foto": "",
                "SELECTIE": "PARKEER",
            },
        },
        {
            "id": 77,
            "type": "Feature",
            "geometry": {"type": "Point", "coordinates": [4.916832, 52.4078986]},
            "properties": {
                "Soort": "Toilet in parkeergarage",
                "Prijs_per_gebruik": 0,
                "Dagen_geopend": "",
                "Openingstijden": "24 uur per dag",
                "Omschrijving": "De Banne, Parkeergarage (alleen voor parkeerders)",
                "Foto": "",
                "SELECTIE": "PARKEER",
            },
        },
        {
            "id": 78,
            "type": "Feature",
            "geometry": {"type": "Point", "coordinates": [4.9414285, 52.3103656]},
            "properties": {
                "Soort": "Toilet in parkeergarage",
                "Prijs_per_gebruik": 0,
                "Dagen_geopend": "",
                "Openingstijden": "",
                "Omschrijving": "Parkeergarage ",
                "Foto": "",
                "SELECTIE": "PARKEER",
            },
        },
        {
            "id": 79,
            "type": "Feature",
            "geometry": {"type": "Point", "coordinates": [4.9456903, 52.3117427]},
            "properties": {
                "Soort": "Toilet in parkeergarage",
                "Prijs_per_gebruik": 0,
                "Dagen_geopend": "",
                "Openingstijden": "",
                "Omschrijving": "Parkeergarage ",
                "Foto": "",
                "SELECTIE": "PARKEER",
            },
        },
        {
            "id": 80,
            "type": "Feature",
            "geometry": {"type": "Point", "coordinates": [4.9384517, 52.3118226]},
            "properties": {
                "Soort": "Toilet in parkeergarage",
                "Prijs_per_gebruik": 0,
                "Dagen_geopend": "",
                "Openingstijden": "",
                "Omschrijving": "Parkeergarage ",
                "Foto": "",
                "SELECTIE": "PARKEER",
            },
        },
        {
            "id": 81,
            "type": "Feature",
            "geometry": {"type": "Point", "coordinates": [4.8837227, 52.3623231]},
            "properties": {
                "Soort": "Verzinkbaar urinoir",
                "Prijs_per_gebruik": 0,
                "Dagen_geopend": "",
                "Openingstijden": "Donderdag tot en met zondag van 18.00 - 7.00 uur.\n\nTussen 15.30 - 18.00 uur verplaatsing naar bovengronds.\ntussen 07.00 - 09.00 uur verplaatsing naar ondergronds.",
                "Omschrijving": "Urilift",
                "Foto": "IMG_8838.jpg",
                "SELECTIE": "URILIFT",
            },
        },
        {
            "id": 85,
            "type": "Feature",
            "geometry": {"type": "Point", "coordinates": [4.8836773, 52.3843331]},
            "properties": {
                "Soort": "Amsterdamse krul",
                "Prijs_per_gebruik": 0,
                "Dagen_geopend": "",
                "Openingstijden": "24 uur",
                "Omschrijving": "Haarlemmerplein",
                "Foto": "haarlememerplein.JPG",
                "SELECTIE": "KRUL",
            },
        },
        {
            "id": 86,
            "type": "Feature",
            "geometry": {"type": "Point", "coordinates": [4.9939258, 52.3932128]},
            "properties": {
                "Soort": "Amsterdamse krul",
                "Prijs_per_gebruik": 0,
                "Dagen_geopend": "",
                "Openingstijden": "24 uur",
                "Omschrijving": "Dorpsweg Ransdorp naast bushalte kerk",
                "Foto": "ransdorp.JPG",
                "SELECTIE": "KRUL",
            },
        },
        {
            "id": 87,
            "type": "Feature",
            "geometry": {"type": "Point", "coordinates": [5.0251367, 52.4132206]},
            "properties": {
                "Soort": "Amsterdamse krul",
                "Prijs_per_gebruik": 0,
                "Dagen_geopend": "",
                "Openingstijden": "24 uur",
                "Omschrijving": "Dorpsstraat Holysloot - naast bushalte Kerk",
                "Foto": "holysloot.JPG",
                "SELECTIE": "KRUL",
            },
        },
        {
            "id": 88,
            "type": "Feature",
            "geometry": {"type": "Point", "coordinates": [4.9651492, 52.383644]},
            "properties": {
                "Soort": "Amsterdamse krul",
                "Prijs_per_gebruik": 0,
                "Dagen_geopend": "",
                "Openingstijden": "24",
                "Omschrijving": "Wijkergouw / Schellingwoude Kerk",
                "Foto": "WijkergouwKerkSchellingwoude.JPG",
                "SELECTIE": "KRUL",
            },
        },
        {
            "id": 89,
            "type": "Feature",
            "geometry": {"type": "Point", "coordinates": [4.951276, 52.3973067]},
            "properties": {
                "Soort": "Overig urinoir",
                "Prijs_per_gebruik": 0,
                "Dagen_geopend": "",
                "Openingstijden": "24 uur",
                "Omschrijving": "Beemesterstraat / IJdoornlaan",
                "Foto": "IJDoornlaan_Beemsterstraat.JPG",
                "SELECTIE": "OVERIG",
            },
        },
        {
            "id": 90,
            "type": "Feature",
            "geometry": {"type": "Point", "coordinates": [4.9051621, 52.3652648]},
            "properties": {
                "Soort": "Amsterdamse krul",
                "Prijs_per_gebruik": 0,
                "Dagen_geopend": "",
                "Openingstijden": "24 uur",
                "Omschrijving": "Nieuwe Keizersgracht / Weesperstraat",
                "Foto": "IMG_8813.jpg",
                "SELECTIE": "KRUL",
            },
        },
        {
            "id": 91,
            "type": "Feature",
            "geometry": {"type": "Point", "coordinates": [4.9108778, 52.3632207]},
            "properties": {
                "Soort": "Amsterdamse krul",
                "Prijs_per_gebruik": 0,
                "Dagen_geopend": "",
                "Openingstijden": "24 uur",
                "Omschrijving": "Nieuwe Achtergracht / Roetersstraat",
                "Foto": "nieuweprinsengrachtRoetersstraat.jpg",
                "SELECTIE": "KRUL",
            },
        },
        {
            "id": 92,
            "type": "Feature",
            "geometry": {"type": "Point", "coordinates": [4.900592, 52.3732588]},
            "properties": {
                "Soort": "Amsterdamse krul",
                "Prijs_per_gebruik": 0,
                "Dagen_geopend": "",
                "Openingstijden": "24 uur",
                "Omschrijving": "Nieuwmarkt / Geldersekade",
                "Foto": "geldersekadeNieuwmarkt.jpg",
                "SELECTIE": "KRUL",
            },
        },
        {
            "id": 97,
            "type": "Feature",
            "geometry": {"type": "Point", "coordinates": [4.9593458, 52.3721075]},
            "properties": {
                "Soort": "Openbaar toilet",
                "Prijs_per_gebruik": 0.5,
                "Dagen_geopend": "ma - di - wo - do - vr - za - zo",
                "Openingstijden": "24 uur per dag ",
                "Omschrijving": "P+R Zeeburg",
                "Foto": "P en R Zeeburg.jpg",
                "SELECTIE": "OPENBAAR",
            },
        },
        {
            "id": 100,
            "type": "Feature",
            "geometry": {"type": "Point", "coordinates": [4.9008307, 52.3678834]},
            "properties": {
                "Soort": "Openbaar toilet, rolstoeltoegankelijk",
                "Prijs_per_gebruik": 0,
                "Dagen_geopend": "ma - di - wo - do - vr",
                "Openingstijden": "Alle werkdagen geopend van 08.00 - 18.00 uur en op donderdagen tot 20.00 uur.",
                "Omschrijving": "Stadsloket",
                "Foto": "images4.persgroep.net.jpg",
                "SELECTIE": "TOEGANG",
            },
        },
        {
            "id": 101,
            "type": "Feature",
            "geometry": {"type": "Point", "coordinates": [4.9330557, 52.4010569]},
            "properties": {
                "Soort": "Openbaar toilet, rolstoeltoegankelijk",
                "Prijs_per_gebruik": 0,
                "Dagen_geopend": "",
                "Openingstijden": "Alle werkdagen geopend van 08.00 - 18.00 uur en op donderdagen tot 20.00 uur.",
                "Omschrijving": "Stadsloket",
                "Foto": "25473-160906-stadsloket-stadsdeel-noord_AN-6396.jpg",
                "SELECTIE": "TOEGANG",
            },
        },
        {
            "id": 102,
            "type": "Feature",
            "geometry": {"type": "Point", "coordinates": [4.9308932, 52.356721]},
            "properties": {
                "Soort": "Openbaar toilet, rolstoeltoegankelijk",
                "Prijs_per_gebruik": 0,
                "Dagen_geopend": "ma - di - wo - do - vr",
                "Openingstijden": "Alle werkdagen geopend van 08.00 - 18.00 uur en op donderdagen tot 20.00 uur.",
                "Omschrijving": "Stadsloket",
                "Foto": "stadsloket-langer-open-1-300x194.jpg",
                "SELECTIE": "TOEGANG",
            },
        },
        {
            "id": 103,
            "type": "Feature",
            "geometry": {"type": "Point", "coordinates": [4.8938577, 52.3404557]},
            "properties": {
                "Soort": "Openbaar toilet, rolstoeltoegankelijk",
                "Prijs_per_gebruik": 0,
                "Dagen_geopend": "ma - di - wo - do - vr",
                "Openingstijden": "Alle werkdagen geopend van 08.00 - 18.00 uur en op donderdagen tot 20.00 uur.",
                "Omschrijving": "Stadsloket",
                "Foto": "28878-170307-stadsloket-stadsdeel-zuid_an-0002.jpg",
                "SELECTIE": "TOEGANG",
            },
        },
        {
            "id": 104,
            "type": "Feature",
            "geometry": {"type": "Point", "coordinates": [4.8451906, 52.3781623]},
            "properties": {
                "Soort": "Openbaar toilet, rolstoeltoegankelijk",
                "Prijs_per_gebruik": 0,
                "Dagen_geopend": "ma - di - wo - do - vr",
                "Openingstijden": "Alle werkdagen geopend van 08.00 - 18.00 uur en op donderdagen tot 20.00 uur.",
                "Omschrijving": "Stadsloket",
                "Foto": "24882-stadsloket_west_01_23aug2016_e_v_eis.jpg",
                "SELECTIE": "TOEGANG",
            },
        },
        {
            "id": 105,
            "type": "Feature",
            "geometry": {"type": "Point", "coordinates": [4.8058379, 52.3579491]},
            "properties": {
                "Soort": "Openbaar toilet, rolstoeltoegankelijk",
                "Prijs_per_gebruik": 0,
                "Dagen_geopend": "ma - di - wo - do - vr",
                "Openingstijden": "Alle werkdagen geopend van 08.00 - 18.00 uur en op donderdagen tot 20.00 uur.",
                "Omschrijving": "Stadsloket",
                "Foto": "Stadsloket NW.jpg",
                "SELECTIE": "TOEGANG",
            },
        },
        {
            "id": 106,
            "type": "Feature",
            "geometry": {"type": "Point", "coordinates": [4.9565068, 52.3161816]},
            "properties": {
                "Soort": "Openbaar toilet, rolstoeltoegankelijk",
                "Prijs_per_gebruik": 0,
                "Dagen_geopend": "",
                "Openingstijden": "Alle werkdagen geopend van 08.00 - 18.00 uur en op donderdagen tot 20.00 uur.",
                "Omschrijving": "Stadskantoor",
                "Foto": "24813-10_stadsloket-zo_16aug2016_e_v_eis1.jpg",
                "SELECTIE": "TOEGANG",
            },
        },
        {
            "id": 107,
            "type": "Feature",
            "geometry": {"type": "Point", "coordinates": [4.8908454, 52.3727418]},
            "properties": {
                "Soort": "Openbaar toilet",
                "Prijs_per_gebruik": 0,
                "Dagen_geopend": "do - vr - za",
                "Openingstijden": "Donderdag tot en met zondag van 18.00 - 7.00 uur.\r\n\r\nTussen 15.30 - 18.00 uur verplaatsing naar bovengronds.\r\ntussen 07.00 - 09.00 uur verplaatsing naar ondergronds.",
                "Omschrijving": "",
                "Foto": "PaleisstraatAchterkantDAm.jpg",
                "SELECTIE": "OPENBAAR",
            },
        },
        {
            "id": 108,
            "type": "Feature",
            "geometry": {"type": "Point", "coordinates": [4.8953037, 52.3332921]},
            "properties": {
                "Soort": "Openbaar toilet",
                "Prijs_per_gebruik": 0,
                "Dagen_geopend": "",
                "Openingstijden": "openingstijden van de kinderboerderij\r\ngesloten van november - januari\r\nfebruari - maart: 10 -17 uur\r\napril - oktober: 10 -18 uur\r\nalle dagen open tijdens de schoolvakanties",
                "Omschrijving": "",
                "Foto": "",
                "SELECTIE": "OPENBAAR",
            },
        },
        {
            "id": 109,
            "type": "Feature",
            "geometry": {"type": "Point", "coordinates": [4.8933753, 52.3295026]},
            "properties": {
                "Soort": "Openbaar toilet",
                "Prijs_per_gebruik": 0,
                "Dagen_geopend": "",
                "Openingstijden": "",
                "Omschrijving": "",
                "Foto": "",
                "SELECTIE": "OPENBAAR",
            },
        },
        {
            "id": 160,
            "type": "Feature",
            "geometry": {"type": "Point", "coordinates": [4.8920712, 52.3324386]},
            "properties": {
                "Soort": "Openbaar toilet",
                "Prijs_per_gebruik": 0,
                "Dagen_geopend": "",
                "Openingstijden": "8.00 uur tot een half uur vóór zonsondergang.\r\n",
                "Omschrijving": "MV toiletgebouw",
                "Foto": "Amstelpark.JPG",
                "SELECTIE": "OPENBAAR",
            },
        },
        {
            "id": 162,
            "type": "Feature",
            "geometry": {"type": "Point", "coordinates": [4.8949128, 52.3659589]},
            "properties": {
                "Soort": "Overig urinoir",
                "Prijs_per_gebruik": 0,
                "Dagen_geopend": "do - vr - za - zo",
                "Openingstijden": "alleen tijdens nachtelijke uren",
                "Omschrijving": "Green Pee, urinor met groene uitstraling met planten.",
                "Foto": "",
                "SELECTIE": "OVERIG",
            },
        },
        {
            "id": 163,
            "type": "Feature",
            "geometry": {"type": "Point", "coordinates": [4.8948618, 52.366031]},
            "properties": {
                "Soort": "Overig urinoir",
                "Prijs_per_gebruik": 0,
                "Dagen_geopend": "do - vr - za - zo",
                "Openingstijden": "alleen tijdens de nachtelijke uren",
                "Omschrijving": "Green Pee, urinor met groene uitstraling met planten.",
                "Foto": "",
                "SELECTIE": "OVERIG",
            },
        },
        {
            "id": 168,
            "type": "Feature",
            "geometry": {"type": "Point", "coordinates": [4.9850582, 52.3106669]},
            "properties": {
                "Soort": "Amsterdamse krul",
                "Prijs_per_gebruik": 0,
                "Dagen_geopend": "ma - di - wo - do - vr - za - zo",
                "Openingstijden": "",
                "Omschrijving": "",
                "Foto": "Plaskrul Gaapserpark.jpg",
                "SELECTIE": "KRUL",
            },
        },
        {
            "id": 179,
            "type": "Feature",
            "geometry": {"type": "Point", "coordinates": [4.8922447, 52.3645638]},
            "properties": {
                "Soort": "Openbaar toilet, rolstoeltoegankelijk",
                "Prijs_per_gebruik": 0,
                "Dagen_geopend": "ma - di - wo - do - vr - za - zo",
                "Openingstijden": "Maandag t/m vrijdag: 9.00 - 17.00 uur.\nZaterdag en zondag: 12.00 - 17.00 uur.",
                "Omschrijving": "Stadsarchief de Bazel",
                "Foto": "",
                "SELECTIE": "TOEGANG",
            },
        },
        {
            "id": 180,
            "type": "Feature",
            "geometry": {"type": "Point", "coordinates": [4.9085149, 52.3624329]},
            "properties": {
                "Soort": "Openbaar toilet, rolstoeltoegankelijk",
                "Prijs_per_gebruik": 0,
                "Dagen_geopend": "ma - di - wo - do - vr",
                "Openingstijden": "Maandag t/m donderdag 9.00 - 18.00 uur.\nVrijdag 9.00 - 18.00 uur.",
                "Omschrijving": "GGD Amsterdam",
                "Foto": "",
                "SELECTIE": "TOEGANG",
            },
        },
        {
            "id": 182,
            "type": "Feature",
            "geometry": {"type": "Point", "coordinates": [4.9212382, 52.3614494]},
            "properties": {
                "Soort": "Openbaar toilet",
                "Prijs_per_gebruik": 0,
                "Dagen_geopend": "ma - di - wo - do - vr - za - zo",
                "Openingstijden": "Alleen open als pierenbadje ook open is als het boven de 20 graden is en van mei tot en met september.\r\n\r\nMeer informatie: https://www.amsterdam.nl/sport/zwemmen/openbare/",
                "Omschrijving": "",
                "Foto": "",
                "SELECTIE": "OPENBAAR",
            },
        },
        {
            "id": 222,
            "type": "Feature",
            "geometry": {"type": "Point", "coordinates": [4.8537102, 52.383266]},
            "properties": {
                "Soort": "Openbaar toilet",
                "Prijs_per_gebruik": 0,
                "Dagen_geopend": "",
                "Openingstijden": "Alleen open als pierenbadje ook open is als het boven de 20 graden is en van mei tot en met september.",
                "Omschrijving": "",
                "Foto": "",
                "SELECTIE": "OPENBAAR",
            },
        },
        {
            "id": 223,
            "type": "Feature",
            "geometry": {"type": "Point", "coordinates": [4.8858894, 52.4139971]},
            "properties": {
                "Soort": "Openbaar toilet",
                "Prijs_per_gebruik": 0,
                "Dagen_geopend": "",
                "Openingstijden": "Alleen open als pierenbadje ook open is als het boven de 20 graden is en van mei tot en met september.",
                "Omschrijving": "",
                "Foto": "",
                "SELECTIE": "OPENBAAR",
            },
        },
        {
            "id": 224,
            "type": "Feature",
            "geometry": {"type": "Point", "coordinates": [4.8095235, 52.3825225]},
            "properties": {
                "Soort": "Openbaar toilet",
                "Prijs_per_gebruik": 0,
                "Dagen_geopend": "",
                "Openingstijden": "Alleen open als pierenbadje ook open is als het boven de 20 graden is en van mei tot en met september.",
                "Omschrijving": "",
                "Foto": "",
                "SELECTIE": "OPENBAAR",
            },
        },
        {
            "id": 225,
            "type": "Feature",
            "geometry": {"type": "Point", "coordinates": [4.8176883, 52.3551135]},
            "properties": {
                "Soort": "Openbaar toilet",
                "Prijs_per_gebruik": 0,
                "Dagen_geopend": "",
                "Openingstijden": "Alleen open als pierenbadje ook open is als het boven de 20 graden is en van mei tot en met september.",
                "Omschrijving": "",
                "Foto": "",
                "SELECTIE": "OPENBAAR",
            },
        },
        {
            "id": 226,
            "type": "Feature",
            "geometry": {"type": "Point", "coordinates": [4.8549056, 52.3274059]},
            "properties": {
                "Soort": "Openbaar toilet, rolstoeltoegankelijk",
                "Prijs_per_gebruik": 0,
                "Dagen_geopend": "",
                "Openingstijden": "De Boswinkel is geopend op woensdag t/m zondag van 10.00 - 17.00 uur.",
                "Omschrijving": "",
                "Foto": "",
                "SELECTIE": "TOEGANG",
            },
        },
        {
            "id": 227,
            "type": "Feature",
            "geometry": {"type": "Point", "coordinates": [4.8485826, 52.3243402]},
            "properties": {
                "Soort": "Openbaar toilet, rolstoeltoegankelijk",
                "Prijs_per_gebruik": 0,
                "Dagen_geopend": "",
                "Openingstijden": "",
                "Omschrijving": "Het Klein Kinderbad is vanaf mei tot en met september van 10:00 tot 19:00 uur gevuld met water bij een buitentemperatuur van boven de 20 graden en bij droog weer. Als het bad is gevuld zijn de toiletten ook open.",
                "Foto": "",
                "SELECTIE": "TOEGANG",
            },
        },
        {
            "id": 228,
            "type": "Feature",
            "geometry": {"type": "Point", "coordinates": [4.8221432, 52.3166175]},
            "properties": {
                "Soort": "Openbaar toilet, rolstoeltoegankelijk",
                "Prijs_per_gebruik": 0,
                "Dagen_geopend": "",
                "Openingstijden": "",
                "Omschrijving": "Het Groot Kinderbad is vanaf mei tot en met september van 10:00 tot 19:00 uur gevuld met water bij een buitentemperatuur van boven de 20 graden en bij droog weer. Als het bad is gevuld zijn de toiletten ook open.",
                "Foto": "",
                "SELECTIE": "TOEGANG",
            },
        },
        {
            "id": 229,
            "type": "Feature",
            "geometry": {"type": "Point", "coordinates": [4.8262613, 52.3213381]},
            "properties": {
                "Soort": "Openbaar toilet",
                "Prijs_per_gebruik": 0,
                "Dagen_geopend": "",
                "Openingstijden": "Openingstijden zijn van 10.00 - 17.00 uur.",
                "Omschrijving": "Dit toilet is open van 15 maart tot 1 november: van 15 maart tot 1 mei alleen in de weekenden; van 1 mei tot 1 november de hele week. ",
                "Foto": "",
                "SELECTIE": "OPENBAAR",
            },
        },
        {
            "id": 231,
            "type": "Feature",
            "geometry": {"type": "Point", "coordinates": [4.8166496, 52.3061697]},
            "properties": {
                "Soort": "Openbaar toilet",
                "Prijs_per_gebruik": 0,
                "Dagen_geopend": "",
                "Openingstijden": "De openingstijden zijn van 10.00 - 17.00 uur.",
                "Omschrijving": "Dit toilet is open van 15 maart tot 1 november: van 15 maart tot 1 mei alleen in de weekenden; van 1 mei tot 1 november de hele week. ",
                "Foto": "",
                "SELECTIE": "OPENBAAR",
            },
        },
        {
            "id": 232,
            "type": "Feature",
            "geometry": {"type": "Point", "coordinates": [4.8383892, 52.3895766]},
            "properties": {
                "Soort": "Openbaar toilet, rolstoeltoegankelijk",
                "Prijs_per_gebruik": 0,
                "Dagen_geopend": "",
                "Openingstijden": "24 uur per dag",
                "Omschrijving": "",
                "Foto": "",
                "SELECTIE": "TOEGANG",
            },
        },
        {
            "id": 243,
            "type": "Feature",
            "geometry": {"type": "Point", "coordinates": [4.8897202, 52.3686674]},
            "properties": {
                "Soort": "Verzinkbaar urinoir",
                "Prijs_per_gebruik": 0,
                "Dagen_geopend": "",
                "Openingstijden": "Donderdag tot en met zondag van 18.00 - 7.00 uur.\n\nTussen 15.30 - 18.00 uur verplaatsing naar bovengronds.\ntussen 7.00 - 9.00 uur verplaatsing naar ondergronds.",
                "Omschrijving": "Urilift",
                "Foto": "",
                "SELECTIE": "URILIFT",
            },
        },
        {
            "id": 245,
            "type": "Feature",
            "geometry": {"type": "Point", "coordinates": [4.8753739, 52.3877248]},
            "properties": {
                "Soort": "Openbaar toilet",
                "Prijs_per_gebruik": 0,
                "Dagen_geopend": "",
                "Openingstijden": "Open bij mooi weer van 9.00 uur - 17.00 uur.",
                "Omschrijving": "Toilet bij kiosk. Zie voor meer info http://www.de-parkwachter.nl/",
                "Foto": "",
                "SELECTIE": "OPENBAAR",
            },
        },
        {
            "id": 246,
            "type": "Feature",
            "geometry": {"type": "Point", "coordinates": [4.8970089, 52.3661463]},
            "properties": {
                "Soort": "Openbaar toilet, rolstoeltoegankelijk",
                "Prijs_per_gebruik": 0.5,
                "Dagen_geopend": "",
                "Openingstijden": "Donderdag tot en met zondag van 18.00 - 7.00 uur.\n\nTussen 15.30 - 18.00 uur verplaatsing naar bovengronds.\ntussen 07.00 - 09.00 uur verplaatsing naar ondergronds.",
                "Omschrijving": "Rolstoeltoegankelijk zelfreinigend toilet",
                "Foto": "",
                "SELECTIE": "TOEGANG",
            },
        },
        {
            "id": 247,
            "type": "Feature",
            "geometry": {"type": "Point", "coordinates": [4.8932225, 52.3711681]},
            "properties": {
                "Soort": "Toilet in parkeergarage",
                "Prijs_per_gebruik": 0,
                "Dagen_geopend": "",
                "Openingstijden": "7 dagen per week, 24 uur per dag",
                "Omschrijving": "Rokin 67, Parkeergarage (alleen voor parkeerders)",
                "Foto": "",
                "SELECTIE": "PARKEER",
            },
        },
        {
            "id": 248,
            "type": "Feature",
            "geometry": {"type": "Point", "coordinates": [4.9663353, 52.3733558]},
            "properties": {
                "Soort": "Openbaar toilet",
                "Prijs_per_gebruik": 0,
                "Dagen_geopend": "",
                "Openingstijden": "24 uur per dag geopend",
                "Omschrijving": "",
                "Foto": "",
                "SELECTIE": "OPENBAAR",
            },
        },
        {
            "id": 249,
            "type": "Feature",
            "geometry": {"type": "Point", "coordinates": [4.9663138, 52.3732281]},
            "properties": {
                "Soort": "Overig urinoir",
                "Prijs_per_gebruik": 0,
                "Dagen_geopend": "",
                "Openingstijden": "24 uur per dag geopend",
                "Omschrijving": "",
                "Foto": "",
                "SELECTIE": "OVERIG",
            },
        },
        {
            "id": 256,
            "type": "Feature",
            "geometry": {"type": "Point", "coordinates": [4.8741075, 52.3595001]},
            "properties": {
                "Soort": "Openbaar toilet",
                "Prijs_per_gebruik": 0,
                "Dagen_geopend": "",
                "Openingstijden": "",
                "Omschrijving": "",
                "Foto": "",
                "SELECTIE": "OPENBAAR",
            },
        },
        {
            "id": 258,
            "type": "Feature",
            "geometry": {"type": "Point", "coordinates": [5.0423941, 52.3067169]},
            "properties": {
                "Soort": "Openbaar toilet, rolstoeltoegankelijk",
                "Prijs_per_gebruik": 0,
                "Dagen_geopend": "",
                "Openingstijden": "Alle werkdagen geopend van 08.00 - 18.00 uur en op donderdagen tot 20.00 uur.",
                "Omschrijving": "Stadskantoor",
                "Foto": "",
                "SELECTIE": "TOEGANG",
            },
        },
        {
            "id": 260,
            "type": "Feature",
            "geometry": {"type": "Point", "coordinates": [4.8831523, 52.3641961]},
            "properties": {
                "Soort": "Verzinkbaar urinoir",
                "Prijs_per_gebruik": 0,
                "Dagen_geopend": "",
                "Openingstijden": "Donderdag tot en met zondag van 18.00 - 7.00 uur.\r\n\r\nTussen 15.30 - 18.00 uur verplaatsing naar bovengronds.\r\ntussen 07.00 - 09.00 uur verplaatsing naar ondergronds.",
                "Omschrijving": "Urilift",
                "Foto": "",
                "SELECTIE": "URILIFT",
            },
        },
        {
            "id": 261,
            "type": "Feature",
            "geometry": {"type": "Point", "coordinates": [4.9196013, 52.3605006]},
            "properties": {
                "Soort": "Openbaar toilet, rolstoeltoegankelijk",
                "Prijs_per_gebruik": 0,
                "Dagen_geopend": "ma - di - wo - do - vr - za - zo",
                "Openingstijden": "1 april tot 1 oktober 08.00 – 22.00 uur\r\n1 oktober tot 1 april: 08.00 – 20.00 uur",
                "Omschrijving": "",
                "Foto": "Toilet Oosterpark.png",
                "SELECTIE": "TOEGANG",
            },
        },
        {
            "id": 280,
            "type": "Feature",
            "geometry": {"type": "Point", "coordinates": [4.8775408, 52.369053]},
            "properties": {
                "Soort": "Openbaar toilet, rolstoeltoegankelijk",
                "Prijs_per_gebruik": 0,
                "Dagen_geopend": "",
                "Openingstijden": "",
                "Omschrijving": "",
                "Foto": "",
                "SELECTIE": "TOEGANG",
            },
        },
    ],
}
