MOCK_DATA = {
    "type": "FeatureCollection",
    "name": "OPENBARE_TOILETTEN",
    "features": [
        {
            "id": 1,
            "type": "Feature",
            "geometry": {"type": "Point", "coordinates": [4.8900955, 52.3672802]},
            "properties": {
                "Soort": "Amsterdamse krul",
                "Prijs_per_gebruik": 0,
                "Dagen_geopend": "",
                "Openingstijden": "24 uur",
                "Omschrijving": "Singel tov Bloemenmarkt",
                "Foto": "IMG_8829.jpg",
                "SELECTIE": "KRUL",
            },
        },
        {
            "id": 2,
            "type": "Feature",
            "geometry": {"type": "Point", "coordinates": [4.8892087, 52.3674372]},
            "properties": {
                "Soort": "Openbaar toilet, rolstoeltoegankelijk",
                "Prijs_per_gebruik": 0.5,
                "Dagen_geopend": "ma - di - wo - do - vr - za - zo",
                "Openingstijden": "24 uur per dag",
                "Omschrijving": "Koningsplein",
                "Foto": "IMG_8832.jpg",
                "SELECTIE": "TOEGANG",
            },
        },
        {
            "id": 3,
            "type": "Feature",
            "geometry": {"type": "Point", "coordinates": [4.8922195, 52.3662449]},
            "properties": {
                "Soort": "Verzinkbaar urinoir",
                "Prijs_per_gebruik": 0,
                "Dagen_geopend": "",
                "Openingstijden": "Donderdag tot en met zondag van 18.00 - 7.00 uur.\n\nTussen 15.30 - 18.00 uur verplaatsing naar bovengronds.\ntussen 07.00 - 09.00 uur verplaatsing naar ondergronds.",
                "Omschrijving": "Urilift",
                "Foto": "reguliersdwarsstraat.JPG",
                "SELECTIE": "URILIFT",
            },
        },
        {
            "id": 32,
            "type": "Feature",
            "geometry": {"type": "Point", "coordinates": [0, 0]},
            "properties": {
                "Soort": "Amsterdamse krul",
                "Prijs_per_gebruik": 0,
                "Dagen_geopend": "",
                "Openingstijden": "",
                "Omschrijving": "Nieuwe Achtergracht",
                "Foto": "IMG_8930.jpg",
                "SELECTIE": "KRUL",
            },
        },
        {
            "id": 261,
            "type": "Feature",
            "geometry": {"type": "Point", "coordinates": [4.9196013, 52.3605006]},
            "properties": {
                "Soort": "Openbaar toilet, rolstoeltoegankelijk",
                "Prijs_per_gebruik": 0,
                "Dagen_geopend": "ma - di - wo - do - vr - za - zo",
                "Openingstijden": "1 april tot 1 oktober 08.00 – 22.00 uur\r\n1 oktober tot 1 april: 08.00 – 20.00 uur",
                "Omschrijving": "",
                "Foto": "Toilet Oosterpark.png",
                "SELECTIE": "TOEGANG",
            },
        },
        {
            "id": 280,
            "type": "Feature",
            "geometry": {"type": "Point", "coordinates": [4.8775408, 52.369053]},
            "properties": {
                "Soort": "Openbaar toilet, rolstoeltoegankelijk",
                "Prijs_per_gebruik": 0,
                "Dagen_geopend": "",
                "Openingstijden": "",
                "Omschrijving": "",
                "Foto": "",
                "SELECTIE": "TOEGANG",
            },
        },
    ],
}
