# Generated by Django 4.2.17 on 2025-01-28 14:49

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="NotificationSchedule",
            fields=[
                (
                    "device_id",
                    models.CharField(max_length=255, primary_key=True, serialize=False),
                ),
                ("bag_nummeraanduiding_id", models.CharField(max_length=255)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
