# Generated by Django 4.2.20 on 2025-03-27 13:23

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("waste", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="notificationschedule",
            name="updated_at",
            field=models.DateTimeField(null=True),
        ),
    ]
