# Generated by Django 5.1 on 2025-12-11 09:41

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("waste", "0003_manualnotification"),
    ]

    operations = [
        migrations.AlterField(
            model_name="manualnotification",
            name="title",
            field=models.CharField(
                default="Afvalwijzer", max_length=255, verbose_name="Titel"
            ),
        ),
    ]
