# Generated by Django 5.1 on 2026-01-26 13:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("waste", "0004_alter_manualnotification_title"),
    ]

    operations = [
        migrations.CreateModel(
            name="RecycleLocation",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255, verbose_name="Naam")),
                (
                    "city",
                    models.CharField(
                        default="Amsterdam", max_length=100, verbose_name="Plaatsnaam"
                    ),
                ),
                (
                    "city_district",
                    models.CharField(
                        blank=True, max_length=100, verbose_name="Stadsdeel"
                    ),
                ),
                (
                    "street",
                    models.CharField(max_length=1000, verbose_name="Straatnaam"),
                ),
                (
                    "number",
                    models.IntegerField(
                        blank=True, null=True, verbose_name="Huisnummer"
                    ),
                ),
                (
                    "addition_letter",
                    models.CharField(blank=True, null=True, verbose_name="Huisletter"),
                ),
                (
                    "addition_number",
                    models.CharField(
                        blank=True, null=True, verbose_name="Huisnummertoevoeging"
                    ),
                ),
                (
                    "postal_code",
                    models.CharField(max_length=7, verbose_name="Postcode"),
                ),
                (
                    "latitude",
                    models.DecimalField(
                        decimal_places=7, max_digits=9, verbose_name="Latitude"
                    ),
                ),
                (
                    "longitude",
                    models.DecimalField(
                        decimal_places=7, max_digits=9, verbose_name="Longitude"
                    ),
                ),
                (
                    "commercial_waste",
                    models.BooleanField(default=False, verbose_name="Bedrijfsafval"),
                ),
            ],
            options={
                "verbose_name": "Recyclepunt",
                "verbose_name_plural": "Recyclepunten",
            },
        ),
        migrations.CreateModel(
            name="OpeningHoursException",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "description",
                    models.CharField(
                        blank=True,
                        max_length=200,
                        null=True,
                        verbose_name="Reden van de uitzondering",
                    ),
                ),
                ("date", models.DateField(verbose_name="Datum")),
                ("opens_time", models.TimeField(blank=True, null=True)),
                ("closes_time", models.TimeField(blank=True, null=True)),
                (
                    "affected_locations",
                    models.ManyToManyField(
                        help_text="Selecteer de recycle punten waar deze uitzondering voor geldt",
                        to="waste.recyclelocation",
                        verbose_name="Recyclepunt",
                    ),
                ),
            ],
            options={
                "verbose_name": "Openingstijden uitzondering",
                "verbose_name_plural": "Openingstijden uitzonderingen",
            },
        ),
        migrations.CreateModel(
            name="RecycleLocationOpeningHours",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "recycle_location",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="waste.recyclelocation",
                        verbose_name="Recyclepunt",
                    ),
                ),
            ],
            options={
                "verbose_name": "Openingstijd regulier",
                "verbose_name_plural": "Openingstijden regulier",
            },
        ),
        migrations.CreateModel(
            name="RegularOpeningHours",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "opens_time",
                    models.TimeField(
                        blank=True, null=True, verbose_name="Openingstijd"
                    ),
                ),
                (
                    "closes_time",
                    models.TimeField(
                        blank=True, null=True, verbose_name="Sluitingstijd"
                    ),
                ),
                (
                    "day_of_week",
                    models.IntegerField(
                        choices=[
                            (0, "Zondag"),
                            (1, "Maandag"),
                            (2, "Dinsdag"),
                            (3, "Woensdag"),
                            (4, "Donderdag"),
                            (5, "Vrijdag"),
                            (6, "Zaterdag"),
                        ],
                        verbose_name="Dag van de week",
                    ),
                ),
                (
                    "recycle_location_opening_hours",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="waste.recyclelocationopeninghours",
                        verbose_name="Openingstijden recyclepunt",
                    ),
                ),
            ],
            options={
                "verbose_name": "Openingstijd",
                "verbose_name_plural": "Openingstijden",
                "unique_together": {("recycle_location_opening_hours", "day_of_week")},
            },
        ),
    ]
