# Generated by Django 5.1 on 2026-01-29 09:32

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("waste", "0005_recyclelocation_openinghoursexception_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="recyclelocation",
            name="latitude",
            field=models.DecimalField(
                decimal_places=8, max_digits=10, verbose_name="Latitude"
            ),
        ),
        migrations.AlterField(
            model_name="recyclelocation",
            name="longitude",
            field=models.DecimalField(
                decimal_places=8, max_digits=10, verbose_name="Longitude"
            ),
        ),
    ]
