# Generated by Django 5.1 on 2026-03-25 11:46

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("waste", "0006_alter_recyclelocation_latitude_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="WasteCollectionException",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("date", models.DateField(unique=True, verbose_name="Datum")),
                (
                    "reason",
                    models.CharField(
                        max_length=200, verbose_name="Reden van de uitzondering"
                    ),
                ),
            ],
            options={
                "verbose_name": "Afvalophaling uitzondering",
                "verbose_name_plural": "Afvalophaling uitzonderingen",
            },
        ),
    ]
