# Generated by Django 5.1 on 2026-03-30 14:03

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("waste", "0007_wastecollectionexception"),
    ]

    operations = [
        migrations.CreateModel(
            name="WasteCollectionRouteName",
            fields=[
                (
                    "name",
                    models.CharField(max_length=300, primary_key=True, serialize=False),
                ),
            ],
            options={
                "ordering": ["name"],
            },
        ),
        migrations.AddField(
            model_name="wastecollectionexception",
            name="affected_routes",
            field=models.ManyToManyField(
                help_text="Selecteer de afvalophaalroutes waar deze uitzondering voor geldt",
                to="waste.wastecollectionroutename",
                verbose_name="afvalwijzerRoutenaam",
            ),
        ),
    ]
