# Generated by Django 6.0.6 on 2026-07-10 09:21

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("waste", "0008_wastecollectionroutename_and_more"),
    ]

    operations = [
        migrations.DeleteModel(
            name="NotificationSchedule",
        ),
    ]
