# Generated by Django 6.0.6 on 2026-08-21 07:52

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("waste", "0009_delete_notificationschedule"),
    ]

    operations = [
        migrations.AddField(
            model_name="manualnotification",
            name="affected_routes",
            field=models.ManyToManyField(
                blank=True,
                help_text="Selecteer de afvalophaalroutes waar deze notificatie voor geldt. Als er geen routes geselecteerd zijn, wordt de notificatie naar alle gebruikers gestuurd.",
                to="waste.wastecollectionroutename",
                verbose_name="afvalwijzerRoutenaam",
            ),
        ),
    ]
