# Generated by Django 5.2 on 2025-05-07 11:06

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("image", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="imageset",
            name="identifier",
            field=models.CharField(max_length=64, null=True),
        ),
        migrations.AddIndex(
            model_name="imageset",
            index=models.Index(
                condition=models.Q(("identifier__isnull", False)),
                fields=["identifier"],
                name="idx_identifier_not_null",
            ),
        ),
        migrations.AddConstraint(
            model_name="imageset",
            constraint=models.UniqueConstraint(
                condition=models.Q(("identifier__isnull", False)),
                fields=("identifier",),
                name="image_imageset_unique_identifier",
            ),
        ),
    ]
