MOCK_RESPONSE = {
    "page": 1,
    "row_per_page": 10,
    "count": 8,
    "data": [
        {
            "type": "client_product",
            "id": 1003,
            "zone": "CE02E Centrum-2e",
            "zone_group": None,
            "permit_description": "Bewonersvergunning",
            "permit_name": "Bewonersvergunning",
            "permit_type": "resident",
            "is_webform": False,
            "parent_request_id": None,
            "started_at": "2025-04-02T14:22:03+00:00",
            "ended_at": "2025-09-13T21:59:59+00:00",
            "cancelled_at": "2025-09-13T21:59:59+00:00",
            "is_overflow_permit": False,
            "status": "ACTIVE",
            "vrns": [
                {
                    "id": 1003,
                    "vrn": "AB1003",
                    "temporary_vrn": None,
                    "temporary_ended_at": None,
                    "activated_at": "2025-04-02T14:22:17+00:00",
                    "ended_at": None,
                    "is_temporary": False,
                    "is_future": False,
                    "has_change_plate_in_progress": False,
                    "has_parking_session": False,
                }
            ],
        },
        {
            "type": "client_product",
            "id": 10001,
            "zone": "BA01B West-1.2",
            "zone_group": None,
            "permit_description": "Tarief \u20ac5,00, 150 uur 65% korting",
            "permit_name": "Bezoekersparkeervergunning",
            "permit_type": "visitor",
            "is_webform": False,
            "parent_request_id": None,
            "started_at": "2025-09-09T22:00:00+00:00",
            "ended_at": "2124-09-09T22:00:00+00:00",
            "cancelled_at": None,
            "is_overflow_permit": False,
            "status": "FUTURE",
            "vrns": [],
        },
        {
            "type": "client_product",
            "id": 1001,
            "zone": "CE02E Centrum-2e",
            "zone_group": None,
            "permit_description": "Bewonersvergunning",
            "permit_name": "Bewonersvergunning",
            "permit_type": "resident",
            "is_webform": False,
            "parent_request_id": None,
            "started_at": "2022-01-01T00:00:00+00:00",
            "ended_at": "2025-04-02T23:59:59+00:00",
            "cancelled_at": None,
            "is_overflow_permit": False,
            "status": "ARCHIVED",
            "vrns": [
                {
                    "id": 1002,
                    "vrn": "67WFD6",
                    "temporary_vrn": None,
                    "temporary_ended_at": None,
                    "activated_at": "2023-01-01T00:00:00+00:00",
                    "ended_at": None,
                    "is_temporary": False,
                    "is_future": False,
                    "has_change_plate_in_progress": False,
                    "has_parking_session": False,
                }
            ],
        },
    ],
}
