from .boat_charging_models import BoatChargingSession as BoatChargingSession
from .burning_guide_models import BurningGuideDevice as BurningGuideDevice
from .waste_guide_models import WasteDevice as WasteDevice
