# Generated by Django 5.1 on 2025-09-17 13:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("survey", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="survey",
            name="cooldown",
        ),
        migrations.RemoveField(
            model_name="survey",
            name="fraction",
        ),
        migrations.RemoveField(
            model_name="survey",
            name="minimum_actions",
        ),
        migrations.CreateModel(
            name="SurveyConfiguration",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "location",
                    models.CharField(
                        max_length=200, unique=True, verbose_name="Locatie"
                    ),
                ),
                (
                    "fraction",
                    models.FloatField(
                        default=1.0,
                        help_text="Hoeveel procent van de gebruikers moet deze vragenlijst krijgen?",
                        verbose_name="Fractie",
                    ),
                ),
                (
                    "cooldown",
                    models.IntegerField(
                        default=0,
                        help_text="Aantal dagen voordat een gebruiker deze vragenlijst opnieuw aangeboden kan krijgen. 0 = geen cooldown.",
                        verbose_name="Cooldown",
                    ),
                ),
                (
                    "minimum_actions",
                    models.IntegerField(
                        default=0,
                        help_text="Minimaal aantal acties dat een gebruiker moet hebben uitgevoerd voordat deze vragenlijst wordt aangeboden.",
                        verbose_name="Minimaal aantal acties",
                    ),
                ),
                (
                    "survey",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="configuration",
                        to="survey.survey",
                    ),
                ),
            ],
            options={
                "verbose_name": "Vragenlijst configuratie",
                "verbose_name_plural": "Vragenlijst configuraties",
            },
        ),
    ]
