# Generated by Django 5.1 on 2025-11-18 11:40

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("survey", "0002_remove_survey_cooldown_remove_survey_fraction_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="question",
            options={"verbose_name": "Vraag", "verbose_name_plural": "Vragen"},
        ),
        migrations.RemoveField(
            model_name="question",
            name="sort_order",
        ),
    ]
