# Generated by Django 5.1 on 2025-12-01 15:16

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("survey", "0003_alter_question_options_remove_question_sort_order"),
    ]

    operations = [
        migrations.AddField(
            model_name="question",
            name="textarea_rows",
            field=models.IntegerField(default=4),
        ),
        migrations.AlterField(
            model_name="question",
            name="question_type",
            field=models.CharField(
                choices=[
                    ("text", "Text"),
                    ("radio", "Radio"),
                    ("select", "Select"),
                    ("checkbox", "Check"),
                    ("textarea", "Textarea"),
                    ("rating", "Rating"),
                    ("selection_buttons", "Buttons"),
                ],
                max_length=20,
            ),
        ),
    ]
