# Generated by Django 5.1 on 2025-12-19 09:10

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("survey", "0004_question_textarea_rows_alter_question_question_type"),
    ]

    operations = [
        migrations.AlterField(
            model_name="question",
            name="question_type",
            field=models.CharField(
                choices=[
                    ("selection_buttons", "Buttons"),
                    ("checkbox", "Check"),
                    ("date", "Date"),
                    ("email", "Email"),
                    ("numeric", "Numeric"),
                    ("radio", "Radio"),
                    ("rating", "Rating"),
                    ("select", "Select"),
                    ("tel", "Telephone"),
                    ("text", "Text"),
                    ("textarea", "Textarea"),
                    ("time", "Time"),
                    ("url", "Url"),
                ],
                max_length=20,
            ),
        ),
    ]
