# Generated by Django 5.1 on 2026-02-04 11:47

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("survey", "0005_alter_question_question_type"),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="condition",
            unique_together={("question", "reference_question", "value")},
        ),
    ]
