# Generated by Django 5.1 on 2026-03-26 10:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("survey", "0006_alter_condition_unique_together"),
    ]

    operations = [
        migrations.AlterField(
            model_name="answer",
            name="answer",
            field=models.CharField(max_length=1000, verbose_name="Antwoord"),
        ),
        migrations.AlterField(
            model_name="answer",
            name="question",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                to="survey.question",
                verbose_name="Vraag",
            ),
        ),
        migrations.AlterField(
            model_name="surveyversionentry",
            name="created_at",
            field=models.DateTimeField(auto_now_add=True, verbose_name="Aangemaakt op"),
        ),
        migrations.AlterField(
            model_name="surveyversionentry",
            name="entry_point",
            field=models.CharField(max_length=1000, verbose_name="Toegangspunt"),
        ),
        migrations.AlterField(
            model_name="surveyversionentry",
            name="survey_version",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                to="survey.surveyversion",
                verbose_name="Vragenlijst versie",
            ),
        ),
    ]
